Add tests of slice luks with different disk format
autotest/tp-libvirt pull request #2710
Opened 2020-04-24 04:31 UTC by jgao12345

Add tests of slice luks with different disk format
# avocado run --vt-type libvirt type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug.slice_test.qcow2_internal.normal_test.encryption_out_source
JOB ID     : aeee0693b46eb9cdaa538624309f0f955428be67
JOB LOG    : /root/avocado/job-results/job-2020-04-24T00.20-aeee069/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug.slice_test.qcow2_internal.normal_test.encryption_out_source: PASS (87.58 s)

# avocado run --vt-type libvirt type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug.slice_test.raw_luks.normal_test.encryption_in_source
JOB ID     : ead446774b88d016a1cae1d1bf8c5749bb76fd10
JOB LOG    : /root/avocado/job-results/job-2020-04-24T00.24-ead4467/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug.slice_test.raw_luks.normal_test.encryption_in_source: PASS (68.86 s)

 avocado run --vt-type libvirt type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug.slice_test.qcow2_internal.error_test.encryption_in_source
JOB ID     : a049f30b20d865d953678f025e77c6b8cd60a6b5
JOB LOG    : /root/avocado/job-results/job-2020-04-24T00.26-a049f30/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug.slice_test.qcow2_internal.error_test.encryption_in_source: PASS (74.34 s)

2020-04-27 02:20 UTC, qiankehan commented on libvirt/tests/cfg/virtual_disks/virtual_disks_luks.cfg
> +            luks_extra_elements = "--object secret,id=sec0,data=`printf password | base64`,format=base64' \
The variable here is only the value of data. It is not proper to make such a long options as a variable.
No necessity to user base64 format. More simple example:
data=PASSWORD_HERE,format=raw.

2020-04-27 02:25 UTC, qiankehan commented on libvirt/tests/cfg/virtual_disks/virtual_disks_luks.cfg
> +             -o encrypt.format=luks,encrypt.key-secret=sec0"
`-o encrypt.format=luks,encrypt.key-secret=sec0` only works for creating qcow2 with luks.
To create raw with luks, use `-o key-secret=`

2020-04-27 02:28 UTC, qiankehan commented on libvirt/tests/src/virtual_disks/virtual_disks_luks.py
> +                    create_vol(pool_name, vol_encryption_params, vol_params)
The test is for virtual disk. No need to implement libvirt storage functions.
Just create the image directly by qemu-img

2020-04-27 02:45 UTC, qiankehan commented on libvirt/tests/src/virtual_disks/virtual_disks_luks.py
> +        if volume_target_format == "qcow2":
Together with the former review:
For virtual disk tests, the  scenarios related to libvirt storage are `pool type disk` and `incremental storage migration`. For the rest cases, the storage part should be involved as less as possible because it is a really low priority feature.
The `check_dev_format` here is a libvirt storage scenario. It checks if the format of the volume created by vol-create API is expected. 
For virtual disk tests, that scenario is an excess because the volume is not created by libvirt.

2020-04-27 02:49 UTC, qiankehan commented on libvirt/tests/src/virtual_disks/virtual_disks_encryption.py
> +                process.run("virsh pool-refresh %s" % pool_name)
Again, unnecessary libvirt storage call here.

2020-04-27 02:53 UTC, qiankehan commented on libvirt/tests/cfg/virtual_disks/virtual_disks_encryption.cfg
> +            test_size = "1"
Too small size.

2020-04-27 07:37 UTC, jgao12345 commented on libvirt/tests/cfg/virtual_disks/virtual_disks_luks.cfg
> +            luks_extra_elements = "--object secret,id=sec0,data=`printf password | base64`,format=base64' \
I will fix it after i confirm the format of secret.

2020-04-27 07:38 UTC, jgao12345 commented on libvirt/tests/src/virtual_disks/virtual_disks_luks.py
> +                    create_vol(pool_name, vol_encryption_params, vol_params)
I will modify the whole structure in another pr,i will add the pr link here later.

2020-04-27 07:49 UTC, qiankehan commented on libvirt/tests/src/virtual_disks/virtual_disks_luks.py
> +                    create_vol(pool_name, vol_encryption_params, vol_params)
It's better to fix it in this PR because you another PR may be conflict with this one.
Write a commit to replace the functions of storage then the commits of slice luks

2020-04-27 07:59 UTC, jgao12345 commented on libvirt/tests/cfg/virtual_disks/virtual_disks_luks.cfg
> +             -o encrypt.format=luks,encrypt.key-secret=sec0"
Yeah,but now in virtual_disks_luks.py, we only use it to create raw with luks,and we still use the vol-create to prepare qcow2 images.
So i think this should be changed together with the creation of the image in another pr.

2020-04-29 10:11 UTC, dzhengfy commented on libvirt/tests/src/virtual_disks/virtual_disks_encryption.py
> +                vol_encryption_params['encryption'] = volume_target_encypt
What is the reason to assign value twice for vol_encryption_params['encryption']?

2020-07-31 09:47 UTC, jgao12345 commented on libvirt/tests/src/virtual_disks/virtual_disks_encryption.py
> +                vol_encryption_params['encryption'] = volume_target_encypt
I think you are right , these code repeatedly takes the same value, so i delete the last one.

2020-08-17 09:14 UTC, jgao12345 commented
> Please also provide more test results in this module, like not_slice_test cases. Thanks.
> As a new case name pattern is inserted into the existing cases' name, we'd better consider if it is the best choice.
# avocado run --vt-type libvirt type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug
JOB ID     : 3468366de2c68e1bb81a3899527730348ce15512
JOB LOG    : /root/avocado/job-results/job-2020-08-17T00.18-3468366/job.log
 (01/12) type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug.slice_test.qcow2_internal.normal_test.encryption_in_source: ERROR: Error parsing XML: '' (94.83 s)
 (02/12) type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug.slice_test.qcow2_internal.normal_test.encryption_out_source: PASS (139.55 s)
 (03/12) type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug.slice_test.qcow2_internal.error_test.encryption_in_source: ERROR: Error parsing XML: '' (88.16 s)
 (04/12) type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug.slice_test.qcow2_internal.error_test.encryption_out_source: PASS (123.08 s)
 (05/12) type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug.slice_test.raw_luks.normal_test.encryption_in_source: PASS (85.25 s)
 (06/12) type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug.slice_test.raw_luks.normal_test.encryption_out_source: PASS (84.15 s)
 (07/12) type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug.not_slice_test.qcow2_internal.normal_test.encryption_in_source: ERROR: Failed to create volume.Error: error: Failed to create vol from /var/tmp/xml_utils_temp_tuei38q9.xml\nerror: unsupported configuration: creation of qcow2 encrypted image is not supported\n (37.60 s)
 (08/12) type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug.not_slice_test.qcow2_internal.normal_test.encryption_out_source: ERROR: Failed to create volume.Error: error: Failed to create vol from /var/tmp/xml_utils_temp_ykpbvd6p.xml\nerror: unsupported configuration: creation of qcow2 encrypted image is not supported\n (35.67 s)
 (09/12) type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug.not_slice_test.qcow2_internal.error_test.encryption_in_source: ERROR: Failed to create volume.Error: error: Failed to create vol from /var/tmp/xml_utils_temp_fryiqdz3.xml\nerror: unsupported configuration: creation of qcow2 encrypted image is not supported\n (35.87 s)
 (10/12) type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug.not_slice_test.qcow2_internal.error_test.encryption_out_source: ERROR: Failed to create volume.Error: error: Failed to create vol from /var/tmp/xml_utils_temp_07j588ak.xml\nerror: unsupported configuration: creation of qcow2 encrypted image is not supported\n (36.15 s)
 (11/12) type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug.not_slice_test.raw_luks.normal_test.encryption_in_source: PASS (83.62 s)
 (12/12) type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug.not_slice_test.raw_luks.normal_test.encryption_out_source: PASS (83.07 s)
RESULTS    : PASS 6 | ERROR 6 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 930.39 s

Failed cases are blocked by libvirt-ci blacklist as:
- when: any_package('qemu-kvm', 'qemu-kvm-rhev', 'qemu-kvm-ma') >= '2.4.0'
  description: 'with qemu-kvm newer than or equal to 2.4.0'
  not-supported:
      - test:
          - virtual_disks.encryption..qcow2_internal
        feature: 'AES-CBC encrypted qcow2 images'

2020-09-01 08:06 UTC, dzhengfy reviewed
LGTM. 
But could you provide test results after you did these changes?

2020-09-02 02:54 UTC, jgao12345 commented
> LGTM.
> But could you provide test results after you did these changes?

# avocado run --vt-type libvirt type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug
JOB ID     : a198f95f9ae004c45cbc1077f0a0db169f1d9163
JOB LOG    : /root/avocado/job-results/job-2020-09-01T22.26-a198f95/job.log
 (01/12) type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug.slice_test.qcow2_internal.normal_test.encryption_in_source: PASS (227.82 s)
 (02/12) type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug.slice_test.qcow2_internal.normal_test.encryption_out_source: PASS (225.82 s)
 (03/12) type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug.slice_test.qcow2_internal.error_test.encryption_in_source: PASS (220.92 s)
 (04/12) type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug.slice_test.qcow2_internal.error_test.encryption_out_source: PASS (224.43 s)
 (05/12) type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug.slice_test.raw_luks.normal_test.encryption_in_source: PASS (76.52 s)
 (06/12) type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug.slice_test.raw_luks.normal_test.encryption_out_source: PASS (74.70 s)
 (07/12) type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug.not_slice_test.qcow2_internal.normal_test.encryption_in_source: ERROR: Failed to create volume.Error: error: Failed to create vol from /var/tmp/xml_utils_temp_spa702xg.xml\nerror: unsupported configuration: creation of qcow2 encrypted image is not supported\n (339.61 s)
 (08/12) type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug.not_slice_test.qcow2_internal.normal_test.encryption_out_source: |^C
Interrupt requested. Waiting 2 seconds for test to finish (ignoring new Ctrl+C until then)
/
INTERRUPTED: Runner error occurred: Interrupted by ctrl+c\nOriginal status: ERROR\n{'name': '08-type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug.not_slice_test.qcow2_internal.normal_test.encryption_out_source', 'logdir': '/root/avocado/job-resul... (198.48 s)
RESULTS    : PASS 6 | ERROR 1 | FAIL 0 | SKIP 4 | WARN 0 | INTERRUPT 1 | CANCEL 0
JOB TIME   : 1592.37 s

And the test with not_slice_test with qcow2 has been blocked by CI blacklist.

2020-09-02 06:54 UTC, dzhengfy submitted a review, later dismissed
LGTM

2020-09-03 10:03 UTC, qiankehan commented on libvirt/tests/cfg/virtual_disks/virtual_disks_encryption.cfg
> +        - slice_test:
@dzhengfy I don't think so. Slice element is optional. When you don't mention it, there is no slice in cases.

2020-09-03 10:04 UTC, qiankehan commented on libvirt/tests/cfg/virtual_disks/virtual_disks_encryption.cfg
> +        - not_slice_test:
No need to mention "no slice"

2020-09-03 10:19 UTC, qiankehan requested changes

2020-09-03 10:19 UTC, qiankehan commented on libvirt/tests/src/virtual_disks/virtual_disks_encryption.py
> +                create_vol(pool_name, vol_encryption_params, vol_params)
I wonder why the luks images are created by 2 ways: qemu-img and storage vol. Why not use qemu-img always

2020-09-03 12:18 UTC, jgao12345 commented on libvirt/tests/cfg/virtual_disks/virtual_disks_encryption.cfg
> +        - slice_test:
I have a little confusion here, I will reconfirm with you through IRC later.
Usually we use 'with_slice' and 'without_slice' which are more formal. But it is not a must to change.
> @dzhengfy I don't think so. Slice element is optional. When you don't mention it, there is no slice in cases.

I have a little confusion here, I will reconfirm with you through IRC later.

2020-09-17 11:16 UTC, dzhengfy commented
@jgao12345 , As this PR is over 4 months and we need it merged as soon as possible. Regarding removing vol-create usage, I think it is out of the scope of this PR, so we definitely are OKay to do it in a new PR. @qiankehan What do you think about?

2020-09-18 01:10 UTC, jgao12345 commented
> @jgao12345 , As this PR is over 4 months and we need it merged as soon as possible. Regarding removing vol-create usage, I think it is out of the scope of this PR, so we definitely are OKay to do it in a new PR. @qiankehan What do you think about?

I think it‘s ok. This case should use qemu-img to prepare the image, but there is no time to change it recently. It can be closed temporarily. I will mention the new pr later.

2020-09-23 09:11 UTC, jgao12345 commented
Close it since there have been some other changes, and this pr comment is a bit confusing, I will create a new pr later.

2020-09-23 09:11 UTC, closed without merging