Add cfg file definition convertions
autotest/tp-libvirt pull request #2861
Opened 2020-06-15 07:28 UTC by chunfuwen

In order to provide one consistent, human-readable, maintainable test case names, it is necessary to
apply some conventions rules to Cartesian Configuration format.

Signed-off-by: chunfuwen <chwen@redhat.com>

2020-06-16 08:25 UTC, chunfuwen commented
@santwana 
@smitterl 
@kylazhang 
@dzhengfy 
Welcome inputs and thoughts.

2020-06-17 04:05 UTC, chloerh commented on cfg_file_definition_convention.rst
> +
Currently we have fewer cases that need to be constructed from matrix, but more cases with different structures and sets of parameters. And they usually look like this in our test cfg files:

```
- positive_test:
    variants:
        - test_1:
        - test_2:
- negative_test:
    variants:
        - n_test_1:
        - n_test_2:
```
The advantage of this way is that we only need to place test cases to the correct part (positive or negative) without having to concern about the whole structure of the cfg file which influences all its test cases.  And no need to put a lot of cases' patterns under '-positive_test' or '-negative_test' like those matrix cfg files: virsh_attach_detach_disk_matrix.cfg  or virsh_attach_detach_interface_matrix.cfg  with one single line that has 2153 characters just because it's filled with only xxx, xxx, xxx ...

2020-07-10 02:08 UTC, kylazhang commented on cfg_file_definition_convention.rst
> +
Agree

2020-07-10 02:11 UTC, kylazhang commented
@chunfuwen I think you can add more for some tips you ever mentioned for condition in cfg  and parmas for specific cases in cfg

2020-09-02 08:33 UTC, smitterl commented on cfg_file_definition_convention.rst
> +
+1

2020-09-02 08:39 UTC, smitterl requested changes
Thank you @chunfuwen Could you check some minor grammatical issues I think to have spotted?

2020-09-02 08:39 UTC, smitterl commented on cfg_file_definition_convention.rst
> +Cartesian configuration files(Cfg) will define test case names.
"files(Cfg)" -> "files (.cfg)"

2020-09-02 08:39 UTC, smitterl commented on cfg_file_definition_convention.rst
> +How cfg works? please refer to https://avocado-vt.readthedocs.io/en/latest/CartesianConfig.html
"How cfg works? please" -> "How do cfg files work? Please"

2020-09-02 08:39 UTC, smitterl commented on cfg_file_definition_convention.rst
> +In order to provide one consistent, human-readable, maintainable test case names, it is necessary to
"one [..] names" -> "[..] names"

2020-09-02 08:39 UTC, smitterl commented on cfg_file_definition_convention.rst
> +   of whole test case name. The higher level one variant represents, the more lower its position should be placed in. for example:
"more lower" -> "lower"

2020-09-15 08:56 UTC, chunfuwen commented on cfg_file_definition_convention.rst
> +Cartesian configuration files(Cfg) will define test case names.
updated

2020-09-15 08:57 UTC, chunfuwen commented on cfg_file_definition_convention.rst
> +How cfg works? please refer to https://avocado-vt.readthedocs.io/en/latest/CartesianConfig.html
updated

2020-09-15 08:58 UTC, chunfuwen commented on cfg_file_definition_convention.rst
> +In order to provide one consistent, human-readable, maintainable test case names, it is necessary to
updated

2020-09-15 08:58 UTC, chunfuwen commented on cfg_file_definition_convention.rst
> +   of whole test case name. The higher level one variant represents, the more lower its position should be placed in. for example:
updated

2020-09-15 09:08 UTC, chunfuwen commented on cfg_file_definition_convention.rst
> +
updated

2020-09-15 09:30 UTC, chunfuwen commented on cfg_file_definition_convention.rst
> +How cfg works? please refer to https://avocado-vt.readthedocs.io/en/latest/CartesianConfig.html
updated

2020-09-15 09:31 UTC, chunfuwen commented on cfg_file_definition_convention.rst
> +
updated

2020-09-15 09:31 UTC, chunfuwen commented on cfg_file_definition_convention.rst
> +Cartesian configuration files(Cfg) will define test case names.
updated

2020-09-15 09:31 UTC, chunfuwen commented on cfg_file_definition_convention.rst
> +In order to provide one consistent, human-readable, maintainable test case names, it is necessary to
updated

2020-09-15 09:32 UTC, chunfuwen commented on cfg_file_definition_convention.rst
> +   of whole test case name. The higher level one variant represents, the more lower its position should be placed in. for example:
updated

2020-09-16 06:50 UTC, chloerh approved these changes

2020-09-17 01:10 UTC, chunfuwen commented
@smitterl 
@kylazhang 
comments updated accordingly ,please take a look.

2020-09-17 09:41 UTC, kylazhang approved these changes

2020-09-21 01:34 UTC, merged