Fix disk_bus_virtio.device_disk.default case failure
autotest/tp-libvirt pull request #3068
Opened 2020-09-21 04:33 UTC by chunfuwen

After libvirt 6.6.0, scsi=on/off flag is removed from qemu command line after libvirt 6.6.0,
so set device_option .* to make code compatible

Signed-off-by: chunfuwen <chwen@redhat.com>

2020-09-21 04:33 UTC, chunfuwen commented
DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
PASS 1-type_specific.io-github-autotest-libvirt.virtual_disks.multidisks.coldplug.single_disk_test.disk_bus_device_option.disk_bus_virtio.device_disk.default

2020-09-22 10:20 UTC, sathnaga requested changes

2020-09-22 10:20 UTC, sathnaga commented on libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
> +                        device_option = ".*"
better to handle grep command option aswell, we can simply omit `device_option` if libvirt_version greater than 6.6 why to update it with `.*`, any specific reason, `.*` kind of regular expression might match unwanted strings aswell, better to drop it completely.

2020-09-23 05:14 UTC, chunfuwen commented on libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
> +                        device_option = ".*"
the regular expression are composed by server string including device_option, see line 1793
                    cmd += (" | grep virtio-blk-pci,%s,bus=pci.%x,addr=0x%x"
                            % (device_option, dev_bus, pci_slot))
so as per my understanding, device_option as'.*' will  bring very limited effect due to constraints of other string

2020-10-14 04:45 UTC, sathnaga commented on libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
> +                        device_option = ".*"
@chunfuwen 
my suggestion was to update the grep cmd itself, for 6.6.0 something like
```
cmd += (" | grep virtio-blk-pci,bus=pci.%x,addr=0x%x" % (dev_bus, pci_slot))
```
not sure if there is any other constraints by doing it though.

`.*` will eventually pass anything even with `scsi=on/off` too, so my suggestion was to drop to completely.

2020-10-14 04:45 UTC, sathnaga requested changes
Comment given above

2020-10-19 01:42 UTC, chunfuwen commented on libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
> +                        device_option = ".*"
updated accordingly

2020-10-20 07:33 UTC, sathnaga approved these changes
LGTM

2020-10-21 03:29 UTC, merged