virsh_detach_device: mixed detach disk
autotest/tp-libvirt pull request #3075
Opened 2020-09-21 09:58 UTC by dzhengfy

Since libvirt detach device APIs(detach-device, detach-device-alias)
works asynchronously, that means every call returns before the detach
operation returns.This patch is to test multiple continuous detach to
make sure a detach call will not be interrupted by other calls.

Signed-off-by: Dan Zheng <dzheng@redhat.com>

2020-09-21 10:00 UTC, dzhengfy commented
Run on beaker host:
```
# avocado run --vt-type libvirt --vt-machine-type q35 virsh.detach_device..detach_mixed
JOB ID     : d7cc7c3cc1199010608935f6564f40b2146b7ca0
JOB LOG    : /root/avocado/job-results/job-2020-09-21T05.41-d7cc7c3/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virsh.detach_device.normal_test.vm_running_live.disk_test.file_type.detach_mixed: PASS (74.07 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 76.54 s

```

2020-09-22 02:51 UTC, chunfuwen commented on libvirt/tests/src/virsh_cmd/domain/virsh_detach_device.py
> +                time.sleep(1)
def detach_device(domainarg=None, filearg=None,
                  domain_opt=None, file_opt=None,
                  flagstr=None, wait_remove_event=False, event_timeout=7, **dargs):
detach_device extend one more parameter wait_remove_event, so it may help removal of time.sleep statement here

2020-09-22 02:56 UTC, chunfuwen commented on libvirt/tests/src/virsh_cmd/domain/virsh_detach_device.py
> +                virsh.detach_device_alias(vm_ref, device_alias,
do we need create separate threads to trigger those detach operations?

2020-09-22 10:22 UTC, sathnaga requested changes

2020-09-22 10:22 UTC, sathnaga commented on libvirt/tests/src/virsh_cmd/domain/virsh_detach_device.py
> +                virsh.detach_device_alias(vm_ref, device_alias,
yes, from the commit message it looks like parallel requests are needed, better to trigger via threading...
this seems not cover the case.

2020-10-12 12:43 UTC, dzhengfy commented
Run with libvirt-ci provisioned machine:
```
# avocado run --vt-type libvirt --vt-machine-type q35 virsh.detach_device..detach_mixed
JOB ID     : 879f053ea34e170ece74ec7d32bb2626d9b02580
JOB LOG    : /root/avocado/job-results/job-2020-10-12T20.37-879f053/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virsh.detach_device.normal_test.vm_running_live.disk_test.file_type.detach_mixed: PASS (47.00 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 49.99 s
```

2020-10-13 01:18 UTC, dzhengfy commented on libvirt/tests/src/virsh_cmd/domain/virsh_detach_device.py
> +                virsh.detach_device_alias(vm_ref, device_alias,
@chunfuwen @sathnaga yes, updated.

2020-10-13 01:20 UTC, chunfuwen approved these changes
LGTM

2020-10-14 04:39 UTC, sathnaga requested changes

2020-10-14 04:39 UTC, sathnaga commented on libvirt/tests/src/virsh_cmd/domain/virsh_detach_device.py
> +            dt_thread.start()
wait for thread to finish?, i guess dt_thread.join() is missing...
same for other thread

2020-10-14 04:39 UTC, sathnaga commented on libvirt/tests/src/virsh_cmd/domain/virsh_detach_device.py
> +            status = 0  # We do not care the virsh command return result
this does not look good, better make it return from the function and have the comment there, or controlled by ignore_status etc..

2020-10-21 04:21 UTC, dzhengfy commented on libvirt/tests/src/virsh_cmd/domain/virsh_detach_device.py
> +            dt_thread.start()
@sathnaga, originally I also think to use join(). But finally I do not think it is necessary because virsh detach operations are always asynchronous that means the functions will return immediately and the thread will end up. So I think no need to join() again.
So what do you think about it?

2020-10-21 04:32 UTC, dzhengfy commented on libvirt/tests/src/virsh_cmd/domain/virsh_detach_device.py
> +            status = 0  # We do not care the virsh command return result
@santwana , the scenario is to execute multiple detach at same time. And the first one will succeed and the followings will fail which are we expected.  Here I set status =0 to avoid of the following checking codes failed by the failure of second detach. And it is enough to check the device within the guest and guest xml.

Currently second detach failure already does not raise any exception with ignore_status=True. I am not sure what you mean by 'controlled by ignore_status'. 
And you want the function to return a result, then which detach result should I return?

2020-11-02 08:01 UTC, kylazhang commented on libvirt/tests/src/virsh_cmd/domain/virsh_detach_device.py
> +            status = 0  # We do not care the virsh command return result
The comments in the code here is acceptable for me to understand, so approve for not update here.

2020-11-10 08:59 UTC, dzhengfy commented on libvirt/tests/src/virsh_cmd/domain/virsh_detach_device.py
> +            dt_thread.start()
@kylazhang @sathnaga , updated.

2020-11-10 09:04 UTC, dzhengfy commented on libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device.cfg
> +            only normal_test.vm_running_live.disk_test.file_type.detach_mixed
@kylazhang This customer bug does not cover other configurations, so I fixed the case pattern like this.

2020-11-10 12:31 UTC, dzhengfy commented on libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device.cfg
> +            only normal_test.vm_running_live.disk_test.file_type.detach_mixed
@kylazhang updated.

2020-11-11 02:31 UTC, kylazhang approved these changes

2020-11-11 06:12 UTC, merged