virsh_migrate_setmaxdowntime: Fix conf issue in modular daemon mode
autotest/tp-libvirt pull request #3123
Opened 2020-10-22 08:54 UTC by fangge1212

The test fails with "can't find the log file" in modular daemon mode, we should
set log configurations according to the daemon mode and the log type, e.g.
in this case, "setmaxdowntime" log should be configured in virtqemud in
modular daemon mode, and in libvirtd in non-modular daemon mode.

Signed-off-by: Fangge Jin <fjin@redhat.com>

2020-10-22 11:23 UTC, fangge1212 commented
**Before fix:**
In modular daemon mode:
 (02/11) type_specific.io-github-autotest-libvirt.virsh.migrate_setmaxdowntime.error_test.invalid_uuid.without_postcopy:  ERROR: [Errno 2] No such file or directory: '/var/log/libvirt/libvirtd.log' (255.43 s)

**After fix:**
Tested in both modular daemon mode and non-modular daemon mode, both PASSED:
 (1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_setmaxdowntime.error_test.invalid_uuid.without_postcopy: PASS (254.16 s)

2020-10-23 08:34 UTC, Yingshun requested changes

2020-10-23 08:34 UTC, Yingshun commented on libvirt/tests/src/virsh_cmd/domain/virsh_migrate_setmaxdowntime.py
> +
If 'virtqemud' is a replacement of 'libvirtd' in your case, you can simply recall libvirt.customize_libvirt_config().

2020-10-23 08:43 UTC, fangge1212 commented on libvirt/tests/src/virsh_cmd/domain/virsh_migrate_setmaxdowntime.py
> +
I don't want to hard code it in py file, in case we need to add new test case with different conf_type.

2020-10-23 09:51 UTC, Yingshun commented on libvirt/tests/src/virsh_cmd/domain/virsh_migrate_setmaxdowntime.py
> +
No, you don't need to hardcode, the default value of config_type is 'libivrtd' and it will become 'virtqemud' when modular daemon is enabled.

2020-10-23 09:54 UTC, fangge1212 commented on libvirt/tests/src/virsh_cmd/domain/virsh_migrate_setmaxdowntime.py
> +
I don't want to hard code the conf_type of modular daemon mode to "virtqemud"

2020-10-28 00:42 UTC, Yingshun commented on libvirt/tests/src/virsh_cmd/domain/virsh_migrate_setmaxdowntime.py
> +
Could you please go through the code below? I think you didn't understand what I said.
https://github.com/avocado-framework/avocado-vt/blob/e41354352909a2a8bca9ee36b412ed3af7dfb436/virttest/utils_test/libvirt.py#L3577-L3606

2020-10-28 00:53 UTC, fangge1212 commented on libvirt/tests/src/virsh_cmd/domain/virsh_migrate_setmaxdowntime.py
> +
I know  what you mean, in avocado-vt, conf type for daemon is hardcoded to virtqemud when libvirt is modular daemon, but this is not what I expect. Because conf type for daemon may not be virtqemud, it can also be virtproxyd or others. I think it will be more straitforward and clear for it to be configured in *.cfg. 
We can meet if there is still gap in our understanding.

2020-12-01 13:41 UTC, fangge1212 commented
Retest case virsh.migrate_setmaxdowntime.error_test.invalid_uuid.without_postcopy, PASSED

2020-12-02 01:39 UTC, fangge1212 commented
@Yingshun @dzhengfy 
I have updated this pr, please review again

2020-12-07 01:45 UTC, Yingshun approved these changes

2020-12-22 10:26 UTC, kylazhang approved these changes

2020-12-22 10:26 UTC, merged