Add testcases for embedded qemu driver:
autotest/tp-libvirt pull request #3202
Opened 2020-12-14 03:11 UTC by yafu-1

1.Test cmd options;
2.Test starting qemu process;
3.Test second driver supported;

Signed-off-by: Yan Fu <yafu@redhat.com>

2020-12-14 09:59 UTC, smitterl requested changes
@yafu-1 Please, add test runs.
Regarding the commit message: could you please describe what you changed and why? Is this a new feature?

2020-12-14 09:59 UTC, smitterl commented on libvirt/tests/src/embedded_qemu/embedded_qemu.py
> +    Check socket files.
@yafu-1 Could you add more details to what is being tested? From this description I find it hard to understand what the script is supposed to be doing.

2020-12-15 10:05 UTC, chunfuwen commented on libvirt/tests/cfg/embedded_qemu/embedded_qemu.cfg
> +                    embedd_arg = '-d'
I wonder whether we can combine embedd_arg = '-d' and embedded_arg = '-h' into one case, otherwise we waste too much to just do case setup and clean up

2020-12-15 10:07 UTC, chunfuwen commented on libvirt/tests/src/embedded_qemu/embedded_qemu.py
> +    def create_secret(img_path):
there is currently existed method in :virttest/utils_test/libvirt.py

2020-12-30 07:06 UTC, yafu-1 commented on libvirt/tests/src/embedded_qemu/embedded_qemu.py
> +    Check socket files.
Added. Would you help to review again please? Thanks.

2020-12-30 07:06 UTC, yafu-1 commented on libvirt/tests/cfg/embedded_qemu/embedded_qemu.cfg
> +                    embedd_arg = '-d'
The test points are different. And also having different manual testcases for the options.

2020-12-30 07:07 UTC, yafu-1 commented on libvirt/tests/src/embedded_qemu/embedded_qemu.py
> +    def create_secret(img_path):
Updated. Would you help to review again please? Thanks.

2020-12-30 07:21 UTC, yafu-1 commented
@chunfuwen @Yingshun ,
This pr depends on:
https://github.com/avocado-framework/avocado-vt/pull/2860
So would you help to review that pr please？ Thanks.

2021-01-08 02:38 UTC, yafu-1 commented
@smitterl @chunfuwen 
I have updated the pr according to your suggestions. Would you help to review it again please? Thanks.

2021-01-12 04:04 UTC, chunfuwen approved these changes
LGTM

2021-01-13 06:05 UTC, Yingshun commented
Are these cases supported in all versions? I'm wondering if you need to check version before testing?

2021-01-13 06:06 UTC, Yingshun commented
BTW, could you please upload test results?

2021-01-13 06:32 UTC, Yingshun commented on libvirt/tests/cfg/embedded_qemu/embedded_qemu.cfg
> +        - secondary_driver_support:
Would you please explain what this testing is? I'm not quit sure about the purpose of this case...

2021-01-13 06:32 UTC, Yingshun commented on libvirt/tests/src/embedded_qemu/embedded_qemu.py
> +            test.fail("process did not exit successfully")
Do these 2 lines need to be moved to L145?

2021-01-13 06:40 UTC, yafu-1 commented on libvirt/tests/cfg/embedded_qemu/embedded_qemu.cfg
> +        - secondary_driver_support:
secondary_driver_support is based on the functional test point instead onf the cmd line point. For now, embedded qemu just supports secret sub-driver, later will support more.

2021-01-13 08:39 UTC, yafu-1 commented on libvirt/tests/src/embedded_qemu/embedded_qemu.py
> +            test.fail("process did not exit successfully")
Actually line 144 and 145 could be removed. Because terminating guest will be tested by all the cases. I will modified the scripts. Thanks.

2021-01-13 10:50 UTC, smitterl approved these changes
LGTM

2021-01-14 01:02 UTC, yafu-1 commented
> Are these cases supported in all versions? I'm wondering if you need to check version before testing?

The version is checked in the avocado-vt class.

2021-01-14 02:23 UTC, Yingshun approved these changes

2021-01-14 02:26 UTC, merged