Add some cases to check migration over unix socket
autotest/tp-libvirt pull request #3256
Opened 2021-01-19 08:54 UTC by Yingshun

This PR adds below cases:
1) Migrate vm over unix socket
2) Migrate vm with copy storage over unix socket - one disk
3) Migrate vm with copy storage over unix socket - multiple disks
4) Abort migration over unix socket and migrate again
5) Abort migration with copy storage over unix socket, and migrate again
6) Migrate vm over unix socket - libvirt tunnelled(--tunnelled)

Signed-off-by: Yingshun Cui <yicui@redhat.com>

2021-01-19 09:15 UTC, Yingshun commented
**Test results:**
```
# avocado run --vt-type libvirt --vt-machine-type q35 virsh.migrate_over_unix --vt-connect-uri qemu:///system
JOB ID     : 28f3511ddd836dff8905931f8b078109f5d5e2ff
JOB LOG    : /root/avocado/job-results/job-2021-01-19T03.47-28f3511/job.log
 (1/9) type_specific.io-github-autotest-libvirt.virsh.migrate_over_unix.positive_testing.basic.p2p_migration.with_postcopy: PASS (147.92 s)
 (2/9) type_specific.io-github-autotest-libvirt.virsh.migrate_over_unix.positive_testing.basic.p2p_migration.without_postcopy: PASS (151.88 s)
 (3/9) type_specific.io-github-autotest-libvirt.virsh.migrate_over_unix.positive_testing.basic.live_migration.without_postcopy: PASS (150.15 s)
 (4/9) type_specific.io-github-autotest-libvirt.virsh.migrate_over_unix.positive_testing.tunnelled.p2p_migration.without_postcopy: PASS (146.45 s)
 (5/9) type_specific.io-github-autotest-libvirt.virsh.migrate_over_unix.positive_testing.storage_migration.single_disk.p2p_migration.without_postcopy: PASS (89.38 s)
 (6/9) type_specific.io-github-autotest-libvirt.virsh.migrate_over_unix.positive_testing.storage_migration.single_disk.live_migration.without_postcopy: PASS (88.91 s)
 (7/9) type_specific.io-github-autotest-libvirt.virsh.migrate_over_unix.positive_testing.storage_migration.multi_disks.p2p_migration.without_postcopy: PASS (101.70 s)
 (8/9) type_specific.io-github-autotest-libvirt.virsh.migrate_over_unix.negative_test.domjobabort.normal_migration.p2p_migration.without_postcopy: PASS (164.91 s)
 (9/9) type_specific.io-github-autotest-libvirt.virsh.migrate_over_unix.negative_test.domjobabort.storage_migration.p2p_migration.without_postcopy: PASS (203.18 s)
RESULTS    : PASS 9 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 1247.14 s

```

2021-01-20 03:00 UTC, chunfuwen commented on libvirt/tests/cfg/migration/migrate_over_unix.cfg
> +        - live_migration:
https://libvirt.org/migration.html
not sure whether we can align  case variables with this  link?

2021-01-20 05:07 UTC, chunfuwen commented on libvirt/tests/cfg/migration/migrate_over_unix.cfg
> +    virsh_migrate_desturi = "qemu+unix:///system?socket=${desturi_socket_path}"
suggest align with name in the end of https://libvirt.org/migration.html#scenarionativepeer2peer
this allow more visible and understandable to others
***************************************************************
virsh migrate --domain web1 [--p2p] --copy-storage-all
  --desturi 'qemu+unix:///system?socket=/tmp/migdir/test-sock-driver'
  --migrateuri 'unix:///tmp/migdir/test-sock-qemu'
  --disks-uri unix:///tmp/migdir/test-sock-nbd

2021-01-20 05:18 UTC, chunfuwen commented on libvirt/tests/cfg/migration/migrate_over_unix.cfg
> +                - basic:
as per explanaiton:https://libvirt.org/migration.html#scenarionativepeer2peer
-basic change to -Hypervisor-native makes more meaningful.
****************************************************
Network data transports ¶
There are two options for the data transport used during migration, either the hypervisor's own native transport, or tunnelled over a libvirtd connection.

2021-01-21 02:07 UTC, chunfuwen commented
@smitterl  , would you mind joining in VM migration related case review ?

2021-01-21 02:46 UTC, Yingshun commented on libvirt/tests/cfg/migration/migrate_over_unix.cfg
> +        - live_migration:
Thanks for your comments!
The command 'virsh migrate' has an option '--direct' which means direct migration, so I prefer 'live_migration'.

2021-01-21 02:47 UTC, Yingshun commented on libvirt/tests/cfg/migration/migrate_over_unix.cfg
> +        - live_migration:
Thanks for your comments!
The command 'virsh migrate' has an option '--direct' which means direct migration, so I prefer 'live_migration'.

2021-01-22 00:59 UTC, chunfuwen commented
@fangge1212 , we may need align with some migration terminology at the beginning point of feature cases design
Here is a good reference :https://libvirt.org/migration.html .
Apparently , we can figure out sereval pairs of terminology from the scope, be careful not to mess them up :
1)Migration protocol :  
-- Hypervisor-native
-- libvirt-tunnel
2)Communication control paths/flow
--direct
--p2p
3) Memory and storage migration
-- live-migration (memory only)
-- block-migration(storage and memory only)

2021-01-22 01:16 UTC, Yingshun commented
> @fangge1212 , we may need align with some migration terminology at the beginning point of feature cases design
> Here is a good reference :https://libvirt.org/migration.html .
> Apparently , we can figure out sereval pairs of terminology from the same scope, be careful not to mess them up :
> 1)Migration protocol :
> -- Hypervisor-native
> -- libvirt-tunnel
> 2)Communication control paths/flow
> --direct
> --p2p
> 3) Memory and storage migration
> -- live-migration (memory only)
> -- block-migration(storage and memory only)
@chunfuwen your questions are about test plan, I think it would be great if you email to her directly.
There may be some conversation to discuss them or her may miss github information...

2021-01-22 01:41 UTC, fangge1212 commented
> @fangge1212 , we may need align with some migration terminology at the beginning point of feature cases design
> Here is a good reference :https://libvirt.org/migration.html .
> Apparently , we can figure out sereval pairs of terminology from the same scope, be careful not to mess them up :
> 1)Migration protocol :
> -- Hypervisor-native
This corresponds to "without virsh option --tunnel"

> -- libvirt-tunnel
This corresponds to "with virsh option --tunnel"

> 2)Communication control paths/flow
> --direct
"virsh option --direct" corresponds to "unmanaged direct", which is not supported by qemu-kvm

> --p2p
"virsh option --p2p" corresponds to "managed peer to peer", but we can just call it p2p migration

without either --direct or --p2p:
This corresponds to "managed direct", we don't have to point this out as it is default behaviour

Note:
managed means migration control flow is managed by libvirt. 
unmanaged means migration control flow is managed by hypervisor itself.

> 3) Memory and storage migration
> -- live-migration (memory only)
For "migration with memory only", we call it "live migration";
If --p2p is used, we call it "p2p live migration"
> -- block-migration(storage and memory only)
For "migration with both storage and memory", we call it "live migration with copy storage"

4) live/offline/non-live migration
live migration:
"live migration" corresponds to "virsh option --live", normally we will use --live when do migration, as apps/services in guest will be affected with live migration(just a short downtime).

non-live migration:
"non-live migration" corresponds to "without virsh option --live", guest will be paused when non-live migration starts and resumed when non-live migration completes, so apps/services in guest will be affected. This is not common usage, we just test it in one single test case. In most cases, we test live migration.

offline migration:
"offline migration" corresponds to "virsh option --offline", it means only guest defination(vm xml) is migrated to dest host(it is equivalent to "define a same vm on dest host").

2021-01-22 04:24 UTC, Yingshun commented on libvirt/tests/cfg/migration/migrate_over_unix.cfg
> +    virsh_migrate_desturi = "qemu+unix:///system?socket=${desturi_socket_path}"
I've added some comments for these variants, hoping to help you to understand them.

2021-02-01 10:40 UTC, smitterl requested changes

2021-02-01 10:40 UTC, smitterl commented on libvirt/tests/src/migration/migrate_over_unix.py
> +    def update_disk(vm, params):
e.g. `update_disk` updates a value that's declared further down the code after it's definition while nothing in the functions signature indicates that that value is being updated

https://github.com/autotest/tp-libvirt/blob/6784261ed94b958da1171459dbda82b7245fd3a0/libvirt/tests/src/migration/migrate_over_unix.py#L209

assumes list declared in 

https://github.com/autotest/tp-libvirt/blob/6784261ed94b958da1171459dbda82b7245fd3a0/libvirt/tests/src/migration/migrate_over_unix.py#L142

is already filled with values from

https://github.com/autotest/tp-libvirt/blob/6784261ed94b958da1171459dbda82b7245fd3a0/libvirt/tests/src/migration/migrate_over_unix.py#L92

after the function has been called in

https://github.com/autotest/tp-libvirt/blob/6784261ed94b958da1171459dbda82b7245fd3a0/libvirt/tests/src/migration/migrate_over_unix.py#L196

the signature being

https://github.com/autotest/tp-libvirt/blob/6784261ed94b958da1171459dbda82b7245fd3a0/libvirt/tests/src/migration/migrate_over_unix.py#L39

2021-02-01 10:40 UTC, smitterl commented on libvirt/tests/src/migration/migrate_over_unix.py
> +            logging.debug("Sleeping 10 seconds before rerun migration")
I'm not native but IMO it should be "[...] before rerunning the migration"

2021-02-01 10:40 UTC, smitterl commented on libvirt/tests/src/migration/migrate_over_unix.py
> +            if params.get("migrate_again_status_error") == "no":
Better create variable to hold value, same as you did with `migrate_again`.
https://github.com/autotest/tp-libvirt/blob/6784261ed94b958da1171459dbda82b7245fd3a0/libvirt/tests/src/migration/migrate_over_unix.py#L133

2021-02-01 10:40 UTC, smitterl commented on libvirt/tests/src/migration/migrate_over_unix.py
> +    migrate_again = "yes" == params.get("migrate_again")
`migrate_again` is not guaranteed to have a value, it might be None (the `cfg` file doesn't declare it globally). Better set a default value like you did in the other occasions. Check also `server_ip`, `remote_ip` etc.

2021-02-01 10:40 UTC, smitterl commented on libvirt/tests/src/migration/migrate_over_unix.py
> +                if vm.serial_console is not None:
Duplicate code, can be removed, `cleanup_serial_console` already checks this:
https://github.com/avocado-framework/avocado-vt/blob/7fabec524f2d50a37ef3c3a86bf60692730d8c3f/virttest/libvirt_vm.py#L1861

Question: Why do you have to recreate the serial console?

2021-02-01 10:40 UTC, smitterl commented on libvirt/tests/src/migration/migrate_over_unix.py
> +        logging.info("Recovery VM XML configration")
Is logging this message necessary? Also, if so, you'd better say "Recover VM XML configuration" (use the verb and typo).

2021-02-01 10:40 UTC, smitterl commented on libvirt/tests/src/migration/migrate_over_unix.py
> +        # Clean VM on destination and source
Is this comment necessary?

2021-02-01 10:40 UTC, smitterl commented on libvirt/tests/src/migration/migrate_over_unix.py
> +        logging.info("Recover test environment")
Is logging this message necessary?

2021-02-01 10:40 UTC, smitterl commented on libvirt/tests/src/migration/migrate_over_unix.py
> +                target_dev = 'vd' + chr(idx + 96)
Using magic number here. Might be worth creating function and moving to avocado-vt

2021-02-01 10:40 UTC, smitterl commented on libvirt/tests/src/migration/migrate_over_unix.py
> +                if result.exit_status:
Maybe not necessary here but there's a function for checking results:
https://github.com/avocado-framework/avocado-vt/blob/7fabec524f2d50a37ef3c3a86bf60692730d8c3f/virttest/utils_test/libvirt.py#L1217

2021-02-01 10:40 UTC, smitterl commented on libvirt/tests/src/migration/migrate_over_unix.py
> +                    raise test.fail("Attach device %s failed." % target_dev)
For setup issues like this the recommendation, IIUC, is to use `test.error`

https://github.com/avocado-framework/avocado/blob/9b372adeec6dceaba276ca4729f2e5a2fcccaa4c/avocado/core/exceptions.py#L90

2021-02-01 10:40 UTC, smitterl commented on libvirt/tests/src/migration/migrate_over_unix.py
> +                disk_cmd = ("qemu-img create -f %s %s 500M" %
You might want to consider creating an analog to `libvirt.create_local_disk` that you used above - e.g. `libvirt.create_remote_disk`. This would improve readability and helps avoid duplication.

2021-02-02 09:08 UTC, Yingshun commented on libvirt/tests/src/migration/migrate_over_unix.py
> +                    raise test.fail("Attach device %s failed." % target_dev)
Updated.

2021-02-02 09:22 UTC, Yingshun commented on libvirt/tests/src/migration/migrate_over_unix.py
> +                disk_cmd = ("qemu-img create -f %s %s 500M" %
As I know, only storage migration cases need to create disks on remote host. and we have some functions to execute command lines on a remote host, such as utils_misc.cmd_status_output(), remote.run_remote_cmd() and session.cmd/cmd_status_output() and so on. So I just generate a command line and send it to utils_misc.cmd_status_output(). We may run different commands on a remote host and if they're not quite common, I'd rather call the above functions than define each one individually. Can you please tell me what you think?

2021-02-02 09:25 UTC, Yingshun commented on libvirt/tests/src/migration/migrate_over_unix.py
> +                if result.exit_status:
Yes, thanks for sharing.

2021-02-02 09:26 UTC, Yingshun commented on libvirt/tests/src/migration/migrate_over_unix.py
> +        logging.info("Recovery VM XML configration")
Removed.

2021-02-02 09:28 UTC, Yingshun commented on libvirt/tests/src/migration/migrate_over_unix.py
> +        logging.info("Recover test environment")
I often check this message when debugging migration jobs so let's keep it.

2021-02-02 09:34 UTC, Yingshun commented on libvirt/tests/src/migration/migrate_over_unix.py
> +                if vm.serial_console is not None:
Yes, correct, it's unnecessary.

2021-02-02 09:56 UTC, Yingshun commented on libvirt/tests/src/migration/migrate_over_unix.py
> +                test.fail("Failed to start VM: %s" % err)
Ok, removed.

2021-02-02 09:59 UTC, Yingshun commented on libvirt/tests/src/migration/migrate_over_unix.py
> +    migrate_again = "yes" == params.get("migrate_again")
migrate_again in local will be False if params.get("migrate_again") is None, anyway, default value added.

2021-02-02 10:00 UTC, Yingshun commented on libvirt/tests/src/migration/migrate_over_unix.py
> +            logging.debug("Sleeping 10 seconds before rerun migration")
Updated.

2021-02-02 10:01 UTC, Yingshun commented on libvirt/tests/src/migration/migrate_over_unix.py
> +            if params.get("migrate_again_status_error") == "no":
Updated.

2021-02-02 10:03 UTC, Yingshun commented on libvirt/tests/src/migration/migrate_over_unix.py
> +        # Clean VM on destination and source
I think it's no harm to have it... how do you think?

2021-02-02 10:21 UTC, Yingshun commented on libvirt/tests/src/migration/migrate_over_unix.py
> +                target_dev = 'vd' + chr(idx + 96)
How about changing it to `target_dev = 'vd' + chr(idx + ord('a') - 1)`?

2021-02-02 10:26 UTC, Yingshun commented on libvirt/tests/src/migration/migrate_over_unix.py
> +    func_name = params.get("action_during_mig")
The variant func_name's used in almost all of the scripts under src/migration, so let's keep it. Is it ok?

2021-02-02 10:44 UTC, Yingshun commented on libvirt/tests/src/migration/migrate_over_unix.py
> +    def update_disk(vm, params):
Thanks for sharing your option! I understand what you mean but in other hand, it's convenient to implement the operations. And we have both of them in our existing code. 
Can I say it's a matter of coding style? It looks like we don't have a limitation about it.
There are pluses and minuses to all the solutions, I'm ok with both of them. But if you think it blocks this PR, we'd better to  have a discussion about this problem with whole team. How do you think?

2021-02-02 10:45 UTC, Yingshun commented
@smitterl I've updated the code, please help review again. Thanks!

2021-02-02 12:05 UTC, smitterl commented on libvirt/tests/src/migration/migrate_over_unix.py
> +    def update_disk(vm, params):
@chunfuwen What do you think? I think in context of improving code quality we should insist on having non-nested functions.

@Yingshun You have to admit that the signature e.g. of update_disk is wrong - it uses a local variable 'vm_did_list' which is not shown in the signature. I think for consistency if we accept nested run functions at least the signature should either be empty and variables just consumed because they are available to scope, or the signature has to be correct, listing all parameters or accepting a dictionary holding all parameters.

2021-02-02 12:10 UTC, smitterl commented on libvirt/tests/src/migration/migrate_over_unix.py
> +    func_name = params.get("action_during_mig")
@chunfuwen What do you think?

2021-02-02 12:11 UTC, smitterl commented on libvirt/tests/src/migration/migrate_over_unix.py
> +                target_dev = 'vd' + chr(idx + 96)
@Yingshun I believe it's still cryptical and should really live in a reusable function but I wouldn't block approval on it.

2021-02-02 13:05 UTC, smitterl commented on libvirt/tests/src/migration/migrate_over_unix.py
> +                disk_cmd = ("qemu-img create -f %s %s 500M" %
@Yingshun I'm sorry, I'm not sure I understand. Not having the _cmds but rather an equivalent create_remote_disk or more general create_disk would make your code more readable besides being useful. Something that reads like
```python
libvirt.create_disk("file", disk_format=disk_format,
                             path=disk_path, size="500M", session=session)
```
This way you can also use it in a local guest or even in a remote guest. For safe refactoring, `libvirt.create_local_disk` could either delegate to `create_disk` - the code would have to run cmd_status_output on session and process.run or process.getstatusoutput for local access without session - or `create_disk` delegates simply to `create_local_disk` if session==None.

2021-02-02 17:36 UTC, smitterl commented on libvirt/tests/src/migration/migrate_over_unix.py
> +    func_name = params.get("action_during_mig")
@Yingshun To be honest, my preference would be to rather change it in all other occurrences, too. When I read the code further down I don't remember what func_name is being used for. I mean you wouldn't want to name "disks_uri_port" "int_as_string_param_1" either (I admit I'm exaggerating a bit :P). I mean, we already have this in our review guide IIUC:
```
variable name issue:
     name should be meaningful
```

2021-02-02 17:52 UTC, smitterl commented on libvirt/tests/src/migration/migrate_over_unix.py
> +        # Clean VM on destination and source
OK. I'm trying to understand why you put in comments here and not in the long code of the `run` function. Using them here could be considered a code smell pointing to "Wrong Level of Abstraction" [1]. If it's not necessary, I wouldn't put it.

[1] https://blog.usejournal.com/stop-writing-code-comments-28fef5272752

2021-02-02 17:58 UTC, smitterl reviewed
Thank you @Yingshun I mainly have some more questions. Everything is relative and I agree that having a discussion helps to understand what expectations there are to the test code.

2021-02-03 01:10 UTC, Yingshun commented on libvirt/tests/src/migration/migrate_over_unix.py
> +    def update_disk(vm, params):
@dzhengfy @kylazhang @chloerh @kamilvarga Would you mind sharing your ideas?

2021-02-04 02:20 UTC, Yingshun commented on libvirt/tests/src/migration/migrate_over_unix.py
> +                disk_cmd = ("qemu-img create -f %s %s 500M" %
Done, please check https://github.com/avocado-framework/avocado-vt/pull/2915.

2021-02-05 02:26 UTC, dzhengfy commented on libvirt/tests/src/migration/migrate_over_unix.py
> +    func_name = params.get("action_during_mig")
In my memory, 'func_name' is used in migrate_options_shared.py as a common name to accommodate  different function names in different cases. But in this py file, 'func_name' is used to always read the parameter of 'action_during_mig', so I think maybe we do not need to use a common name any more here. But I think that is only better to change, not a must.

2021-02-05 02:26 UTC, dzhengfy commented on libvirt/tests/src/migration/migrate_over_unix.py
> +            migration_test.check_result(mig_result, params)
Line 231 and 230 are same with Line 213 and 214. Because we usually do the 2 steps after do_migration, I am thinking if it is better to extend the do_migration() to check the result by default?

2021-02-05 02:44 UTC, Yingshun commented on libvirt/tests/src/migration/migrate_over_unix.py
> +                    raise test.error("Attach device %s failed." % target_dev)
Updated.

2021-02-05 02:45 UTC, Yingshun commented on libvirt/tests/src/migration/migrate_over_unix.py
> +                local_image_list.append(disk_path)
Yes, you're right, updated.

2021-02-05 02:45 UTC, Yingshun commented on libvirt/tests/src/migration/migrate_over_unix.py
> +        Update interfaces for guest
Done.

2021-02-05 02:49 UTC, Yingshun commented on libvirt/tests/src/migration/migrate_over_unix.py
> +    func_name = params.get("action_during_mig")
Below are the files we used 'func_name', if we need another name, I prefer to do it separately.
migrate_bandwidth.py
migrate_gluster.py
migrate_mem.py
migrate_network.py
migrate_options_shared.py
migrate_over_unix.py
migrate_storage.py
sriov_migrate.py

2021-02-05 03:47 UTC, Yingshun commented on libvirt/tests/src/migration/migrate_over_unix.py
> +            migration_test.check_result(mig_result, params)
That's a good idea @dzhengfy. Thank you for your suggestion! 
It almost affects all of the migration scripts so I add a item in TODO list. I will do it later, is it ok?

2021-02-07 02:05 UTC, dzhengfy commented on libvirt/tests/src/migration/migrate_over_unix.py
> +            migration_test.check_result(mig_result, params)
OK

2021-02-07 02:47 UTC, dzhengfy commented on libvirt/tests/src/migration/migrate_over_unix.py
> +    vm_did_list = []
Above assignments seems useless because in Line 193, they will be reassigned by update_disk() function which already declares local variables with same names. Maybe you can set them to None or pass them to update_disk(),  I think.

2021-02-07 03:24 UTC, Yingshun commented on libvirt/tests/src/migration/migrate_over_unix.py
> +    vm_did_list = []
If an exception is raised before calling update_disk() there will be a problem. And  local_image_list and remote_image_list will be checked in 'finally' block as below:

https://github.com/autotest/tp-libvirt/blob/6784261ed94b958da1171459dbda82b7245fd3a0/libvirt/tests/src/migration/migrate_over_unix.py#L270-L273

2021-02-20 04:09 UTC, dzhengfy approved these changes

2021-02-20 04:09 UTC, dzhengfy commented on libvirt/tests/src/migration/migrate_over_unix.py
> +    vm_did_list = []
It is ok regarding your words. But I do not think it is good practice. However, it is not a must to change.

2021-02-23 00:33 UTC, chunfuwen commented on libvirt/tests/src/migration/migrate_over_unix.py
> +    def update_disk(vm, params):
+1 with kamil and smitterl 's comment

2021-02-23 00:58 UTC, Yingshun commented on libvirt/tests/src/migration/migrate_over_unix.py
> +    def update_disk(vm, params):
@smitterl @kamilvarga   redefined such lists of images in this function. Would you please help review again?

2021-02-23 01:03 UTC, Yingshun commented on libvirt/tests/src/migration/migrate_over_unix.py
> +    def update_disk(vm, params):
@chunfuwen  Would you mind adding some details to the review comments so that we can understand you clearly.

2021-02-24 01:47 UTC, dzhengfy commented on libvirt/tests/src/migration/migrate_over_unix.py
> +    def update_disk(vm, params):
@smitterl @kamilvarga @chunfuwen , thanks for your comments. Your opinion is valuable and a good point. In the past, we do not have a strict rule for this, so you may see both writings exist in many python files. I will create an issue to specifically discuss about this and hope we can reach an agreement finally, then we will follow the conclusion in the following pull requests. 
Regarding this PR, it implemented many critical and high test cases and feature owner is waiting for its run in jenkins, so we decide to merge it now to speed up our tests. Thank you.

2021-02-24 02:02 UTC, chunfuwen approved these changes
LGTM

2021-02-24 02:36 UTC, merged

2021-02-24 02:36 UTC, dzhengfy commented
https://github.com/avocado-framework/avocado-vt/issues/2926