remote_access: new tests added for uri aliases/default
autotest/tp-libvirt pull request #3524
Opened 2021-05-31 07:37 UTC by kamilvarga

The new test cases added to test uri default and uri aliases.

Signed-off-by: Kamil Varga <kvarga@redhat.com>

- Description of the cases: custom uri aliases and uri default
- case ID: RHEL7-18304
- Test results:
<pre>WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
WARNING:root:No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
<font color="#2A7BDE">JOB ID     : 095e334a76344f8b7d924ab0d8242c27ca83beba</font>
<font color="#2A7BDE">JOB LOG    : /root/avocado/job-results/job-2021-05-31T03.22-095e334/job.log</font>
 (1/1) type_specific.io-github-autotest-libvirt.virsh.remote_with_ssh.positive_testing.test_uri_alias_list: <font color="#33DA7A">PASS</font> (35.45 s)
<font color="#2A7BDE">RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0</font>
<font color="#2A7BDE">JOB TIME   : 37.08 s</font>
WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
WARNING:root:No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
<font color="#2A7BDE">JOB ID     : 87dfb16735153cf83e3f20df723bab6becab4a35</font>
<font color="#2A7BDE">JOB LOG    : /root/avocado/job-results/job-2021-05-31T03.23-87dfb16/job.log</font>
 (1/1) type_specific.io-github-autotest-libvirt.virsh.remote_with_ssh.positive_testing.test_uri_one_alias: <font color="#33DA7A">PASS</font> (35.52 s)
<font color="#2A7BDE">RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0</font>
<font color="#2A7BDE">JOB TIME   : 36.31 s</font>
WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
WARNING:root:No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
<font color="#2A7BDE">JOB ID     : 5fadcd6d41b38417bef5212112be91425c71eac7</font>
<font color="#2A7BDE">JOB LOG    : /root/avocado/job-results/job-2021-05-31T03.24-5fadcd6/job.log</font>
 (1/1) type_specific.io-github-autotest-libvirt.virsh.remote_with_ssh.positive_testing.check_uri: <font color="#33DA7A">PASS</font> (35.43 s)
<font color="#2A7BDE">RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0</font>
<font color="#2A7BDE">JOB TIME   : 36.22 s</font>
WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
WARNING:root:No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
<font color="#2A7BDE">JOB ID     : 627207f318dcfa51acd75b87b400bab7708c99ae</font>
<font color="#2A7BDE">JOB LOG    : /root/avocado/job-results/job-2021-05-31T03.24-627207f/job.log</font>
 (1/1) type_specific.io-github-autotest-libvirt.virsh.remote_with_ssh.positive_testing.test_uri_default_local: <font color="#33DA7A">PASS</font> (34.77 s)
<font color="#2A7BDE">RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0</font>
<font color="#2A7BDE">JOB TIME   : 35.68 s</font>
WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
WARNING:root:No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
<font color="#2A7BDE">JOB ID     : 5a6b0444c4973f1404eccbc5fe7f557f1a89d762</font>
<font color="#2A7BDE">JOB LOG    : /root/avocado/job-results/job-2021-05-31T03.25-5a6b044/job.log</font>
 (1/1) type_specific.io-github-autotest-libvirt.virsh.remote_with_ssh.positive_testing.test_uri_default_remote: <font color="#33DA7A">PASS</font> (35.87 s)
<font color="#2A7BDE">RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0</font>
<font color="#2A7BDE">JOB TIME   : 36.67 s</font>
WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
WARNING:root:No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
<font color="#2A7BDE">JOB ID     : 95f761ae95910ec718d1baee3e7305611878d122</font>
<font color="#2A7BDE">JOB LOG    : /root/avocado/job-results/job-2021-05-31T03.26-95f761a/job.log</font>
 (1/1) type_specific.io-github-autotest-libvirt.virsh.remote_with_ssh.negative_testing.test_uri_invalid_alias: <font color="#33DA7A">PASS</font> (34.86 s)
<font color="#2A7BDE">RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0</font>
<font color="#2A7BDE">JOB TIME   : 35.58 s</font>
WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
WARNING:root:No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
<font color="#2A7BDE">JOB ID     : a03ef0763697de41b32dfe6abea1c1ae5efe3aab</font>
<font color="#2A7BDE">JOB LOG    : /root/avocado/job-results/job-2021-05-31T03.26-a03ef07/job.log</font>
 (1/1) type_specific.io-github-autotest-libvirt.virsh.remote_with_ssh.negative_testing.test_uri_invalid_alias_string: <font color="#33DA7A">PASS</font> (34.87 s)
<font color="#2A7BDE">RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0</font>
<font color="#2A7BDE">JOB TIME   : 35.76 s</font>
</pre>

2021-05-31 07:38 UTC, kamilvarga commented
Depends on https://github.com/avocado-framework/avocado-vt/pull/3075.

2021-05-31 07:40 UTC, kamilvarga commented on libvirt/tests/src/remote_access/remote_access.py
> +                    % (output_local, output_remote))
These two lines of code are just a minor change of an error which is not captured by the JIRA tickets, as this subtest is skipped by the libvirt-ci.

2021-06-01 02:17 UTC, chunfuwen commented on libvirt/tests/src/remote_access/remote_access.py
> +                   ignore_status=True,
update ignore_status=True --> ignore_status=False to enable earlier assert ?

2021-06-01 02:19 UTC, chunfuwen approved these changes
only one minor comment, others looks good to me.
LGTM

2021-06-01 07:30 UTC, dzhengfy reviewed
Others LGTM

2021-06-01 07:30 UTC, dzhengfy commented on libvirt/tests/cfg/remote_access/remote_with_ssh.cfg
> +                - test_uri_default_remote:
The prefix 'test_' seems unnecessary. In my POV, it makes the case name longer as side effect.

2021-06-02 01:50 UTC, Yingshun commented on libvirt/tests/src/remote_access/remote_access.py
> +        for config in config_list:
There might be a problem if test fails before L454. So how about adding `'config_list' in locals()` or initializing 'config_list' before 'try'?

2021-06-02 08:14 UTC, kamilvarga commented on libvirt/tests/src/remote_access/remote_access.py
> +                   ignore_status=True,
Updated as suggested.

2021-06-02 08:14 UTC, kamilvarga commented on libvirt/tests/cfg/remote_access/remote_with_ssh.cfg
> +                - test_uri_default_remote:
Updated as suggested.

2021-06-02 08:14 UTC, kamilvarga commented on libvirt/tests/src/remote_access/remote_access.py
> +        for config in config_list:
Updated as suggested.

2021-06-07 02:19 UTC, Yingshun approved these changes
LGTM

2021-06-07 03:19 UTC, dzhengfy reviewed
As there are already 2 approvals, I use request to change to avoid of incorrect merging.

2021-06-07 03:20 UTC, dzhengfy requested changes
As there are already 2 approvals, I use request to change to avoid of incorrect merging.

2021-06-08 14:38 UTC, kamilvarga commented on libvirt/tests/src/remote_access/remote_access.py
> +    customize_libvirt_config({}, is_recover=True,
Added as suggested.

2021-06-08 14:39 UTC, kamilvarga commented on libvirt/tests/cfg/remote_access/remote_with_ssh.cfg
> +                - test_uri_invalid_alias_string:
Updated.

2021-06-15 09:30 UTC, dzhengfy approved these changes
LGTM

2021-06-15 09:30 UTC, merged