Fix scsi sgio issue on latest libvirt version by below steps
autotest/tp-libvirt pull request #3561
Opened 2021-06-17 07:16 UTC by chunfuwen

Load modprobe sg manually since kernel not load it automatically
Skip unpriv_sgio check since feature change

Signed-off-by: chunfuwen <chwen@redhat.com>

2021-06-17 07:40 UTC, lento-sun approved these changes
LGTM

2021-06-17 07:58 UTC, chunfuwen commented
cleaning libvirtd logs...
DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
PASS 1-type_specific.io-github-autotest-libvirt.libvirt_scsi_hostdev.positive_test.single_dev.hot_plug.passthrough_local_scsi.sgio_filtered.rawio_enable.not_shareable.readonly.managed_default

2021-06-22 06:16 UTC, qiankehan requested changes

2021-06-22 06:16 UTC, qiankehan commented on libvirt/tests/src/libvirt_scsi_hostdev.py
> +                    # After libvirt 7.4.0, unpriv_sgio feature change,e.g: /sys/dev/char/%s:%s/queue/unpriv_sgio not existed
I don't think the libvirt version checking should be added here.
Although the scsi sgio cases fails only in libvirt 7.4.0, it is not clear that if there is any changes in libvirt 7.4.0 causing these failures. Anyway, the script should make sure **sg** is loaded before scsi_hostdev cases (see https://bugzilla.redhat.com/show_bug.cgi?id=1962482), no matter what version of libvirt is.

2021-06-22 06:16 UTC, qiankehan commented on libvirt/tests/src/libvirt_scsi_hostdev.py
> +                    if not libvirt_version.version_compare(7, 4, 0):
The same as above. Remove the version checking.

2021-06-22 06:17 UTC, qiankehan commented
> Load modprobe sg manually since kernel not load it automatically
> Skip unpriv_sgio check since feature change
Remove **since feature change** because it is not clear if any code change in libvirt caused the scsi_hostdev regressions.
And add the doc bug link https://bugzilla.redhat.com/show_bug.cgi?id=1962482 for further reference.
> 
> Signed-off-by: chunfuwen [chwen@redhat.com](mailto:chwen@redhat.com)



> Load modprobe sg manually since kernel not load it automatically
> Skip unpriv_sgio check since feature change
> 
> Signed-off-by: chunfuwen [chwen@redhat.com](mailto:chwen@redhat.com)

2021-06-23 02:06 UTC, chunfuwen commented on libvirt/tests/src/libvirt_scsi_hostdev.py
> +                    # After libvirt 7.4.0, unpriv_sgio feature change,e.g: /sys/dev/char/%s:%s/queue/unpriv_sgio not existed
@qiankehan 
it is not related to sg module loading issue, this is part of features changes after confirming with yisun.
Module loading issue is handled by line 293

2021-06-23 02:06 UTC, chunfuwen commented on libvirt/tests/src/libvirt_scsi_hostdev.py
> +                    if not libvirt_version.version_compare(7, 4, 0):
@qiankehan 
it is not related to sg module loading issue, this is part of features changes after confirming with yisun.
Module loading issue is handled by line 293

2021-06-23 02:42 UTC, qiankehan commented on libvirt/tests/src/libvirt_scsi_hostdev.py
> +                    # After libvirt 7.4.0, unpriv_sgio feature change,e.g: /sys/dev/char/%s:%s/queue/unpriv_sgio not existed
OK..
However, I recommend to mention reference of the **feature change** for example the libvirt commit id in the commit msg.
In this commit your fix the issues of mod sg and unpriv_sgio. It is better to split it into 2 commits.

2021-06-24 07:42 UTC, chunfuwen commented on libvirt/tests/src/libvirt_scsi_hostdev.py
> +                    # After libvirt 7.4.0, unpriv_sgio feature change,e.g: /sys/dev/char/%s:%s/queue/unpriv_sgio not existed
@qiankehan 

updated git commit log with referred bug wrapping in

2021-06-24 07:43 UTC, chunfuwen commented
> > Load modprobe sg manually since kernel not load it automatically
> > Skip unpriv_sgio check since feature change
> 
> Remove **since feature change** because it is not clear if any code change in libvirt caused the scsi_hostdev regressions.
> And add the doc bug link https://bugzilla.redhat.com/show_bug.cgi?id=1962482 for further reference.
> 
> > Signed-off-by: chunfuwen [chwen@redhat.com](mailto:chwen@redhat.com)
> 
> > Load modprobe sg manually since kernel not load it automatically
> > Skip unpriv_sgio check since feature change
> > Signed-off-by: chunfuwen [chwen@redhat.com](mailto:chwen@redhat.com)

@qiankehan 

updated git commit log with referred bug wrapping in

2021-06-24 07:54 UTC, qiankehan commented
> Load modprobe sg manually since kernel not load it automatically
> Skip unpriv_sgio check since feature change, see ee bug link https://bugzilla.redhat.com/show_bug.cgi?id=1962482 for further reference

@chunfuwen 
Here the bug link makes the line too long and looks like badly formatted. I recommend to update as following:
```
Skip unpriv_sgio check since feature change, see ee bug link[1] for further reference

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1962482
```

And what's the meaning of `ee bug link`?

> 
> Signed-off-by: chunfuwen [chwen@redhat.com](mailto:chwen@redhat.com)

2021-06-24 08:43 UTC, qiankehan commented on libvirt/tests/src/libvirt_scsi_hostdev.py
> +                    # After libvirt 7.4.0, unpriv_sgio feature change,e.g: /sys/dev/char/%s:%s/queue/unpriv_sgio not existed
For the code comments:
```
After libvirt 7.4.0, unpriv_sgio feature change,e.g: /sys/dev/char/%s:%s/queue/unpriv_sgio not existed
```
I cannot image the version of libvirt can affect the content of sysfs. I guess `/sys/dev/char/%s:%s/queue/unpriv_sgio not existed` is caused by the changes from kernel.
@lento-sun  Could you please provide more details about the `unpriv_sgio feature change`

2021-06-24 08:52 UTC, qiankehan commented
@Yingshun @chunfuwen 
It turns out the **unpriv_sgio** is never merged to upstream kernel. It is a downstream only feature[1][2].
So it is only merged into these distributions: `rhel7, rhel8, centos7, centos8`. You can **unpriv_sgio** in  the changelog of  [3] to see it is only applied in RHEL8 downstream.
You can check the sysfs file `/sys/block/<device>/unpriv_sgio`[4] to see if the system contains **unpriv_sgio**. For the systems don't support **unpriv_sgio**, skip its cases

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1810661#c0
[2]: https://www.reddit.com/r/VFIO/comments/f7yiv7/fedora_31_unpriv_sgio_not_supported_by_this_kernel/
[3]: https://koji.mbox.centos.org/koji/buildinfo?buildID=15231
[4]: https://lwn.net/Articles/535075/

2021-06-24 09:40 UTC, chunfuwen commented
> @lento-sun @chunfuwen
> It turns out the **unpriv_sgio** is never merged to upstream kernel. It is a downstream only feature[1](https://bugzilla.redhat.com/show_bug.cgi?id=1810661#c0) [2](https://www.reddit.com/r/VFIO/comments/f7yiv7/fedora_31_unpriv_sgio_not_supported_by_this_kernel/).
> So it is only merged into these distributions: `rhel7, rhel8, centos7, centos8`. You can refer to **unpriv_sgio** in the changelog of [3](https://koji.mbox.centos.org/koji/buildinfo?buildID=15231) to see it is only applied in RHEL8 downstream.
> You can check the sysfs file `/sys/block/<device>/unpriv_sgio`[4](https://lwn.net/Articles/535075/) to see if the system contains **unpriv_sgio**. For the systems don't support **unpriv_sgio**, skip its cases

@qiankehan 
As discussed offline, the code change to check whether file exists or not, if not, just return directly

2021-06-24 09:41 UTC, chunfuwen commented
DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
PASS 1-type_specific.io-github-autotest-libvirt.libvirt_scsi_hostdev.positive_test.single_dev.hot_plug.passthrough_local_scsi.sgio_filtered.rawio_enable.not_shareable.readonly.managed_default

2021-06-25 04:04 UTC, lento-sun commented on libvirt/tests/src/libvirt_scsi_hostdev.py
> +                    # After libvirt 7.4.0, unpriv_sgio feature change,e.g: /sys/dev/char/%s:%s/queue/unpriv_sgio not existed
there is a bug to track this in kernel https://bugzilla.redhat.com/show_bug.cgi?id=1810667
It's still new.

2021-06-25 04:04 UTC, lento-sun commented on libvirt/tests/src/libvirt_scsi_hostdev.py
> +                    # After libvirt 7.4.0, unpriv_sgio feature change,e.g: /sys/dev/char/%s:%s/queue/unpriv_sgio not existed
there is a bug to track this in kernel https://bugzilla.redhat.com/show_bug.cgi?id=1810667
It's still new.

2021-06-28 02:06 UTC, chunfuwen commented on libvirt/tests/src/libvirt_scsi_hostdev.py
> +                    # After libvirt 7.4.0, unpriv_sgio feature change,e.g: /sys/dev/char/%s:%s/queue/unpriv_sgio not existed
@lento-sun 
@qiankehan 
Already wrap this information into git log message

2021-06-28 02:16 UTC, qiankehan approved these changes
Others look good to me

2021-06-28 02:16 UTC, qiankehan commented on libvirt/tests/src/libvirt_scsi_hostdev.py
> +            # unpriv_sgio feature change in centain kernel,e.g: /sys/dev/char/%s:%s/queue/unpriv_sgio may not exist
Post an warning or canceling message might be better than the comment.
```
test.cancel("unpriv_sgio is not supported in this kernel.")
```

2021-06-28 02:26 UTC, chunfuwen commented on libvirt/tests/src/libvirt_scsi_hostdev.py
> +            # unpriv_sgio feature change in centain kernel,e.g: /sys/dev/char/%s:%s/queue/unpriv_sgio may not exist
@qiankehan 
There are some complains from feature team about too many test.cancel in jobs.
So these cases will be filter out by CI skiplist instead

2021-06-29 03:59 UTC, kylazhang approved these changes

2021-06-29 03:59 UTC, merged