virsh_blockcopy: Fix selinux issue
autotest/tp-libvirt pull request #3670
Opened 2021-07-27 08:03 UTC by liuyd96

Based on the reproduce steps of
https://bugzilla.redhat.com/show_bug.cgi?id=924151

Set virt_use_nfs on to fix selinux issue
------
stderr: 'error: Failed to start domain \'avocado-vt-vm1\'\nerror: internal error: qemu unexpectedly closed the monitor: 2021-07-27T07:56:48.770625Z qemu-kvm: -blockdev {"driver":"file","filename":"/var/lib/avocado/data/avocado-vt/nfs-mount/nfs-img","node-name":"libvirt-1-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"}: Could not open \'/var/lib/avocado/data/avocado-vt/nfs-mount/nfs-img\': Permission denied\n'
------

Signed-off-by: Liu Yiding <liuyd.fnst@fujitsu.com>

Before
```
[root@hpe-moonshot-02-c25 ~]# avocado run --vt-type libvirt --vt-arch aarch64 --vt-machine-type arm64-mmio virsh.blockcopy.positive_test.non_acl.nfs_disk.dest_nfs.no_blockdev.shallow.pivot_option
JOB ID     : 7fb3714ec49d959973fc5ebd21ef52b0cd7b96f5
JOB LOG    : /root/avocado/job-results/job-2021-07-27T03.55-7fb3714/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virsh.blockcopy.positive_test.non_acl.nfs_disk.dest_nfs.no_blockdev.shallow.pivot_option: ERROR: VM 'avocado-vt-vm1' failed to start: error: Failed to start domain 'avocado-vt-vm1'\nerror: internal error: qemu unexpectedly closed the monitor: 2021-07-27T07:56:48.770625Z qemu-kvm: -blockdev {"driver":"file","filename":"/var/lib/avocado/data/avocado-vt/... (264.44 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 265.11 s
```
After
```
[root@hpe-moonshot-02-c25 ~]# avocado run --vt-type libvirt --vt-arch aarch64 --vt-machine-type arm64-mmio virsh.blockcopy.positive_test.non_acl.nfs_disk.dest_nfs.no_blockdev.shallow.pivot_option
JOB ID     : b016acfd5ce5ab302685415e64d6baf384ba0adf
JOB LOG    : /root/avocado/job-results/job-2021-07-27T04.01-b016acf/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virsh.blockcopy.positive_test.non_acl.nfs_disk.dest_nfs.no_blockdev.shallow.pivot_option: PASS (87.31 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 87.99 s
```

2021-07-27 08:09 UTC, liuyd96 commented
@chloerh Thanks.

2021-07-28 01:45 UTC, chunfuwen approved these changes
LGTM

2021-07-29 02:53 UTC, kylazhang commented on libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py
> +            test.error("Failed to set virt_use_nfs on")
You can try utils_misc.SELinuxBoolean to do these works with "setup" and "cleanup". The usage you can consult the domblkerror test but I think it is better to set "local_boolean_varible" and "local_boolean_value" in cfg file instead of in py.

2021-07-29 03:12 UTC, chloerh commented on libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py
> +            test.error("Failed to set virt_use_nfs on")
Agree with @kylazhang

2021-07-29 09:03 UTC, liuyd96 commented on libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py
> +            test.error("Failed to set virt_use_nfs on")
Ok, I got it. Thanks.

2021-07-29 09:15 UTC, liuyd96 commented
Before
```
[root@hpe-moonshot-02-c25 ~]# avocado run --vt-type libvirt --vt-arch aarch64 --vt-machine-type arm64-mmio virsh.blockcopy.positive_test.non_acl.nfs_disk.dest_nfs.no_blockdev.shallow.pivot_option
JOB ID     : fd69e3c8f5c447ec981655a8410a433cf9fc92a2
JOB LOG    : /root/avocado/job-results/job-2021-07-29T05.08-fd69e3c/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virsh.blockcopy.positive_test.non_acl.nfs_disk.dest_nfs.no_blockdev.shallow.pivot_option: ERROR: VM 'avocado-vt-vm1' failed to start: error: Failed to start domain 'avocado-vt-vm1'\nerror: internal error: process exited while connecting to monitor: 2021-07-29T09:09:23.152631Z qemu-kvm: -blockdev {"driver":"file","filename":"/var/lib/avocado/data/avoca... (219.68 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 220.30 s
```
After the fix
```
[root@hpe-moonshot-02-c25 ~]# avocado run --vt-type libvirt --vt-arch aarch64 --vt-machine-type arm64-mmio virsh.blockcopy.positive_test.non_acl.nfs_disk.dest_nfs.no_blockdev.shallow.pivot_option
JOB ID     : 7d98f1c82e35f02849daaeee4cb00791af800f77
JOB LOG    : /root/avocado/job-results/job-2021-07-29T04.58-7d98f1c/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virsh.blockcopy.positive_test.non_acl.nfs_disk.dest_nfs.no_blockdev.shallow.pivot_option: PASS (41.25 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 41.88 s

```

2021-07-29 10:05 UTC, kylazhang commented on libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py
> +        if selinux_bool:
should be selinux_local?

2021-07-29 10:06 UTC, chloerh approved these changes

2021-07-29 10:36 UTC, kylazhang requested changes
It should be update else it will report error when selinux_bool do not exist

2021-08-02 01:28 UTC, liuyd96 commented
> It should be fixed else it will report error when selinux_bool do not exist

Yes. I have re-push the codes. Very appreciate for your point.

2021-08-16 00:47 UTC, liuyd96 commented
@kylazhang gently ping

2021-08-19 10:50 UTC, kylazhang approved these changes

2021-08-19 10:50 UTC, merged