v2v: add checkpoint for glance deprecate on RHEL9
autotest/tp-libvirt pull request #3692
Opened 2021-08-04 09:58 UTC by vwu-vera

Check bz #1977539.

Signed-off-by: vwu-vera <vwu@redhat.com>

2021-08-04 09:58 UTC, vwu-vera commented
(1/1) type_specific.io-github-autotest-libvirt.v2v_options.positive_test.machine_readable.input_mode.none.output_mode.none: PASS (2.61 s)

2021-08-04 10:19 UTC, xiaodwan commented on v2v/tests/src/v2v_options.py
> +                            strippedLine = line.strip()
this style 'strippedLine'  does not conform to the code style of v2v in tp-libvirt.
It's better to use '_' to concatenate 'a variant name, such as 'stripped_line'.

2021-08-04 10:26 UTC, vwu-vera commented
@xiaodwan Modified the 'strippedLine' to  'stripped_line' as suggested. 
Please help to review the latest one. Thanks.

2021-08-04 14:24 UTC, xiaodwan requested changes

2021-08-06 08:30 UTC, vwu-vera commented
Modified the script according to the comment. And rerun passed:  (1/1) type_specific.io-github-autotest-libvirt.v2v_options.positive_test.machine_readable.input_mode.none.output_mode.none: PASS (3.28 s)

@xiaodwan Please help to review the latest commit. Thanks.

2021-08-06 08:38 UTC, xiaodwan approved these changes

2021-08-06 08:38 UTC, merged