virsh_blockcopy.py: remove libvirtd status check
autotest/tp-libvirt pull request #3867
Opened 2021-11-11 02:00 UTC by meinaLi

virsh_blockcopy.py: remove libvirtd status check to adapt to the split daemon mode

Fix error: Libvirtd service is dead
The libvirtd status check is standing alone and not dependent on other codes. It's only a check of libvirtd service. So remove it to adapt to the split daemon mode.

Signed-off-by: Meina Li <meili@redhat.com>

2021-11-11 02:30 UTC, meinaLi commented
One related test result:
```
# avocado run --vt-type libvirt --vt-machine-type q35 virsh.blockcopy.positive_test.non_acl.block_disk.disk_t.default.block_type.blockdev.shallow.pivot_option
JOB ID     : f2d9d9c79f88440df8f21120aaa9eef0bd29f58a
JOB LOG    : /root/avocado/job-results/job-2021-11-10T21.21-f2d9d9c/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virsh.blockcopy.positive_test.non_acl.block_disk.disk_t.default.block_type.blockdev.shallow.pivot_option: PASS (431.21 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 433.63 s
```

2021-11-11 02:33 UTC, meinaLi commented
@Yingshun For previous libvirtd error in blockcopy, I found it's only caused by libvirtd status check, which can be removed directly. And it also won't affect other test in RHEL8.5/8.6. Please help to review if this method works.

2021-11-12 01:18 UTC, chunfuwen approved these changes
LGTM

2021-11-12 03:23 UTC, cliping approved these changes
LGTM

2021-11-15 07:41 UTC, Yingshun requested changes
Can you please double check which daemon you should check in this case and update 
libvirtd_utl = utils_libvirtd.Libvirtd() in L446 to libvirtd_utl = utils_libvirtd.Libvirtd('daemon_name') to only focus on the proper daemon(virtqemud I guess). Thanks!

2021-11-15 07:41 UTC, Yingshun commented on libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py
> -        if not libvirtd_utl.is_running():
I found that the time between the daemons restarting and daemons status checking exceeded 120 seconds. That may be the root cause. some of the 'unused' daemons were stopped after 120s.

2021-11-19 05:45 UTC, Yingshun approved these changes

2021-11-19 05:46 UTC, merged