Fix event not found in avocado-vt log
autotest/tp-libvirt pull request #4012
Opened 2022-01-26 07:09 UTC by chunfuwen

Having avocado-vt log only makes sense under monolithic libvirtd mode

Signed-off-by: chunfuwen <chwen@redhat.com>

2022-01-26 07:10 UTC, chunfuwen commented
cleaning libvirtd logs...
DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
PASS 1-type_specific.io-github-autotest-libvirt.virtual_disks.multidisks.hotplug.single_disk_test.virtio_disk_hot_unplug_event_watch

2022-02-16 07:33 UTC, dzhengfy commented on libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
> +                if virtio_disk_hot_unplug_event_watch and not utils_split_daemons.is_modular_daemon():
I have concern with the fix strategy for this one. Checking libvirt daemon log for the event should be working. The key is we need to use the correct log file in modular daemon environment

2022-02-21 01:26 UTC, chunfuwen commented on libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
> +                if virtio_disk_hot_unplug_event_watch and not utils_split_daemons.is_modular_daemon():
@dzhengfy 
For log checking, I don't think we need enable all log checking cases into modular daemon mode one by one since logging is generic framework. Actually I assume there  are specialized  cases developed by yafu to cover logging when we enable modular daemon.
@yafu-1 
What's your opinion ?

2022-02-21 05:50 UTC, yafu-1 commented on libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
> +                if virtio_disk_hot_unplug_event_watch and not utils_split_daemons.is_modular_daemon():
I agree with @dzhengfy 's option. And it needs to check specialized log, which needs to deal cases by cases.

2022-03-23 02:56 UTC, dzhengfy commented on libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
> +                if virtio_disk_hot_unplug_event_watch and not utils_split_daemons.is_modular_daemon():
@qiankehan As this is related virtual-disk feature, could you help confirm if this log checking is needed on modular daemon environment for this scenario? Thanks

2022-03-24 01:59 UTC, qiankehan commented on libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
> +                if virtio_disk_hot_unplug_event_watch and not utils_split_daemons.is_modular_daemon():
No need here. For single libvirtd daemon, find the DEVICE_DELETED qmp event in the log of libvirtd; For split daemons, find the event in log of virtqemud. That is the only difference.



> @qiankehan As this is related virtual-disk feature, could you help confirm if this log checking is needed on modular daemon environment for this scenario? Thanks

2022-03-24 09:41 UTC, qiankehan requested changes

2022-03-24 09:41 UTC, qiankehan commented on libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
>                      result = utils_misc.wait_for(lambda: check_info_in_libvird_log_file('"event": "DEVICE_DELETED"'), timeout=20)
After the PR, the code would be 
```python
if virtio_disk_hot_unplug_event_watch and not utils_split_daemons.is_modular_daemon():
    result = utils_misc.wait_for(lambda: check_info_in_libvird_log_file('"event": "DEVICE_DELETED"'), timeout=20)
```
That means the checking of "DEVICE_DELETED" would be **skipped** for split daemons.  However, it is necessary for split daemons, too.
The pseudocode should be like:
```python
if virtio_disk_hot_unplug_event_watch:
    if Libvirtd:
        Update libvirtd.conf
        Restart libvirtd
    if SplitDaemons:
        Update virtqemud.conf
        Restart virtqemud
```

2022-04-11 04:09 UTC, chunfuwen commented
close it since it may not be used anymore

2022-04-11 04:09 UTC, closed without merging