libvirtd: Add case to test restart libvirtd service
autotest/tp-libvirt pull request #4114
Opened 2022-03-20 14:58 UTC by cliping

RHEL7-103707 - [libvirtd] Restart libvirtd service bug 1450095

Signed-off-by: lcheng <lcheng@redhat.com>

2022-03-20 15:05 UTC, cliping commented
Test result:
#avocado run --vt-type libvirt --vt-machine-type q35 libvirtd.libvirtd.restart_libvirtd --vt-connect-uri qemu:///system
JOB ID     : 69701812864eac7f4053fac238c1e112e0d12b13
JOB LOG    : /root/avocado/job-results/job-2022-03-17T11.14-6970181/job.log
 (1/1) type_specific.io-github-autotest-libvirt.libvirtd.libvirtd.restart_libvirtd: PASS (60.34 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 61.66 s


Test result in modular daemons mode:
#avocado run --vt-type libvirt --vt-machine-type q35 libvirtd.libvirtd.restart_libvirtd --vt-connect-uri qemu:///system
JOB ID     : 0f3840becae339d5e96df043f6e352c07966350e
JOB LOG    : /root/avocado/job-results/job-2022-03-17T11.03-0f3840b/job.log
 (1/1) type_specific.io-github-autotest-libvirt.libvirtd.libvirtd.restart_libvirtd: PASS (5.51 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 6.20 s

2022-03-20 15:13 UTC, cliping commented
@yafu-1 , please help to review, thanks.

2022-03-21 00:19 UTC, chunfuwen commented on libvirt/tests/src/libvirtd/libvirtd.py
> +    if libvirt_version.version_compare(5, 6, 0):
I assume we don't need determin libvirt version, but just judge whether utils_split_daemons.is_modular_daemon() return True or False

2022-03-21 02:53 UTC, yafu-1 requested changes

2022-03-21 02:53 UTC, yafu-1 commented on libvirt/tests/src/libvirtd/libvirtd.py
> +    log_file = "/var/log/messages"
tp-libvirt redirect daemon log to file and not exists in syslog anymore, so need to change the log file or log setting here.

2022-03-21 02:54 UTC, yafu-1 commented on libvirt/tests/src/libvirtd/libvirtd.py
> +        test.fail("Found error message in libvirtd status messages.")
It's better to output the error msg here.

2022-03-21 02:54 UTC, yafu-1 commented on libvirt/tests/src/libvirtd/libvirtd.py
> +        test.fail("Found error message in /var/log/messages.")
The same as above.

2022-03-30 02:31 UTC, cliping commented on libvirt/tests/src/libvirtd/libvirtd.py
> +    if libvirt_version.version_compare(5, 6, 0):
Updated, thanks.

2022-03-30 02:32 UTC, cliping commented on libvirt/tests/src/libvirtd/libvirtd.py
> +    log_file = "/var/log/messages"
Updated to daemon log, thanks.

2022-03-30 02:32 UTC, cliping commented on libvirt/tests/src/libvirtd/libvirtd.py
> +        test.fail("Found error message in libvirtd status messages.")
Updated.

2022-05-06 05:36 UTC, chunfuwen approved these changes
LGTM

2022-05-09 04:37 UTC, cliping commented
Test result:

#avocado run --vt-type libvirt libvirtd.libvirtd.check_journal --vt-machine-type q35 --vt-connect-uri qemu:///system
JOB ID     : ed65cba2f41c6517f3baaf605d67aebb04b16461
JOB LOG    : /var/lib/avocado/job-results/job-2022-05-09T00.29-ed65cba/job.log
 (1/1) type_specific.io-github-autotest-libvirt.libvirtd.libvirtd.check_journal: STARTED
 (1/1) type_specific.io-github-autotest-libvirt.libvirtd.libvirtd.check_journal: PASS (41.17 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/lib/avocado/job-results/job-2022-05-09T00.29-ed65cba/results.html
JOB TIME   : 42.76 s

2022-05-09 08:27 UTC, yafu-1 approved these changes
LGTM

2022-05-12 10:44 UTC, merged