Add test cases to cover various operations on disk with slice attribu…
autotest/tp-libvirt pull request #4138
Opened 2022-04-01 01:37 UTC by chunfuwen

…tes,

including hotplug, snapshot, blockcommit, blockcopy, blkdeviotune

Signed-off-by: chunfuwen <chwen@redhat.com>

2022-04-01 01:39 UTC, chunfuwen commented
PASS 01-_specific.io-github-autotest-libvirt.virtual_disks.slice_operation.disk_qcow2.slice_blkdeviotune
PASS 02-_specific.io-github-autotest-libvirt.virtual_disks.slice_operation.disk_qcow2.slice_disk_blockcopy
PASS 03-_specific.io-github-autotest-libvirt.virtual_disks.slice_operation.disk_qcow2.slice_disk_blockcommit
PASS 04-_specific.io-github-autotest-libvirt.virtual_disks.slice_operation.disk_qcow2.slice_cdrom_update
PASS 06-_specific.io-github-autotest-libvirt.virtual_disks.slice_operation.disk_raw.slice_blkdeviotune
PASS 07-_specific.io-github-autotest-libvirt.virtual_disks.slice_operation.disk_raw.slice_disk_blockcopy
PASS 08-_specific.io-github-autotest-libvirt.virtual_disks.slice_operation.disk_raw.slice_disk_blockcommit
PASS 09-_specific.io-github-autotest-libvirt.virtual_disks.slice_operation.disk_raw.slice_cdrom_update
PASS 10-_specific.io-github-autotest-libvirt.virtual_disks.slice_operation.disk_raw.slice_hot_operate

2022-04-25 02:26 UTC, dzhengfy commented on libvirt/tests/src/virtual_disks/virtual_disks_slice_operation.py
> +    """
:return:

2022-04-25 02:26 UTC, dzhengfy commented on libvirt/tests/src/virtual_disks/virtual_disks_slice_operation.py
> +    """
:return:

2022-04-25 02:26 UTC, dzhengfy commented on libvirt/tests/src/virtual_disks/virtual_disks_slice_operation.py
> +    """
:return:

2022-04-25 02:26 UTC, dzhengfy commented on libvirt/tests/src/virtual_disks/virtual_disks_slice_operation.py
> +        _, output = session.cmd_status_output(
`output = session.cmd_output()` is enough for your need.

2022-04-25 02:26 UTC, dzhengfy commented on libvirt/tests/src/virtual_disks/virtual_disks_slice_operation.py
> +            test.fail("The %s value is not equal from domstats and domblkinfo" % key)
Please add the actual and expected values for better debugging.

2022-04-25 02:26 UTC, dzhengfy commented on libvirt/tests/src/virtual_disks/virtual_disks_slice_operation.py
> +        session.close()
finally:
        session.close()

2022-04-25 02:26 UTC, dzhengfy commented on libvirt/tests/src/virtual_disks/virtual_disks_slice_operation.py
> +        status = session.cmd_status(mnt_cmd)
Suggest  `cmd_status_output() `instead of `cmd_status() `as we could print out the output message for better debugging.

2022-04-25 02:26 UTC, dzhengfy commented on libvirt/tests/src/virtual_disks/virtual_disks_slice_operation.py
> +        vmxml_backup.sync("")
`sync()`?

2022-05-05 08:21 UTC, chunfuwen commented on libvirt/tests/src/virtual_disks/virtual_disks_slice_operation.py
> +from virttest import libvirt_xml
updated

2022-05-05 08:21 UTC, chunfuwen commented on libvirt/tests/src/virtual_disks/virtual_disks_slice_operation.py
> +CLEANUP_FILES = []
updated to cleanup_files

2022-05-05 08:22 UTC, chunfuwen commented on libvirt/tests/src/virtual_disks/virtual_disks_slice_operation.py
> +        process.run(cmd, shell=True, ignore_status=True)
Thank for reminding , libvirt.create_local_disk()  doesn't support creating less than 1G image, so here use primitive method qemu-img to create 100M size disk

2022-05-05 08:27 UTC, chunfuwen commented on libvirt/tests/src/virtual_disks/virtual_disks_slice_operation.py
> +
The purpose of those 3 lines are to create customized source by below steps:
The customized source comes firstly from current available in VM, and then add slices attribute into disk source
After that, we reinitialized disk source

2022-05-05 08:28 UTC, chunfuwen commented on libvirt/tests/src/virtual_disks/virtual_disks_slice_operation.py
> +LOG = logging.getLogger('avocado.' + __name__)
As I showed you some practices in other open  source projects, quite number of them use upper case

2022-05-05 08:39 UTC, chunfuwen commented on libvirt/tests/src/virtual_disks/virtual_disks_slice_operation.py
> +    """
updated

2022-05-05 08:42 UTC, chunfuwen commented on libvirt/tests/src/virtual_disks/virtual_disks_slice_operation.py
> +    """
updated

2022-05-05 08:43 UTC, chunfuwen commented on libvirt/tests/src/virtual_disks/virtual_disks_slice_operation.py
> +    """
updated

2022-05-05 08:44 UTC, chunfuwen commented on libvirt/tests/src/virtual_disks/virtual_disks_slice_operation.py
> +        _, output = session.cmd_status_output(
I think there is no difference between them since previous unnecessary is hidden by '_'

2022-05-05 08:48 UTC, chunfuwen commented on libvirt/tests/src/virtual_disks/virtual_disks_slice_operation.py
> +            test.fail("The %s value is not equal from domstats and domblkinfo" % key)
updated

2022-05-05 08:48 UTC, chunfuwen commented on libvirt/tests/src/virtual_disks/virtual_disks_slice_operation.py
> +        session.close()
updated

2022-05-05 08:50 UTC, chunfuwen commented on libvirt/tests/src/virtual_disks/virtual_disks_slice_operation.py
> +        status = session.cmd_status(mnt_cmd)
Thank for your suggesting, so here it is just one very simple command execution: mount /dev/sr0 /mnt && ls /mnt

2022-05-05 08:50 UTC, chunfuwen commented on libvirt/tests/src/virtual_disks/virtual_disks_slice_operation.py
> +        vmxml_backup.sync("")
updated with removal of "" parameter

2022-05-06 04:52 UTC, dzhengfy commented on libvirt/tests/src/virtual_disks/virtual_disks_slice_operation.py
> +        process.run(cmd, shell=True, ignore_status=True)
OK. It seems it is an enhancement we can do. If you would like, you could help on it. For this PR, it is not a blocker.

2022-05-06 04:55 UTC, dzhengfy approved these changes
LGTM

2022-05-06 05:53 UTC, Yingshun commented
@dzhengfy There are 8 test scenarios for both qcow2 and raw type disk in manual cases but I just find 10 in total, and I'm not familiar with this feature, so could you please ask feature owner to review this PR?

2022-05-10 01:50 UTC, chunfuwen commented
@qiankehan 

Please help review this PR.

2022-05-10 02:15 UTC, qiankehan requested changes
And the commit summary is too long... I'd like to update the commit msg as:
```
New cases for operations on disk with slice element

Operations: hotplug, snapshot, blockcommit, blockcopy, blkdeviotune
```

2022-05-10 02:15 UTC, qiankehan commented on libvirt/tests/cfg/virtual_disks/virtual_disks_slice_operation.cfg
> +            additional_driver_attrs = "{'copy_on_read':'off','cache':'none','discard':'ignore','detect_zeroes':'on','io':'native'}"
Use "'copy_on_read':'on'". 'copy_on_read':'on' will make more complex blockdev layers. That will help find bugs.

2022-05-10 02:15 UTC, qiankehan commented on libvirt/tests/cfg/virtual_disks/virtual_disks_slice_operation.cfg
> +            disk_slice__override_attrs = "{'slice_type': 'storage', 'slice_offset': '0', 'slice_size': '105185280'}"
I am not so sure if the hardcode **'slice_size': '105185280'** is suitable here.
The slice_size comes from the size of full image:
```sh
qemu-img create /tmp/image -f qcow2 SIZE -o preallocation=full
slice_size=$(du -b /tmp/image)
```
If the image size or image format is changed someday, the hardcode will cause troubles.

2022-05-10 02:23 UTC, chunfuwen commented on libvirt/tests/cfg/virtual_disks/virtual_disks_slice_operation.cfg
> +            disk_slice__override_attrs = "{'slice_type': 'storage', 'slice_offset': '0', 'slice_size': '105185280'}"
@qiankehan 
All these are based on pre-condition that 100MiB image was created whether it is qcow2 or raw image format. As the polarion case description, the slice_size is different in qcow2 and raw image, where qcow2 is 105185280, but raw is 104857600.
If the image size or image format is changed someday,  it will help us find the error since there may be something wrong with the change.

2022-05-10 02:25 UTC, chunfuwen commented on libvirt/tests/cfg/virtual_disks/virtual_disks_slice_operation.cfg
> +            additional_driver_attrs = "{'copy_on_read':'off','cache':'none','discard':'ignore','detect_zeroes':'on','io':'native'}"
That need updated in polarion case firstly

2022-05-10 02:27 UTC, chunfuwen commented on libvirt/tests/cfg/virtual_disks/virtual_disks_slice_operation.cfg
> +            additional_driver_attrs = "{'copy_on_read':'off','cache':'none','discard':'ignore','detect_zeroes':'on','io':'native'}"
That need be updated firstly in polarion actually, but I can updated since it is minor update

2022-05-10 02:32 UTC, qiankehan commented on libvirt/tests/cfg/virtual_disks/virtual_disks_slice_operation.cfg
> +            disk_slice__override_attrs = "{'slice_type': 'storage', 'slice_offset': '0', 'slice_size': '105185280'}"
OK. It's better to add a code comment to say how to calculate the right slice_size

2022-05-10 02:36 UTC, qiankehan commented on libvirt/tests/cfg/virtual_disks/virtual_disks_slice_operation.cfg
> +            additional_driver_attrs = "{'copy_on_read':'off','cache':'none','discard':'ignore','detect_zeroes':'on','io':'native'}"
Manual case is updated.

2022-05-10 03:15 UTC, chunfuwen commented on libvirt/tests/cfg/virtual_disks/virtual_disks_slice_operation.cfg
> +            disk_slice__override_attrs = "{'slice_type': 'storage', 'slice_offset': '0', 'slice_size': '105185280'}"
add one relevant comment in line 48

2022-05-10 03:16 UTC, chunfuwen commented on libvirt/tests/cfg/virtual_disks/virtual_disks_slice_operation.cfg
> +            additional_driver_attrs = "{'copy_on_read':'off','cache':'none','discard':'ignore','detect_zeroes':'on','io':'native'}"
update slice_disk_blockcopy and slice_disk_blockcommit with copy_on_read=on

2022-05-10 03:23 UTC, qiankehan approved these changes

2022-05-10 03:32 UTC, merged

2022-05-10 03:33 UTC, chunfuwen commented
Let's merge it since dengy and hanhan approved it already