Add Complexity handling practices as one tip
autotest/tp-libvirt pull request #4177
Opened 2022-04-27 03:18 UTC by chunfuwen

This tip is borrowed from Complexity part in Google engineering practice[1].

[1]https://google.github.io/eng-practices/review/reviewer/looking-for.html

Signed-off-by: chunfuwen <chwen@redhat.com>

2022-06-27 02:41 UTC, chunfuwen commented
@smitterl 
@dzhengfy 
Please help take a look. 
This practice is follow-up action on our PR review meeting

2022-07-05 06:18 UTC, dzhengfy approved these changes
LGTM

2022-07-08 13:16 UTC, smitterl requested changes
@chunfuwen Thank you for this addition! I think there should be some change in format and optionally in style. Please, check my comment. Thank you!

2022-07-11 00:07 UTC, chunfuwen commented on tp-libvirt_review_comment_summary.rst
> +  - Encourage contributors to solve the problem they know needs to be solved now, not the problem that the contributor speculates might need to be solved in the future. The future problem should be s
@smitterl , updated, please double check this

2022-07-13 00:49 UTC, chunfuwen commented
@smitterl 
Updated almost like https://github.com/chunfuwen/tp-libvirt/pull/1, but remain qualifying words, which is already there in original statement ]https://google.github.io/eng-practices/review/reviewer/looking-for.html.

2022-07-14 08:50 UTC, smitterl approved these changes

2022-07-18 00:12 UTC, merged

2022-07-18 00:12 UTC, chunfuwen commented
Let's merge it since all reviewers approve this