Fix qemu command line output change issue due to json format as default
autotest/tp-libvirt pull request #4279
Opened 2022-06-15 08:02 UTC by chunfuwen

Those practices are borrowed from previous practice in virtual_disks_multidisks

Signed-off-by: chunfuwen <chwen@redhat.com>

2022-06-15 08:03 UTC, chunfuwen commented
Run on latest version after fixing:

Command 'virsh list' finished with 0 after 0.032168161s
cleaning libvirtd logs...
DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
PASS 1-type_specific.io-github-autotest-libvirt.virtual_disks.at_dt_iscsi_disk.positive_test.cold_plug.block_disk.with_packed.packed_on

2022-06-15 08:03 UTC, chunfuwen commented
Run on previous old version:

[stdout] 
cleaning libvirtd logs...
DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
PASS 1-type_specific.io-github-autotest-libvirt.virtual_disks.at_dt_iscsi_disk.positive_test.cold_plug.block_disk.with_packed.packed_on

2022-06-15 08:04 UTC, chunfuwen commented
Error log 
Error Details
TestFail: Expected 'packed=off' was NOT found in qemu command line&#10;

2022-06-17 09:31 UTC, smitterl requested changes
Thank you for this @chunfuwen Sorry for nitpicking, but could you please make sure you're commit and PR message state clearly what this change is about?

2022-06-17 09:31 UTC, smitterl commented on libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py
> +                test.fail("Check disk driver option failed with %s" % expect_qemu_line)
I'd suggest you use the `libvirt.check_qemu_cmd_line` to reuse existing code and reduce code complexity. I tried it out and the following works:
```python
    expect_qemu_line = ".*packed.*%s|%s" % (driver_packed, 'true' if driver_packed == 'on' else 'false')
    libvirt.check_qemu_cmd_line(expect_qemu_line)
```

```bash
JOB ID     : 3c0ab250bed78b8b772cede504b14763db0f4944
JOB LOG    : /var/lib/avocado/job-results/job-2022-06-17T05.27-3c0ab25/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virtual_disks.at_dt_iscsi_disk.positive_test.cold_plug.block_disk.with_packed.packed_on: STARTED
 (1/1) type_specific.io-github-autotest-libvirt.virtual_disks.at_dt_iscsi_disk.positive_test.cold_plug.block_disk.with_packed.packed_on: PASS (33.62 s)
```

2022-06-20 03:07 UTC, chunfuwen commented on libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py
> +                test.fail("Check disk driver option failed with %s" % expect_qemu_line)
@smitterl , thank you for suggestion, now change it to the solution you suggested.

2022-06-20 03:08 UTC, chunfuwen commented
New test result:

cleaning libvirtd logs...
DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
PASS 1-type_specific.io-github-autotest-libvirt.virtual_disks.at_dt_iscsi_disk.positive_test.cold_plug.block_disk.with_packed.packed_on

2022-06-20 06:29 UTC, qiankehan requested changes
BTW, the device JSON format is enabled when QEMU>=6.2 and Libvirt>=v7.9.0
```
commit c9b13e0557
Author: Peter Krempa <pkrempa@redhat.com>
Date:   Fri Oct 15 11:42:19 2021 +0200

    qemu: Use JSON directly for '-device'
    
    Starting with QEMU-6.2 started accepting a JSON object as argument for
    '-device' which will also become the only syntax considered stable by
    qemu in the future.
    
    Since libvirt was recently converted to generate the properties via JSON
    to begin wit we can start using it on the commandline as well, by simply
    enabling the QEMU_CAPS_DEVICE_JSON capability, which we do by probing
    for the 'json-cli' feature flag of 'device_add'.
    
    Normally a change which changes a commandline output should be happening
    only after the impacted real-caps test files are forked in the version
    preceding the change, but in this case it's not necessary as the logic
    for generating the device properties stays identical and we just change
    the output format (avoid conversion). Additionally we still have a lot
    of tests validating the conversion to the old commandline options.
    
    Signed-off-by: Peter Krempa <pkrempa@redhat.com>
    Reviewed-by: Ján Tomko <jtomko@redhat.com>
```
So it can be fixed with version checking as well

2022-06-20 06:29 UTC, qiankehan commented on libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py
> +            expect_qemu_line = ".*packed.*%s|%s" % (driver_packed, 'true' if driver_packed == 'on' else 'false')
The regex valid range is too wide to allow the invalid cases like such a QEMU command line(assuming packed is true in XML):
```
"packed":false,..., -device ..., "ats":true
```

2022-06-20 12:06 UTC, chunfuwen commented on libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py
> +            expect_qemu_line = ".*packed.*%s|%s" % (driver_packed, 'true' if driver_packed == 'on' else 'false')
@qiankehan 
Team previously agreed either we use wild card to handle qemu command line checking, or we can disregard qemu command line checking at all. Do you think there is high possibility to have above-mentioned string appear in qemu commnd line?

2022-06-21 02:05 UTC, chunfuwen commented on libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py
> +            expect_qemu_line = ".*packed.*%s|%s" % (driver_packed, 'true' if driver_packed == 'on' else 'false')
@qiankehan , narrow down matching pattern  by adding delimiter =|: between key and value

2022-06-21 02:10 UTC, chunfuwen commented
new uploaded test result after changing

Command 'virsh list' finished with 0 after 0.032302579s
cleaning libvirtd logs...
DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
PASS 1-type_specific.io-github-autotest-libvirt.virtual_disks.at_dt_iscsi_disk.positive_test.cold_plug.block_disk.with_packed.packed_on

2022-06-21 08:56 UTC, smitterl approved these changes
@chunfuwen Thank you for this. Please check @qiankehan 's comment (s. link below). Rest LGTM so approving this conditionally on that fix :)

https://github.com/autotest/tp-libvirt/pull/4279/files#r902111959

2022-06-21 09:05 UTC, smitterl commented on libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py
> +            expect_qemu_line = ".*packed=|:%s|%s" % (driver_packed, 'true' if driver_packed == 'on' else 'false')
Personally, I'm in favor of removing all qemu-commandline checks as it just leads to brittleness; the question for me is if the functionality actually is available in the vm.

In this specific case, could we maybe use character sets, @chunfuwen ?

```
>>> s1 = '"packed": true'
>>> s2 = '"packed" :true'
>>> r1 = re.compile('"packed"[\s:]+true')
>>> r1.match(s1)
<_sre.SRE_Match object; span=(0, 14), match='"packed": true'>
>>> r1.match(s2)
<_sre.SRE_Match object; span=(0, 14), match='"packed" :true'>
```

2022-06-22 02:54 UTC, chunfuwen commented on libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py
> +            expect_qemu_line = ".*packed=|:%s|%s" % (driver_packed, 'true' if driver_packed == 'on' else 'false')
@smitterl , I verified your solution works in this situation, thank again for you helping out.

2022-06-22 02:57 UTC, chunfuwen commented
new test result available:

Command 'virsh list' finished with 0 after 0.032578793s
cleaning libvirtd logs...
DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
PASS 1-type_specific.io-github-autotest-libvirt.virtual_disks.at_dt_iscsi_disk.positive_test.cold_plug.block_disk.with_packed.packed_on

2022-06-22 02:57 UTC, chunfuwen commented
@qiankehan 
please double check the recent change.

2022-06-22 03:01 UTC, qiankehan commented
The regex is OK now. However, as I said before, I'd like to leave the checking for libvirt unit tests.

2022-06-23 01:08 UTC, dzhengfy reviewed
@chunfuwen @qiankehan , from the following codes, I see there are codes to find the attached disk using find_attach_disk(). So as we discussed before, we should remove this qemu command line checking to avoid fixing this matching issue. What do you think of?

2022-06-23 01:34 UTC, chunfuwen commented
@dzhengfy 
@qiankehan 

I think we had agreed for newly introduced test case, we don't need address qemu line output.
For existed test case, we can maintain them if efforts are low.
So please don't mess up those information.

2022-06-23 02:02 UTC, qiankehan commented
> @dzhengfy @qiankehan
> 
> I think we had agreed for newly introduced test case, we don't need address qemu line output. For existed test case, we can maintain them if efforts are low. So please don't mess up those information.

No. The efforts here are not so low.  Like this patch, you have to design the regex for matching and be ready to adapt to the changes in the future. 
What we will gain from these efforts? A duplicated checking function.
Remove that checking and leave it for unit tests. That will take us less effects.

2022-06-23 03:11 UTC, chunfuwen commented
@qiankehan 
@dzhengfy 
For this specific test case, let's move off the qemu command line checking since it is already covered in libvirt upstream CI test, https://gitlab.com/libvirt/libvirt/-/blob/master/tests/qemuxml2argvdata/virtio-options-disk-packed.x86_64-latest.args

2022-06-24 02:47 UTC, dzhengfy approved these changes
LGTM

2022-06-24 08:58 UTC, qiankehan commented
Confusing commit summary. Better to summarize what this PR does: `Remove QEMU cmdline check from ...`
@chunfuwen

2022-06-24 09:53 UTC, rhdyuan commented on libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py
> -            libvirt.check_qemu_cmd_line(expect_qemu_line)
Test comment for reviewer list.

2022-06-27 02:52 UTC, chunfuwen commented
Let's merge it since all reviewers have approved

2022-06-27 02:52 UTC, merged