Newly add new cases to cover bochs video model
autotest/tp-libvirt pull request #4368
Opened 2022-07-21 08:43 UTC by chunfuwen

default_heads and vram default_size attributes are covered

Signed-off-by: chunfuwen <chwen@redhat.com>

2022-07-21 08:44 UTC, chunfuwen commented
DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
PASS 1-type_specific.io-github-autotest-libvirt.virtual_devices.video_devices.positive_test.primary_video.bochs.no_secondary_video.mem_test.vram.bochs_default_size


DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
PASS 1-type_specific.io-github-autotest-libvirt.virtual_devices.video_devices.positive_test.primary_video.bochs.no_secondary_video.heads_test.default_heads

2022-08-08 08:46 UTC, chunfuwen commented
@iccaszhulili 
it aims to automate xx-179809 case

2022-08-22 05:27 UTC, iccaszhulili requested changes

2022-08-22 05:27 UTC, iccaszhulili commented on libvirt/tests/cfg/virtual_device/video_devices.cfg
> +                            only no_secondary_video..default_heads no_secondary_video..vram..bochs_default_size
video type 'bochs' doesn't support multiple 'heads', if we keep the defaults_heads pattern here, it seems we can change the heads for 'bochs' video. Can we change the pattern to no_secondary_video..model_test.default

2022-08-26 06:42 UTC, chunfuwen commented on libvirt/tests/cfg/virtual_device/video_devices.cfg
> +                            only no_secondary_video..default_heads no_secondary_video..vram..bochs_default_size
@iccaszhulili ,
If change pattern to no_secoddary_video..model_test.default, currently test code will throw error as below.
```
Reproduced traceback from: /root/82ltscode/avocado/avocado/core/test.py:767
Traceback (most recent call last):
  File "/root/82ltscode/avocado-vt/avocado_vt/test.py", line 200, in runTest
    raise self.__status  # pylint: disable=E0702
  File "/root/82ltscode/avocado-vt/avocado_vt/test.py", line 146, in setUp
    self._runTest()
  File "/root/82ltscode/avocado-vt/avocado_vt/test.py", line 263, in _runTest
    run_func(self, params, env)
  File "/root/82ltscode/tp-libvirt/libvirt/tests/src/virtual_device/video_devices.py", line 268, in run
    check_model_test_cmd_line(model_type, is_primary)
  File "/root/82ltscode/tp-libvirt/libvirt/tests/src/virtual_device/video_devices.py", line 123, in check_model_test_cmd_line
    "in qemu cmd line." % model_type)
  File "/root/82ltscode/avocado/avocado/core/test.py", line 953, in fail
    raise exceptions.TestFail(message)
avocado.core.exceptions.TestFail: Can not find the primary bochs video device in qemu cmd line.

Local variables:
 -> self <class 'avocado_vt.test.VirtTest'>: 1-type_specific.io-github-autotest-libvirt.virtual_devices.video_devices.positive_test.primary_video.bochs.no_secondary_video.model_test.default
DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
FAIL 1-type_specific.io-github-autotest-libvirt.virtual_devices.video_devices.positive_test.primary_video.bochs.no_secondary_video.model_test.default -> TestFail: Can not find the primary bochs video device in qemu cmd line.

Requested MAC address release from persistent vm avocado-vt-vm1. Ignoring.
Test results available in /root/avocado/job-results/job-2022-08-26T02.38-9b8d7c8

```

2022-08-26 06:42 UTC, chunfuwen commented on libvirt/tests/cfg/virtual_device/video_devices.cfg
> +                            only no_secondary_video..default_heads no_secondary_video..vram..bochs_default_size
@iccaszhulili 
If change pattern to no_secoddary_video..model_test.default, currently test code will throw error as below.

Reproduced traceback from: /root/82ltscode/avocado/avocado/core/test.py:767
Traceback (most recent call last):
  File "/root/82ltscode/avocado-vt/avocado_vt/test.py", line 200, in runTest
    raise self.__status  # pylint: disable=E0702
  File "/root/82ltscode/avocado-vt/avocado_vt/test.py", line 146, in setUp
    self._runTest()
  File "/root/82ltscode/avocado-vt/avocado_vt/test.py", line 263, in _runTest
    run_func(self, params, env)
  File "/root/82ltscode/tp-libvirt/libvirt/tests/src/virtual_device/video_devices.py", line 268, in run
    check_model_test_cmd_line(model_type, is_primary)
  File "/root/82ltscode/tp-libvirt/libvirt/tests/src/virtual_device/video_devices.py", line 123, in check_model_test_cmd_line
    "in qemu cmd line." % model_type)
  File "/root/82ltscode/avocado/avocado/core/test.py", line 953, in fail
    raise exceptions.TestFail(message)
avocado.core.exceptions.TestFail: Can not find the primary bochs video device in qemu cmd line.

Local variables:
 -> self <class 'avocado_vt.test.VirtTest'>: 1-type_specific.io-github-autotest-libvirt.virtual_devices.video_devices.positive_test.primary_video.bochs.no_secondary_video.model_test.default
DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
FAIL 1-type_specific.io-github-autotest-libvirt.virtual_devices.video_devices.positive_test.primary_video.bochs.no_secondary_video.model_test.default -> TestFail: Can not find the primary bochs video device in qemu cmd line.

Requested MAC address release from persistent vm avocado-vt-vm1. Ignoring.
Test results available in /root/avocado/job-results/job-2022-08-26T02.38-9b8d7c8

2022-08-29 02:50 UTC, iccaszhulili commented on libvirt/tests/cfg/virtual_device/video_devices.cfg
> +                            only no_secondary_video..default_heads no_secondary_video..vram..bochs_default_size
@chunfuwen Hi, it is because the qemu cmdline is different for bochs video, we need to add
            elif model_type == "bochs":
                pattern = r"-device.*bochs-display"
under

2022-08-29 07:04 UTC, chunfuwen commented
new test result attached:

Command 'virsh list' finished with 0 after 1.817685604095459s
cleaning libvirtd logs...
DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
PASS 1-type_specific.io-github-autotest-libvirt.virtual_devices.video_devices.positive_test.primary_video.bochs.no_secondary_video.model_test.default


[stdout] 
cleaning libvirtd logs...
DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
PASS 1-type_specific.io-github-autotest-libvirt.virtual_devices.video_devices.positive_test.primary_video.bochs.no_secondary_video.mem_test.vram.bochs_default_size

2022-08-29 07:05 UTC, chunfuwen commented on libvirt/tests/cfg/virtual_device/video_devices.cfg
> +                            only no_secondary_video..default_heads no_secondary_video..vram..bochs_default_size
@iccaszhulili 
updated as suggested

2022-08-29 08:02 UTC, iccaszhulili approved these changes

2022-08-29 08:02 UTC, iccaszhulili commented
LGTM

2022-08-30 06:46 UTC, dzhengfy approved these changes
LGTM

2022-08-30 06:46 UTC, merged