auth_pwd need have one initialized value if auth_pwd parameter is not…
autotest/tp-libvirt pull request #4384
Opened 2022-07-27 02:21 UTC by chunfuwen

auth_pwd need have one initialized value if auth_pwd parameter is not defined
    
    There are a few cases failure with below errors because of this
    File "/usr/local/lib/python3.6/site-packages/aexpect/client.py", line 412, in sendline
    self.send(cont + self.linesep)
    TypeError: unsupported operand type(s) for +: 'NoneType' and 'str

Signed-off-by: chunfuwen <chwen@redhat.com>

2022-07-27 02:24 UTC, chunfuwen commented
On s390x remote_acess job, below two cases failed with some errors:
 rhel.virsh.remote_with_unix.positive_testing.socket_with_polkit_and_acl_control	
 rhel.virsh.remote_with_unix.positive_testing.socket_with_polkit_rw

``
2022-07-22 06:45:44,360 stacktrace       L0042 ERROR| Reproduced traceback from: /var/tmp/libvirt-ci/runtest/avocado-vt/avocado/avocado/core/test.py:793
2022-07-22 06:45:44,361 stacktrace       L0045 ERROR| Traceback (most recent call last):
2022-07-22 06:45:44,361 stacktrace       L0045 ERROR|   File "/var/tmp/libvirt-ci/runtest/avocado-vt/avocado-vt/avocado_vt/test.py", line 200, in runTest
2022-07-22 06:45:44,361 stacktrace       L0045 ERROR|     raise self.__status  # pylint: disable=E0702
2022-07-22 06:45:44,361 stacktrace       L0045 ERROR|   File "/var/tmp/libvirt-ci/runtest/avocado-vt/avocado-vt/avocado_vt/test.py", line 146, in setUp
2022-07-22 06:45:44,361 stacktrace       L0045 ERROR|     self._runTest()
2022-07-22 06:45:44,361 stacktrace       L0045 ERROR|   File "/var/tmp/libvirt-ci/runtest/avocado-vt/avocado-vt/avocado_vt/test.py", line 263, in _runTest
2022-07-22 06:45:44,361 stacktrace       L0045 ERROR|     run_func(self, params, env)
2022-07-22 06:45:44,361 stacktrace       L0045 ERROR|   File "/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-libvirt/libvirt/tests/src/remote_access/remote_access.py", line 567, in run
2022-07-22 06:45:44,361 stacktrace       L0045 ERROR|     remote_access(test_dict, test)
2022-07-22 06:45:44,361 stacktrace       L0045 ERROR|   File "/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-libvirt/libvirt/tests/src/remote_access/remote_access.py", line 56, in remote_access
2022-07-22 06:45:44,361 stacktrace       L0045 ERROR|     patterns_extra_dict)
2022-07-22 06:45:44,361 stacktrace       L0045 ERROR|   File "/var/tmp/libvirt-ci/runtest/avocado-vt/avocado-vt/virttest/utils_test/libvirt.py", line 3145, in connect_libvirtd
2022-07-22 06:45:44,361 stacktrace       L0045 ERROR|     session.sendline(auth_pwd)
2022-07-22 06:45:44,361 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/aexpect/client.py", line 412, in sendline
2022-07-22 06:45:44,362 stacktrace       L0045 ERROR|     self.send(cont + self.linesep)
2022-07-22 06:45:44,362 stacktrace       L0045 ERROR| TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
2022-07-22 06:45:44,362 stacktrace       L0046 ERROR| 
``

2022-07-27 02:26 UTC, chunfuwen commented
@cliping 
@iccaszhulili 
@smitterl 
please help confirm this

2022-07-27 02:45 UTC, cliping approved these changes
LGTM

2022-07-27 14:29 UTC, smitterl requested changes
@chunfuwen Thank you for this. Sorry for nitpicking but could you please update the commit title and description? I had trouble understanding what this change is about. E.g. to me it looks like you unintentionally forgot to set a title.

2022-07-27 16:12 UTC, iccaszhulili reviewed
LGTM, but should we change the default value to like "123456", just like in other config file.

2022-07-28 06:58 UTC, chunfuwen commented
> LGTM, but should we change the default value to like "123456", just like in other config file.

@iccaszhulili , in most cases, password for the guest under testing is 'redhat'

2022-07-28 06:58 UTC, chunfuwen commented
> @chunfuwen Thank you for this. Sorry for nitpicking but could you please update the commit title and description? I had trouble understanding what this change is about. E.g. to me it looks like you unintentionally forgot to set a title.

@smitterl 
commit msg and description are updated

2022-07-28 11:00 UTC, iccaszhulili commented
> @iccaszhulili , in most cases, password for the guest under testing is 'redhat'
Yes, you are right, so do we need to keep it as private?

2022-08-01 01:11 UTC, chunfuwen commented
> > @iccaszhulili , in most cases, password for the guest under testing is 'redhat'
> > Yes, you are right, so do we need to keep it as private?

@iccaszhulili ,regarding this issue, there is ever discussion around this. Sorry to forget the link. 
In my opinion , the best practice should specify different password, other than default.
If using default one, there is no difference whether it is 123456 or redhat in nature

2022-08-01 01:21 UTC, iccaszhulili approved these changes

2022-08-01 01:21 UTC, iccaszhulili commented
LGTM

2022-08-22 01:51 UTC, chunfuwen commented
@dzhengfy  please take a look

2022-08-23 07:49 UTC, dzhengfy commented on libvirt/tests/src/remote_access/remote_access.py
> +    auth_pwd = params.get("auth_pwd", 'redhat')
password is sensitive information which should not be explicitly exposed in the script.
As auth_pwd is the password for remote host,  I notice there is already server_pwd in cfg file. So it should be fixed similar like below:
in cfg file:
server_pwd = ${remote_pwd}
auth_pwd = ${server_pwd}

Or we can use server_pwd instead of auth_pwd in the script.

2022-08-23 07:55 UTC, chunfuwen commented on libvirt/tests/src/remote_access/remote_access.py
> +    auth_pwd = params.get("auth_pwd", 'redhat')
@dzhengfy 
 the best practice should specify different password in cfg file, other than default one.
Here it is just the situation where we specify guest password in virttest/shared/cfg/guest-os/Linux.cfg under avocado-vt

2022-08-23 08:23 UTC, dzhengfy approved these changes
LGTM

2022-08-24 10:23 UTC, smitterl approved these changes
温春福 谢谢

2022-08-25 01:14 UTC, chunfuwen commented
In terms of test result, remote access need setup two machines, and in s390x, there are limited machines for this. Considering the change is minor and impact is very limited, let's merge it ,and monitor it.

2022-08-25 01:15 UTC, merged