tpm_device: some xml config test of bz2084046
autotest/tp-libvirt pull request #4597
Opened 2022-10-24 12:21 UTC by yanqzhan

Including add active_pcr_banks for version default scenario, add invalid tpm model test, add text 'default' value for backend version test.

Signed-off-by: Yanqiu Zhang <yanqzhan@redhat.com>

2022-10-24 12:30 UTC, yanqzhan commented
Local test pass:
1.libvirt-8.8.0-1
#  avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 tpm_device..invalid_model tpm_device..version_textdefault tpm_device..version_default
JOB ID     : 124a1a67ff9dfc2ea75e86f45d30da363a095937
JOB LOG    : /var/lib/avocado/job-results/job-2022-10-24T08.22-124a1a6/job.log
 (1/3) type_specific.io-github-autotest-libvirt.virtual_devices.tpm_device.negative_test.invalid_model: PASS (13.11 s)
 (2/3) type_specific.io-github-autotest-libvirt.virtual_devices.tpm_device.negative_test.emulator.backend_version.version_textdefault: PASS (12.85 s)
 (3/3) type_specific.io-github-autotest-libvirt.virtual_devices.tpm_device.normal_test.tpm-crb_model.emulator.plain.pcrbank_default.version_default: PASS (53.89 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/lib/avocado/job-results/job-2022-10-24T08.22-124a1a6/results.html
JOB TIME   : 81.82 s

2.libvirt-8.5.0-7
JOB ID     : a3bd4539b3f0ded446de961a41f96500fc0c8dc2
JOB LOG    : /var/lib/avocado/job-results/job-2022-10-24T08.28-a3bd453/job.log
 (1/3) type_specific.io-github-autotest-libvirt.virtual_devices.tpm_device.negative_test.invalid_model: PASS (17.84 s)
 (2/3) type_specific.io-github-autotest-libvirt.virtual_devices.tpm_device.negative_test.emulator.backend_version.version_textdefault: PASS (22.04 s)
 (3/3) type_specific.io-github-autotest-libvirt.virtual_devices.tpm_device.normal_test.tpm-crb_model.emulator.plain.pcrbank_default.version_default: PASS (88.16 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/lib/avocado/job-results/job-2022-10-24T08.28-a3bd453/results.html
JOB TIME   : 140.12 s

2022-10-24 13:37 UTC, yanqzhan commented
@dzhengfy Please review. Thanks!

2022-10-27 02:53 UTC, yanqzhan commented
Job#libvirt-RHEL-8.$latest-runtest-x86_64-function-tpm_emulator/10/ with libvirt-8.0.0-11 passed with { "CI_PR": "tp-libvirt 4597"}.
Next will check rhel-9.$latest job.

2022-10-31 12:45 UTC, vasekhodina requested changes

2022-10-31 12:45 UTC, vasekhodina commented on libvirt/tests/src/virtual_device/tpm_device.py
> +        #check this from libvirt-8.7.0.
Redundant comment line, this is apparent from line 87

2022-10-31 12:45 UTC, vasekhodina commented on libvirt/tests/src/virtual_device/tpm_device.py
> +        # Check active_pcr_banks
Please consider creating a function check_active_pcr_banks() with patterns as needed.
Something like:
```
if active_pcr_banks and not remove_pcrbank:
    check_active_pcr_banks(pattern, xml_after_adding_device)
```
The body of the function will be roughly lines 272 to 278.

2022-10-31 12:45 UTC, vasekhodina commented on libvirt/tests/src/virtual_device/tpm_device.py
> +        # For default model and text default version, no need start guest to test
Redundant comment to line 728, please consider removing it.

2022-11-01 03:07 UTC, yanqzhan commented on libvirt/tests/src/virtual_device/tpm_device.py
> +        #check this from libvirt-8.7.0.
There was comment in previous pr that requires bugID for comments: https://github.com/autotest/tp-libvirt/pull/4585/files.
Of course it can be removed.

2022-11-01 03:23 UTC, yanqzhan commented on libvirt/tests/src/virtual_device/tpm_device.py
> +        # Check active_pcr_banks
Thanks! But only an extra 'loop if' for it compared to others, I would like to keep it there, don't like too much function nesting.

2022-11-01 03:31 UTC, yanqzhan commented on libvirt/tests/src/virtual_device/tpm_device.py
> +        # For default model and text default version, no need start guest to test
Thanks! I added this line wanting to help users know about testing design not just code explanation. Since from L728, not just vm.start, but also many other operations in this 'if' branch. I want to help them know the main difference without finishing reading all contents below. Could I keep it?

2022-11-01 03:43 UTC, yanqzhan commented on libvirt/tests/src/virtual_device/tpm_device.py
> +        #check this from libvirt-8.7.0.
So I only removed L89 but not L88, is it meet your comment?

2022-11-02 16:13 UTC, vasekhodina commented on libvirt/tests/src/virtual_device/tpm_device.py
> +        #check this from libvirt-8.7.0.
Yes, that is ok with me.

2022-11-03 02:48 UTC, chunfuwen commented on libvirt/tests/src/virtual_device/tpm_device.py
> +        if active_pcr_banks and not remove_pcrbank:
line 269 to line 277 can be wrapped into one standalone method

2022-11-04 11:57 UTC, yanqzhan commented on libvirt/tests/src/virtual_device/tpm_device.py
> +        # Check active_pcr_banks
DONE.

2022-11-04 11:58 UTC, yanqzhan commented on libvirt/tests/src/virtual_device/tpm_device.py
> +        # For default model and text default version, no need start guest to test
DONE.

2022-11-04 11:58 UTC, yanqzhan commented on libvirt/tests/src/virtual_device/tpm_device.py
> +        if active_pcr_banks and not remove_pcrbank:
DONE.

2022-11-04 11:59 UTC, yanqzhan commented
@chunfuwen @vasekhodina Please review again. Thanks!

2022-11-10 06:55 UTC, chunfuwen approved these changes
LGTM

2022-11-21 09:03 UTC, vasekhodina approved these changes
I have suggested one minor edit regarding a comment on one line. Otherwise LGTM. Sorry this PR was stalled because of me.

2022-11-21 09:03 UTC, vasekhodina commented on libvirt/tests/src/virtual_device/tpm_device.py
> +        # Check active_pcr_banks
Comment on line 283 can be removed.

2022-11-22 02:34 UTC, yanqzhan commented
@vasekhodina Hi, 
1. This comment had already been removed, no concern now: "# For default model and text default version, no need start guest to test"
2. For the extra 'loop if' I mean following content in current L248. But it was also modified to a new function as you suggested.
         for pcrbank in active_pcr_banks:
            if pcrbank not in astring.to_text(xml):
                test.fail("Can not find the %s pcrbank xml for tpm dev "
                          "in the guest xml file." % pcrbank)
3. For L283, to keep consistent with other fragments(all with #check ***) in same function check_dumpxml(), please let me keep it.
Thanks!

2022-11-22 03:05 UTC, dzhengfy commented
@vasekhodina Could we merge this pr now? I saw you approved this pr, but you have new comment after that. So please give me the conclusion. Thanks.

2022-11-24 10:34 UTC, vasekhodina commented
@dzhengfy We can merge this now. I'm ok with the explanations.

2022-12-02 08:52 UTC, merged