Add new case of interface update
autotest/tp-libvirt pull request #4609
Opened 2022-10-28 06:46 UTC by chloerh

- VIRT-99433 - update boot order in interface

Signed-off-by: Haijiao Zhao <haizhao@redhat.com>

2022-10-31 13:42 UTC, vasekhodina requested changes

2022-10-31 13:42 UTC, vasekhodina commented on libvirt/tests/src/virtual_network/iface_update.py
> +    for fea in vm_feature_append:
I would like to see a whole word feature. There is no rule against having long name in "index" of a for loop.

2022-10-31 13:42 UTC, vasekhodina commented on libvirt/tests/src/virtual_network/iface_update.py
> +    logging.info('Update vmxml features.')
Please consider if it would be useful to log each feature updated. Maybe with debug priority.

2022-10-31 13:42 UTC, vasekhodina commented on libvirt/tests/src/virtual_network/iface_update.py
> +    logging.info('Add IOMMU device.')
Wouldn't it be better to log IOMMU device attrs as well here?

2022-10-31 13:42 UTC, vasekhodina commented on libvirt/tests/src/virtual_network/iface_update.py
> +    logging.debug(iface_inst.fetch_attrs())
Wouldn't it be better to add some string explaining the data that are logged here?

2022-10-31 13:42 UTC, vasekhodina commented on libvirt/tests/src/virtual_network/iface_update.py
> +    logging.debug(net_pgs)
Same as line 91.

2022-10-31 13:42 UTC, vasekhodina commented on libvirt/tests/src/virtual_network/iface_update.py
> +    # Remove os boot config
Redundant comment. It doesn't explain "why?" only states what is clear from lines below.

2022-10-31 13:42 UTC, vasekhodina commented on libvirt/tests/src/virtual_network/iface_update.py
> +    # Add boot config to disk
Same issue as line 112.

2022-10-31 13:42 UTC, vasekhodina commented on libvirt/tests/src/virtual_network/iface_update.py
> +            add_iommu_device(params)
I really like this way of taking code block with comment and creating a function with the same name as to comment. All commented code blocks should be reworked like this.

2022-11-03 02:36 UTC, chloerh commented on libvirt/tests/src/virtual_network/iface_update.py
> +    for fea in vm_feature_append:
How about `feature_name` which is less likely to be mixed up with `features`?

2022-11-03 02:38 UTC, chloerh commented on libvirt/tests/src/virtual_network/iface_update.py
> +    for fea in vm_feature_append:
How about `feature_name` which is less likely to be mixed up with `features`?

2022-11-03 02:38 UTC, chloerh commented on libvirt/tests/src/virtual_network/iface_update.py
> +    logging.info('Update vmxml features.')
Yes, it would be helpful.

2022-11-03 02:44 UTC, chloerh commented on libvirt/tests/src/virtual_network/iface_update.py
> +    logging.info('Add IOMMU device.')
Yes, it would be better.

2022-11-03 02:45 UTC, chloerh commented on libvirt/tests/src/virtual_network/iface_update.py
> +    logging.debug(iface_inst.fetch_attrs())
Yes, you're right. I really need to pay more attention to this.

2022-11-03 02:49 UTC, chloerh commented on libvirt/tests/src/virtual_network/iface_update.py
> +    logging.debug(net_pgs)
Done.

2022-11-03 02:53 UTC, chloerh commented on libvirt/tests/src/virtual_network/iface_update.py
> +    # Remove os boot config
Updated to explain why.

2022-11-03 02:53 UTC, chloerh commented on libvirt/tests/src/virtual_network/iface_update.py
> +    # Add boot config to disk
Removed.

2022-11-03 03:00 UTC, chloerh commented on libvirt/tests/src/virtual_network/iface_update.py
> +            add_iommu_device(params)
Yes, I'm working on it, especially the old code that I wrote...

2022-11-21 12:04 UTC, vasekhodina commented on libvirt/tests/src/virtual_network/iface_update.py
> +    for fea in vm_feature_append:
Sure, works for me.

2022-11-21 12:18 UTC, vasekhodina commented on libvirt/tests/src/virtual_network/iface_update.py
> +            "filter", 'boot', 'coalesce', 'source', 'boot',
Is boot sopposed to be twice on this line?

2022-11-21 12:20 UTC, vasekhodina reviewed
I found one more thing, boot is specified twice.

2022-11-22 03:05 UTC, chloerh commented on libvirt/tests/src/virtual_network/iface_update.py
> +            "filter", 'boot', 'coalesce', 'source', 'boot',
You're right. I totally missed that. Thanks.

2022-11-22 03:12 UTC, chloerh commented
> I found one more thing, boot is specified twice.

@vasekhodina code updated. Please take a look. Thanks.

2022-11-22 04:00 UTC, dzhengfy commented on libvirt/tests/src/virtual_network/iface_update.py
> +def add_iommu_device(params):
Please consider this function in ` avocado_vt/virttest/utils_libvirt/libvirt_virtio/ add_iommu_dev() `

2022-11-22 04:00 UTC, dzhengfy commented on libvirt/tests/src/virtual_network/iface_update.py
> +def update_features(params):
If you reuse` avocado_vt/virttest/utils_libvirt/libvirt_virtio/ add_iommu_dev()`, this function could be removed, I think.

2022-11-22 04:00 UTC, dzhengfy commented on libvirt/tests/src/virtual_network/iface_update.py
> +def add_iommu_device(params):
Please consider to reuse virttest/utils_libvirt/libvirt_virtio.py add_iommu_dev()

2022-11-22 04:00 UTC, dzhengfy commented on libvirt/tests/src/virtual_network/iface_update.py
> +def update_features(params):
If you reuse add_`iommu_dev() in virttest/utils_libvirt/libvirt_virtio.py`, you could remove this function, I think

2022-11-22 04:00 UTC, dzhengfy commented on libvirt/tests/src/virtual_network/iface_update.py
> +def update_vm_boot(vm_name, disk_boot):
`update_vm_boot_order` should be more accurate.

2022-11-22 04:00 UTC, dzhengfy commented on libvirt/tests/src/virtual_network/iface_update.py
> +        test.fail('Boot order update does not meet expectation.')
Could you provide the values for `iface.boot `and `params.get('new_iface_boot')` in this exception for better debugging?

2022-11-22 07:09 UTC, chloerh commented on libvirt/tests/cfg/virtual_network/iface_update.cfg
> +                        - disk_boot:
Yes, it is better name.

2022-11-22 07:33 UTC, chloerh commented on libvirt/tests/cfg/virtual_network/iface_update.cfg
> +                        - os_boot:
How about  `with_os_boot`?

2022-11-22 07:33 UTC, chloerh commented on libvirt/tests/src/virtual_network/iface_update.py
> +def add_iommu_device(params):
Thanks, this is very helpful.

2022-11-22 07:33 UTC, chloerh commented on libvirt/tests/src/virtual_network/iface_update.py
> +def update_features(params):
OK

2022-11-22 07:33 UTC, chloerh commented on libvirt/tests/src/virtual_network/iface_update.py
> +def add_iommu_device(params):
OK

2022-11-22 07:34 UTC, chloerh commented on libvirt/tests/src/virtual_network/iface_update.py
> +def update_features(params):
Ok

2022-11-22 07:35 UTC, chloerh commented on libvirt/tests/src/virtual_network/iface_update.py
> +def update_vm_boot(vm_name, disk_boot):
Updated.

2022-11-22 08:10 UTC, chloerh commented on libvirt/tests/src/virtual_network/iface_update.py
> +        test.fail('Boot order update does not meet expectation.')
Updated.

2022-11-24 10:50 UTC, vasekhodina approved these changes
LGTM

2022-12-02 02:51 UTC, dzhengfy reviewed
Others LGTM

2022-12-02 02:51 UTC, dzhengfy commented on libvirt/tests/src/virtual_network/iface_update.py
> +    :param vm: test vm
Need one more blank line above this line.

2022-12-05 03:27 UTC, dzhengfy approved these changes

2022-12-05 03:28 UTC, merged