Implement SE environment check on s390x
autotest/tp-libvirt pull request #4611
Opened 2022-10-28 12:20 UTC by fbq815

Secure execution: Implement SE environment check on s390x

Signed-off-by: Boqiao Fu <bfu@redhat.com>

2022-11-02 14:26 UTC, smitterl requested changes

2022-11-02 14:26 UTC, smitterl commented on libvirt/tests/src/secure_execution/secure_execution.py
> +            update_boot_option_and_reboot(vm, kernel_params, test)
I think setting the kernel cmdline is not necessary.

The kernel parameter 'prot_virt=1' needs to be set on the host and the host needs to be rebooted to activate SE. I believe this is something that the CI / test host installation should take care of.

2022-11-02 14:26 UTC, smitterl commented on libvirt/tests/src/secure_execution/secure_execution.py
> +        if start_vm == "yes":
I think you can drop this conditional: By setting `start_vm = yes` in the test config you determine that the VM must be running and you should be able to rely on that.

2022-11-02 14:26 UTC, smitterl commented on libvirt/tests/src/secure_execution/secure_execution.py
> +        test.fail("SE environment not enable in host")
typo: s/enable/enabled/, preferably I'd say "SE not enabled on host"

2022-11-02 14:26 UTC, smitterl commented on libvirt/tests/src/secure_execution/secure_execution.py
> +                if output:
It looks like `run_cmd_in_guest` always returns some output, does the conditional here work?

2022-11-02 14:26 UTC, smitterl commented on libvirt/tests/src/secure_execution/secure_execution.py
> +                    logging.info("Enable SE successfully in guest")
Is the message correct? Do you enable SE in the guest or do you confirm that it's running securely?

2022-11-02 14:26 UTC, smitterl commented on libvirt/tests/src/secure_execution/secure_execution.py
> +                test.error("Can not enable SE in guest")
Is this needed? Please mind, that `test.error` should be used instead of `test.fail` if a test precondition cannot be established, the test has to be aborted early, is this the case here?

2022-11-02 14:26 UTC, smitterl commented on libvirt/tests/src/secure_execution/secure_execution.py
> +        if kernel_params:
s. above

2022-11-08 02:40 UTC, fbq815 commented on libvirt/tests/src/secure_execution/secure_execution.py
> +        test.fail("SE environment not enable in host")
updated

2022-11-08 02:40 UTC, fbq815 commented on libvirt/tests/src/secure_execution/secure_execution.py
> +        if start_vm == "yes":
updated

2022-11-08 02:42 UTC, fbq815 commented on libvirt/tests/src/secure_execution/secure_execution.py
> +                if output:
updated

2022-11-08 02:45 UTC, fbq815 commented on libvirt/tests/src/secure_execution/secure_execution.py
> +                    logging.info("Enable SE successfully in guest")
updated

2022-11-09 09:28 UTC, fbq815 commented on libvirt/tests/src/secure_execution/secure_execution.py
> +            update_boot_option_and_reboot(vm, kernel_params, test)
updated

2022-11-09 09:28 UTC, fbq815 commented on libvirt/tests/src/secure_execution/secure_execution.py
> +        if kernel_params:
updated

2022-11-09 10:24 UTC, fbq815 commented on libvirt/tests/src/secure_execution/secure_execution.py
> +                test.error("Can not enable SE in guest")
Updated

2022-11-10 10:49 UTC, fbq815 commented
Test result:
JOB ID     : c0966d7252e50cd40de609304c885d01b8bcae3f
JOB LOG    : /root/avocado/job-results/job-2022-11-10T05.44-c0966d7/job.log
 (1/1) type_specific.io-github-autotest-libvirt.secure_execution.secure_execution.confirm_environment: STARTED
 (1/1) type_specific.io-github-autotest-libvirt.secure_execution.secure_execution.confirm_environment: PASS (90.83 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2022-11-10T05.44-c0966d7/results.html
JOB TIME   : 92.66 s

@dzhengfy @smitterl please help me review this patch

2022-11-11 09:45 UTC, smitterl commented on libvirt/tests/src/secure_execution/secure_execution.py
> +def update_boot_option_and_reboot(vm, kernel_params, test):
Not needed please remove.

2022-11-14 16:28 UTC, smitterl approved these changes
Thank you @fbq815

2022-11-15 04:09 UTC, fbq815 commented
JOB ID     : afa84fbcd3b02a033d412d905ff47232d839e62a
JOB LOG    : /root/avocado/job-results/job-2022-11-11T05.14-afa84fb/job.log
 (1/1) type_specific.io-github-autotest-libvirt.secure_execution.secure_execution.confirm_environment: STARTED
 (1/1) type_specific.io-github-autotest-libvirt.secure_execution.secure_execution.confirm_environment: PASS (17.38 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2022-11-11T05.14-afa84fb/results.html
JOB TIME   : 19.23 s

@dzhengfy @chunfuwen please help me review this patch

2022-11-15 04:10 UTC, fbq815 commented
updated

2022-11-15 04:10 UTC, fbq815 commented on libvirt/tests/src/secure_execution/secure_execution.py
> +def update_boot_option_and_reboot(vm, kernel_params, test):
updated

2022-11-15 04:10 UTC, fbq815 commented on libvirt/tests/src/secure_execution/secure_execution.py
> +        cmd = "grubby --update-kernel=`grubby --default-kernel` " \
updated

2022-11-15 04:10 UTC, fbq815 commented on libvirt/tests/src/secure_execution/secure_execution.py
> +        update_boot_option_and_reboot(vm, kernel_params, test)
updated

2022-11-21 08:48 UTC, dzhengfy commented on libvirt/tests/src/secure_execution/secure_execution.py
> +    Run command in the guest
Add one blank line below this line as a common rule for docstring

2022-11-21 08:48 UTC, dzhengfy commented on libvirt/tests/src/secure_execution/secure_execution.py
> +    """
Another two parameters should be also included in docstring.

2022-11-21 08:48 UTC, dzhengfy commented on libvirt/tests/src/secure_execution/secure_execution.py
> +        session.close()
Session close should always happen instead of only when status is not None

2022-11-21 08:48 UTC, dzhengfy commented on libvirt/tests/src/secure_execution/secure_execution.py
> +    else:
if status is not None, we should raise test.error() because there is an unexpected failure happened when running the command within the vm.

2022-11-21 08:48 UTC, dzhengfy commented on libvirt/tests/src/secure_execution/secure_execution.py
> +    with the 'launchSecurity' element
If we need the vm xml includes 'launchSecurity' element for the test, usually we will do below steps:

Backup the existing vm xml provided by CI 
Update the vm xml to have 'launchSecurity' configured
Start vm and check the functionality

2022-11-21 08:51 UTC, chunfuwen commented on libvirt/tests/cfg/secure_execution/secure_execution.cfg
> +- virsh.secure_execution:
virsh.secure_execution --> secure_execution

2022-11-21 08:54 UTC, fbq815 commented on libvirt/tests/src/secure_execution/secure_execution.py
> +    Run command in the guest
updated

2022-11-21 08:56 UTC, chunfuwen commented on libvirt/tests/cfg/secure_execution/secure_execution.cfg
> +    type = secure_execution
secure_execution --> secure_execution_domain ? let's make minor difference with folder name:secure_execution considering we may have more cfg files under secure_execution folder in coming future.

2022-11-21 08:58 UTC, chunfuwen commented on libvirt/tests/src/secure_execution/secure_execution.py
> +    Run command in the guest
doc string not aligned with this method parameter?

2022-11-21 09:00 UTC, chunfuwen commented on libvirt/tests/src/secure_execution/secure_execution.py
> +    if output:
line 39 ~line 42 can directly pulled into method run_cmd_in_guest. And this validation can be done among  run_cmd_in_guest itself.

2022-11-21 09:08 UTC, fbq815 commented on libvirt/tests/src/secure_execution/secure_execution.py
> +    """
updated

2022-11-21 09:11 UTC, fbq815 commented on libvirt/tests/src/secure_execution/secure_execution.py
> +        session.close()
Updated

2022-11-21 09:15 UTC, fbq815 commented on libvirt/tests/src/secure_execution/secure_execution.py
> +    with the 'launchSecurity' element
the reason why I didn't backup the existing vm xml is because this test case case will only run with an ideal test loop with secure_execution

2022-11-21 09:17 UTC, fbq815 commented on libvirt/tests/src/secure_execution/secure_execution.py
> +    else:
The status here will return 0 when it runs well, and I'll need that information below

2022-11-21 09:40 UTC, fbq815 commented on libvirt/tests/cfg/secure_execution/secure_execution.cfg
> +- virsh.secure_execution:
updated

2022-11-21 09:41 UTC, fbq815 commented on libvirt/tests/cfg/secure_execution/secure_execution.cfg
> +    type = secure_execution
Updated

2022-11-21 09:50 UTC, fbq815 commented on libvirt/tests/src/secure_execution/secure_execution.py
> +    if output:
Updated

2022-11-21 10:44 UTC, fbq815 commented on libvirt/tests/src/secure_execution/secure_execution.py
> +    Run command in the guest
Updated

2022-11-21 11:12 UTC, fbq815 commented
Test result:
JOB ID     : c5373a06e68912e6155f6646bbb538d3035875cb
JOB LOG    : /root/avocado/job-results/job-2022-11-21T04.48-c5373a0/job.log
 (1/1) type_specific.io-github-autotest-libvirt.secure_execution.secure_execution.confirm_environment: STARTED
 (1/1) type_specific.io-github-autotest-libvirt.secure_execution.secure_execution.confirm_environment: PASS (16.93 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2022-11-21T04.48-c5373a0/results.html
JOB TIME   : 18.77 s

@dzhengfy @chunfuwen please help me review this patch

2022-11-22 00:27 UTC, chunfuwen commented on libvirt/tests/src/secure_execution/secure_execution.py
> +    with the 'launchSecurity' element
In libvirt, if you want to make secure execution e.g SEV work, it need configure related sev attributes in domain.xml.
Otherwise, it won't work(refer to https://libvirt.org/formatdomain.html#launch-security)
```
  <launchSecurity type='sev' kernelHashes='yes'>
    <policy>0x0001</policy>
    <cbitpos>47</cbitpos>
    <reducedPhysBits>1</reducedPhysBits>
    <dhCert>RBBBSDDD=FDDCCCDDDG</dhCert>
    <session>AAACCCDD=FFFCCCDSDS</session>
  </launchSecurity>
```

2022-11-22 00:36 UTC, chunfuwen commented on libvirt/tests/src/secure_execution/secure_execution.py
> +    1. The guest image is a secure image and the domain already has been setup
@smitterl 
@fbq815 
Since this case will be running under libvirt CI. I wonder where  secure image .eg. protected.qcow2 comes from and how it can be provisioned in libvirt CI?

2022-11-24 07:15 UTC, fbq815 commented on libvirt/tests/src/secure_execution/secure_execution.py
> +    with the 'launchSecurity' element
I discussed with Sebas before, the xml file will be modified locally before triggering this test loop, that's why we didn't add it here. Please correct me if I misunderstanding @smitterl

2022-11-24 09:49 UTC, smitterl commented on libvirt/tests/src/secure_execution/secure_execution.py
> +    1. The guest image is a secure image and the domain already has been setup
@chunfuwen At this point we only run these tests for the milestones. I provision the images manually but there's also a task to automate the creation process.

2022-11-24 09:57 UTC, smitterl commented on libvirt/tests/src/secure_execution/secure_execution.py
> +    with the 'launchSecurity' element
@chunfuwen @fbq815 , we assumed here that the domain already has the launchSecurity element, this is how we will run it in libvirt-CI. We added that as assumption in the test run's comment. This way I hoped the code would be simpler because don't have to handle both situations 1) when the element is already present or b) when it's not present. Please let us know if this works for you. Thanks

2022-11-24 10:50 UTC, chunfuwen commented
@smitterl 
@fbq815 
thanks for clarification, I approved it now

2022-11-24 10:50 UTC, chunfuwen approved these changes
LGTM

2022-12-01 09:41 UTC, dzhengfy approved these changes

2022-12-01 09:41 UTC, merged