remote_access, ensure dfe4159a works on older RHEL
autotest/tp-libvirt pull request #4625
Opened 2022-11-03 16:12 UTC by vasekhodina

Changes in commit dfe4159a broke test run on RHEL-8 and lower, because the configuration introduced by it works only on RHEL-9 and bigger.

This commit tries to fix the crashes by checking RHEL version before running the updated code.

Related test case: VIRT-18307

2022-11-08 16:07 UTC, vasekhodina commented
@dzhengfy Test results from run on RHEL 8.8. Any other tests we need to run?
![image](https://user-images.githubusercontent.com/1662022/200615995-9a4849be-12c5-4218-894d-080cedb50854.png)

2022-11-10 06:51 UTC, chunfuwen commented on libvirt/tests/src/remote_access/remote_access.py
> +    if float(current_version) < minimum_version:
maybe line 239 to 241 can be simplified  as below:
return float(current_version) < minimum_version

2022-11-11 03:44 UTC, dzhengfy commented on libvirt/tests/src/remote_access/remote_access.py
> +def check_rhel_version(minimum_version, os_version):
This case is for testing https://bugzilla.redhat.com/show_bug.cgi?id=2112348. So we need to check libvirt version (8.5.0-5) which the bug was fixed in instead of rhel version. 

The better solution I suggest is :
```
    if driver == "xen":
    # Here we judge libvirt version using below
        if libvirt_version.version_compare(8, 5, 0):
            if ssh_config_path:
                if os.path.exists(ssh_config_path):
                    ssh_config_backup_path = create_file_backup(ssh_config_path)
                change_ssh_conf_on_client(ssh_config_path, uri_path)
            if openssl_config_path:
                change_openssl_conf_on_client(openssl_config_path)
                test_dict["extra_env"] = f"OPENSSL_CONF={openssl_config_path}"

```
And in your finally clean up part, you might consider to use version_compare() again. Like below

```
       if libvirt_version.version_compare(8, 5, 0):
            if ssh_config_path:
                os.remove(ssh_config_path)
      
            if ssh_config_backup_path:
                shutil.copy(ssh_config_backup_path, ssh_config_path)
                os.remove(ssh_config_backup_path)
      
            if openssl_config_path:
                os.remove(openssl_config_path)

```

2022-11-11 03:45 UTC, dzhengfy requested changes
Please consider above my comments

2022-11-11 09:24 UTC, vasekhodina commented on libvirt/tests/src/remote_access/remote_access.py
> +    if float(current_version) < minimum_version:
The whole function was deteled and replaced by libvirt_version.version_compare(8, 5, 0) in places where it was used.

2022-11-11 09:24 UTC, vasekhodina commented on libvirt/tests/src/remote_access/remote_access.py
> +def check_rhel_version(minimum_version, os_version):
Updated.

2022-11-11 09:30 UTC, dzhengfy reviewed
LGTM. Please paste the test result on RHEL 8.7 and latest 9.x ,thanks

2022-11-11 09:30 UTC, dzhengfy approved these changes

2022-11-11 15:07 UTC, vasekhodina commented
Results from RHEL 9.2:
![image](https://user-images.githubusercontent.com/1662022/201367999-d035c57c-0095-466e-90a5-0d1b29fa93f3.png)

2022-11-15 07:23 UTC, dzhengfy commented
8.7 result:

<table class="pane sortable bigtable stripped" id="testresult" style="box-sizing: inherit; font-size: var(--font-size-sm); color: var(--pane-text-color); width: 1341.48px; border-collapse: collapse; border: none;"><tbody style="box-sizing: inherit;"><tr style="box-sizing: inherit;"><td class="pane-header" style="box-sizing: inherit; vertical-align: top; font-size: var(--font-size-sm); padding: var(--bigtable-cell-padding-y) var(--bigtable-cell-padding-x); color: var(--bigtable-header-text-color); background: var(--bigtable-header-bg); border-top: var(--bigtable-border-width) solid var(--bigtable-row-border-color); border-bottom: var(--bigtable-border-width) solid var(--bigtable-row-border-color); border-image-source: ; border-image-slice: ; border-image-width: ; border-image-outset: ; border-image-repeat: ; border-left: none; border-right: none; border-radius: 0px; font-weight: var(--bigtable-header-font-weight);"><a href="https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/libvirt-RHEL-8.7-runtest-x86_64-function-remote_access/16/testReport/#" class="sortheader" style="box-sizing: inherit; text-decoration: var(--link-text-decoration); font-weight: var(--link-font-weight); color: var(--bigtable-header-text-color);">Package<span class="sortarrow" style="box-sizing: inherit; color: var(--bigtable-header-text-color);"></span></a></td><td class="pane-header" style="box-sizing: inherit; vertical-align: top; font-size: var(--font-size-sm); padding: var(--bigtable-cell-padding-y) var(--bigtable-cell-padding-x); color: var(--bigtable-header-text-color); background: var(--bigtable-header-bg); border-top: var(--bigtable-border-width) solid var(--bigtable-row-border-color); border-bottom: var(--bigtable-border-width) solid var(--bigtable-row-border-color); border-image-source: ; border-image-slice: ; border-image-width: ; border-image-outset: ; border-image-repeat: ; border-left: none; border-right: none; border-radius: 0px; font-weight: var(--bigtable-header-font-weight); width: 5em; text-align: right;"><a href="https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/libvirt-RHEL-8.7-runtest-x86_64-function-remote_access/16/testReport/#" class="sortheader" style="box-sizing: inherit; text-decoration: var(--link-text-decoration); font-weight: var(--link-font-weight); color: var(--bigtable-header-text-color);">Duration<span class="sortarrow" style="box-sizing: inherit; color: var(--bigtable-header-text-color);"></span></a></td><td class="pane-header" style="box-sizing: inherit; vertical-align: top; font-size: var(--font-size-sm); padding: var(--bigtable-cell-padding-y) var(--bigtable-cell-padding-x); color: var(--bigtable-header-text-color); background: var(--bigtable-header-bg); border-top: var(--bigtable-border-width) solid var(--bigtable-row-border-color); border-bottom: var(--bigtable-border-width) solid var(--bigtable-row-border-color); border-image-source: ; border-image-slice: ; border-image-width: ; border-image-outset: ; border-image-repeat: ; border-left: none; border-right: none; border-radius: 0px; font-weight: var(--bigtable-header-font-weight); width: 5em; text-align: right;"><a href="https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/libvirt-RHEL-8.7-runtest-x86_64-function-remote_access/16/testReport/#" class="sortheader" style="box-sizing: inherit; text-decoration: var(--link-text-decoration); font-weight: var(--link-font-weight); color: var(--bigtable-header-text-color);">Fail<span class="sortarrow" style="box-sizing: inherit; color: var(--bigtable-header-text-color);"></span></a></td><td class="pane-header" style="box-sizing: inherit; vertical-align: top; font-size: smaller; padding: var(--bigtable-cell-padding-y) var(--bigtable-cell-padding-x); color: var(--bigtable-header-text-color); background: var(--bigtable-header-bg); border-top: var(--bigtable-border-width) solid var(--bigtable-row-border-color); border-bottom: var(--bigtable-border-width) solid var(--bigtable-row-border-color); border-image-source: ; border-image-slice: ; border-image-width: ; border-image-outset: ; border-image-repeat: ; border-left: none; border-right: none; border-radius: 0px; font-weight: var(--bigtable-header-font-weight); width: 1em; text-align: right; white-space: nowrap;"><a href="https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/libvirt-RHEL-8.7-runtest-x86_64-function-remote_access/16/testReport/#" class="sortheader" style="box-sizing: inherit; text-decoration: var(--link-text-decoration); font-weight: var(--link-font-weight); color: var(--bigtable-header-text-color);">(diff)<span class="sortarrow" style="box-sizing: inherit; color: var(--bigtable-header-text-color);"></span></a></td><td class="pane-header" style="box-sizing: inherit; vertical-align: top; font-size: var(--font-size-sm); padding: var(--bigtable-cell-padding-y) var(--bigtable-cell-padding-x); color: var(--bigtable-header-text-color); background: var(--bigtable-header-bg); border-top: var(--bigtable-border-width) solid var(--bigtable-row-border-color); border-bottom: var(--bigtable-border-width) solid var(--bigtable-row-border-color); border-image-source: ; border-image-slice: ; border-image-width: ; border-image-outset: ; border-image-repeat: ; border-left: none; border-right: none; border-radius: 0px; font-weight: var(--bigtable-header-font-weight); width: 5em; text-align: right;"><a href="https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/libvirt-RHEL-8.7-runtest-x86_64-function-remote_access/16/testReport/#" class="sortheader" style="box-sizing: inherit; text-decoration: var(--link-text-decoration); font-weight: var(--link-font-weight); color: var(--bigtable-header-text-color);">Skip<span class="sortarrow" style="box-sizing: inherit; color: var(--bigtable-header-text-color);"></span></a></td><td class="pane-header" style="box-sizing: inherit; vertical-align: top; font-size: smaller; padding: var(--bigtable-cell-padding-y) var(--bigtable-cell-padding-x); color: var(--bigtable-header-text-color); background: var(--bigtable-header-bg); border-top: var(--bigtable-border-width) solid var(--bigtable-row-border-color); border-bottom: var(--bigtable-border-width) solid var(--bigtable-row-border-color); border-image-source: ; border-image-slice: ; border-image-width: ; border-image-outset: ; border-image-repeat: ; border-left: none; border-right: none; border-radius: 0px; font-weight: var(--bigtable-header-font-weight); width: 1em; text-align: right; white-space: nowrap;"><a href="https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/libvirt-RHEL-8.7-runtest-x86_64-function-remote_access/16/testReport/#" class="sortheader" style="box-sizing: inherit; text-decoration: var(--link-text-decoration); font-weight: var(--link-font-weight); color: var(--bigtable-header-text-color);">(diff)<span class="sortarrow" style="box-sizing: inherit; color: var(--bigtable-header-text-color);"></span></a></td><td class="pane-header" style="box-sizing: inherit; vertical-align: top; font-size: var(--font-size-sm); padding: var(--bigtable-cell-padding-y) var(--bigtable-cell-padding-x); color: var(--bigtable-header-text-color); background: var(--bigtable-header-bg); border-top: var(--bigtable-border-width) solid var(--bigtable-row-border-color); border-bottom: var(--bigtable-border-width) solid var(--bigtable-row-border-color); border-image-source: ; border-image-slice: ; border-image-width: ; border-image-outset: ; border-image-repeat: ; border-left: none; border-right: none; border-radius: 0px; font-weight: var(--bigtable-header-font-weight); width: 5em; text-align: right;"><a href="https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/libvirt-RHEL-8.7-runtest-x86_64-function-remote_access/16/testReport/#" class="sortheader" style="box-sizing: inherit; text-decoration: var(--link-text-decoration); font-weight: var(--link-font-weight); color: var(--bigtable-header-text-color);">Pass<span class="sortarrow" style="box-sizing: inherit; color: var(--bigtable-h [...]

2022-11-15 09:34 UTC, dzhengfy commented
Test result on 8.7 all pass except one case which is due to other reason

2022-11-15 09:37 UTC, chunfuwen approved these changes
LGTM

2022-11-15 09:41 UTC, merged