Add new case of memory test
autotest/tp-libvirt pull request #4647
Opened 2022-11-21 07:45 UTC by chloerh

- VIRT-295935 - Mount 1G hugepage path for a running guest vm backed by 2M hugepage memory - bug2123196

Signed-off-by: Haijiao Zhao <haizhao@redhat.com>

2022-11-21 07:51 UTC, dzhengfy commented
@liang-cong-red-hat, please help review

2022-11-21 09:57 UTC, dzhengfy reviewed
Others LGTM

2022-11-21 09:57 UTC, dzhengfy commented on libvirt/tests/src/memory/memory_misc.py
> +            test.log.debug('Free mem on vm: %d', free_mem)
Better to add the unit, 'kB'

2022-11-22 03:16 UTC, chloerh commented on libvirt/tests/src/memory/memory_misc.py
> +            test.log.debug('Free mem on vm: %d', free_mem)
OK. BTW, do you have any suggestion on the name of the case? I'm not quite satisfied with current name.

2022-11-24 10:23 UTC, Yingshun reviewed
is there anything that needs cleaning in the teardown?

2022-11-24 10:23 UTC, Yingshun commented on libvirt/tests/src/memory/memory_misc.py
> +                        % hp_path, shell=True)
we have a function - utils_misc.mount() in avocado-vt to mount a source to a mount_point, would you like to have a try?

2022-11-25 01:58 UTC, liang-cong-red-hat commented on libvirt/tests/src/memory/memory_misc.py
> +            test.log.debug('Free mem on vm: %d', free_mem)
I suggest full name is "mount hugepage path with running vm".

2022-11-25 08:31 UTC, liang-cong-red-hat requested changes

2022-11-25 08:31 UTC, liang-cong-red-hat commented on libvirt/tests/cfg/memory/memory_misc.cfg
> +                    mem_device_attrs = {'source': {'pagesize': 1048576, 'pagesize_unit': 'KiB', 'nodemask': '0-1'}, 'mem_model': 'dimm', 'target': {'size': 1048576, 'node': 0, 'size_unit': 'KiB'}}
For auto case, i remember we may encounter host with some numa node containing 0 memory. Here we could ignore "nodemask" tag, so no problem when host numa node 0 and 1 are short of hugepage memory.
Sure this may lead to difference between auto case with polarion case, if need i could modify the polarion case.

2022-11-25 08:31 UTC, liang-cong-red-hat commented on libvirt/tests/src/memory/memory_misc.py
> +                        % hp_path, shell=True)
Shall we umount hugepage path after case execution? 
BTW, if need, better destroy vm then umount hugepage path.

2022-11-25 08:31 UTC, liang-cong-red-hat commented on libvirt/tests/src/memory/memory_misc.py
> +            session.cmd('memhog %dM' % (int(free_mem) // 1024 - 100))
free_mem is int type, here don't have to convert it.

2022-12-01 02:36 UTC, chloerh commented on libvirt/tests/src/memory/memory_misc.py
> +            test.log.debug('Free mem on vm: %d', free_mem)
Thanks.Updating.

2022-12-01 02:55 UTC, chloerh commented on libvirt/tests/cfg/memory/memory_misc.cfg
> +                    mem_device_attrs = {'source': {'pagesize': 1048576, 'pagesize_unit': 'KiB', 'nodemask': '0-1'}, 'mem_model': 'dimm', 'target': {'size': 1048576, 'node': 0, 'size_unit': 'KiB'}}
Thanks, updating code. About the polarion case, let's ask @dzhengfy for her opinion.

2022-12-01 02:56 UTC, chloerh commented on libvirt/tests/src/memory/memory_misc.py
> +                        % hp_path, shell=True)
Yes, thanks.

2022-12-01 03:09 UTC, chloerh commented on libvirt/tests/src/memory/memory_misc.py
> +            session.cmd('memhog %dM' % (int(free_mem) // 1024 - 100))
Yes, updating, thanks.

2022-12-01 10:04 UTC, chloerh commented
Test result after update:
```
VMxml before login: <domain type='kvm' id='1'>
  <name>avocado-vt-vm1</name>
...
  <maxMemory slots='16' unit='KiB'>15243264</maxMemory>
  <memory unit='KiB'>3145728</memory>
  <currentMemory unit='KiB'>3145728</currentMemory>
  <memoryBacking>
    <hugepages>
      <page size='2048' unit='KiB'/>
    </hugepages>
  </memoryBacking>
  <vcpu placement='static'>4</vcpu>
...
  <cpu mode='custom' match='exact' check='full'>
    <model fallback='forbid'>Cascadelake-Server</model>
    <vendor>Intel</vendor>
...
    <numa>
      <cell id='0' cpus='0-1' memory='1048576' unit='KiB'/>
      <cell id='1' cpus='2-3' memory='1048576' unit='KiB'/>
    </numa>
  </cpu>

...
    <memory model='dimm'>
      <source>
        <pagesize unit='KiB'>1048576</pagesize>
      </source>
      <target>
        <size unit='KiB'>1048576</size>
        <node>0</node>
      </target>
      <alias name='dimm0'/>
      <address type='dimm' slot='0' base='0x100000000'/>
    </memory>
  </devices>
...
</domain>


Attempting to log into 'avocado-vt-vm1' (timeout 240s)
Updated HWADDR (52:54:00:fe:53:b3)<->(192.168.122.152) IP pair into address cache
Found/Verified IP 192.168.122.152 for VM avocado-vt-vm1 NIC 0
[stderr] DEBUG:aexpect.client:Sending command: swapoff -a

[stderr] DEBUG:aexpect.client:Sending command: echo $?

[stderr] DEBUG:aexpect.client:Sending command: grep MemFree /proc/meminfo

Free mem on vm: 2359032 kB
[stderr] DEBUG:aexpect.client:Sending command: memhog 2203M

[stderr] DEBUG:aexpect.client:Sending command: echo $?

Destroying VM
Trying to shutdown VM with shell command
Shutdown command sent; waiting for VM to go down...
VM is down
Running 'virtqemud -V'
[stdout] virtqemud (libvirt) 8.9.0
Command 'virtqemud -V' finished with 0 after 0.015141588s
Running 'true'
Command 'true' finished with 0 after 0.001477481s
Running 'ps -o comm 1'
[stdout] COMMAND
Command 'ps -o comm 1' finished with 0 after 0.017743836s
[stdout] systemd
Setting ignore_status to True.
Running 'systemctl reset-failed virtqemud'
Command 'systemctl reset-failed virtqemud' finished with 0 after 0.012851368s
Setting ignore_status to True.
Running 'systemctl restart virtqemud'
Command 'systemctl restart virtqemud' finished with 0 after 0.048059942s
Running 'virsh list'
[stdout]  Id   Name   State
[stdout] --------------------
[stdout] 
Command 'virsh list' finished with 0 after 0.100010210s
Running virsh command: start avocado-vt-vm1 
Running '/usr/bin/virsh start avocado-vt-vm1 '
[stdout] Domain 'avocado-vt-vm1' started
[stdout] 
Command '/usr/bin/virsh start avocado-vt-vm1 ' finished with 0 after 0.852469308s
status: 0
stdout: Domain 'avocado-vt-vm1' started
stderr: 
Undefine VM avocado-vt-vm1
Define VM from /tmp/xml_utils_temp_86u_all8.xml
...

Running 'umount /dev/hugepages1G'
Command 'umount /dev/hugepages1G' finished with 0 after 0.001852444s


...
PASS 1-type_specific.io-github-autotest-libvirt.memory_misc.memorybacking.mount_hp_running_vm
```

2022-12-01 10:06 UTC, chloerh commented
@Yingshun @liang-cong-red-hat @dzhengfy  Code updated. Please take a look, thanks!

2022-12-01 10:14 UTC, Yingshun approved these changes
LGTM

2022-12-02 02:00 UTC, liang-cong-red-hat approved these changes

2022-12-02 02:35 UTC, dzhengfy reviewed
Others LGTM

2022-12-02 02:35 UTC, dzhengfy commented on libvirt/tests/src/memory/memory_misc.py
> +            utils_misc.mount('hugetlbfs', hp_path, 'hugetlbfs',
Please use utils_disk.mount() directly.  utils_misc.mount is only a wrapper and we do not want more dependency on utils_misc. Thanks.

2022-12-02 03:01 UTC, chloerh commented on libvirt/tests/src/memory/memory_misc.py
> +            utils_misc.mount('hugetlbfs', hp_path, 'hugetlbfs',
Updated.

2022-12-02 09:27 UTC, dzhengfy approved these changes

2022-12-02 09:27 UTC, merged