Fix test failure expectations when libvirtd is off
autotest/tp-libvirt pull request #4658
Opened 2022-11-29 09:29 UTC by Anushree-Mathur

libvirtd is restarted after issuing virsh commands from libvirt version 5.6.0 on.

Signed-off-by: Anushree Mathur <anushree.mathur2@ibm.com>

2022-12-01 04:53 UTC, PraveenPenguin commented
@Anushree-Mathur can you please address pylint issue to make CI pass

2022-12-01 05:06 UTC, Anushree-Mathur commented
@praveenpylint issue fixed.

2022-12-02 06:42 UTC, PraveenPenguin requested changes

2022-12-02 06:42 UTC, PraveenPenguin commented on libvirt/tests/src/virsh_cmd/monitor/virsh_dominfo.py
> +from provider import libvirt_version
please use 'libvirt_version'  from virttest itself

2022-12-02 10:13 UTC, Anushree-Mathur commented on libvirt/tests/src/virsh_cmd/monitor/virsh_dominfo.py
> +from provider import libvirt_version
Did the changes @PraveenPenguin .

2022-12-02 10:36 UTC, bskjois approved these changes
Looks good to me

2022-12-02 12:08 UTC, PraveenPenguin commented
@Anushree-Mathur please squash both the commit  in a single commit

2022-12-05 02:22 UTC, dzhengfy commented on libvirt/tests/src/virsh_cmd/monitor/virsh_dominfo.py
> +import logging
Could you help move this line to the first line? Because we should make the import statements in alphabetical order. Thanks.

2022-12-05 02:22 UTC, dzhengfy commented on libvirt/tests/src/virsh_cmd/monitor/virsh_dominfo.py
Then there are two ways for logging methods.
1. Add a line above run() 
`LOG = logging.getLogger('avocado.' + __name__)` for the log object you will use in codes below. 
2. Directly use test.log.info() in codes below to print your log (then you need not to import logging).

2022-12-05 04:21 UTC, Anushree-Mathur commented
@PraveenPenguin i squashed the commits.

2022-12-05 07:19 UTC, Anushree-Mathur commented
By mistake there were multiple commits here so closing this request and raising a new pull request with all the comments addressed. https://github.com/autotest/tp-libvirt/pull/4669

2022-12-05 07:19 UTC, closed without merging

2022-12-22 10:01 UTC, Anushree-Mathur commented on libvirt/tests/src/virsh_cmd/monitor/virsh_dominfo.py
Thank you so much for the information will take this into consideration.