numa: increase the page_num_0 value for hugepages2M to fix failure
autotest/tp-libvirt pull request #4698
Opened 2023-01-06 08:22 UTC by meinaLi

numa: increase the page_num_0 value for hugepages2M to fix failure
Otherwise the guest can't start because of the insufficient memory.

Signed-off-by: Meina Li <meili@redhat.com>

2023-01-06 08:23 UTC, meinaLi commented
```
# avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 guest_numa.possitive_test.hugepage.per_node.2M.topology.numatune_memnode.m_strict.numatune_mem --vt-connect-uri qemu:///system
JOB ID     : 97855cbccbacd917e9238b50e20abc7f88c94553
JOB LOG    : /var/lib/avocado/job-results/job-2023-01-06T03.14-97855cb/job.log
 (1/1) type_specific.io-github-autotest-libvirt.guest_numa.possitive_test.hugepage.per_node.2M.topology.numatune_memnode.m_strict.numatune_mem: PASS (76.78 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/lib/avocado/job-results/job-2023-01-06T03.14-97855cb/results.html
JOB TIME   : 77.31 s
```

2023-01-09 02:51 UTC, chunfuwen reviewed
Do we need add judgement in python code that test case will be skipped if node memory may be less than 1024 ?

2023-01-09 02:52 UTC, chunfuwen commented on libvirt/tests/cfg/numa/guest_numa.cfg
> +                                     page_num_0 = "1024"
Do we need add judgement in python code that test case will be skipped if node memory may be less than 1024 ?
This may happen on some host.

2023-01-09 03:39 UTC, meinaLi commented on libvirt/tests/cfg/numa/guest_numa.cfg
> +                                     page_num_0 = "1024"
I think we can update it to the skiplist.yaml but no need in python code if it happens.

2023-01-09 06:40 UTC, liang-cong-red-hat requested changes
I suggest changing the 2M hugepage request num to 512, so that would decrease the chance of memory shortage.

2023-01-09 09:22 UTC, meinaLi commented
```
# avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 guest_numa.possitive_test.hugepage.per_node.2M
JOB ID     : 25b365f665ee41c441cd751d0e7fe365043b0626
JOB LOG    : /var/lib/avocado/job-results/job-2023-01-09T03.56-25b365f/job.log
 (01/16) type_specific.io-github-autotest-libvirt.guest_numa.possitive_test.hugepage.per_node.2M.topology.no_numatune_memnode.numatune_mem: PASS (78.69 s)
 (02/16) type_specific.io-github-autotest-libvirt.guest_numa.possitive_test.hugepage.per_node.2M.topology.no_numatune_memnode.no_numatune_mem: PASS (78.87 s)
 (03/16) type_specific.io-github-autotest-libvirt.guest_numa.possitive_test.hugepage.per_node.2M.topology.numatune_memnode.m_strict.numatune_mem: PASS (78.78 s)
......
 (15/16) type_specific.io-github-autotest-libvirt.guest_numa.possitive_test.hugepage.per_node.2M.no_topo.numatune_memnode.m_interleave.numatune_mem: PASS (76.73 s)
 (16/16) type_specific.io-github-autotest-libvirt.guest_numa.possitive_test.hugepage.per_node.2M.no_topo.numatune_memnode.m_interleave.no_numatune_mem: PASS (80.02 s)
RESULTS    : PASS 16 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/lib/avocado/job-results/job-2023-01-09T03.56-25b365f/results.html
JOB TIME   : 1261.52 s
```

2023-01-10 01:28 UTC, liang-cong-red-hat approved these changes
Fine with me.

2023-01-10 01:30 UTC, chunfuwen approved these changes
LGTM

2023-01-10 01:31 UTC, chunfuwen commented
let's merge it since it failed gating testing

2023-01-10 01:31 UTC, merged