guest_numa.py: cancel test when out of memory for host
autotest/tp-libvirt pull request #4737
Opened 2023-02-03 09:02 UTC by meinaLi

In gating, rhel.guest_numa.possitive_test.hugepage.per_node.2M.topology.numatune_memnode.m_strict.numatune_mem will fail when the host has not enough memory for node1. It may affectthe gating result. So  decided to cancel it in that case。

Signed-off-by: Meina Li <meili@redhat.com>

2023-02-03 09:03 UTC, meinaLi commented
```
# avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 guest_numa.possitive_test.hugepage.per_node.2M
JOB ID     : f88e547246f5a2322ff227c3f9551c9772d12a96
JOB LOG    : /var/lib/avocado/job-results/job-2023-02-03T01.47-f88e547/job.log
 (01/16) type_specific.io-github-autotest-libvirt.guest_numa.possitive_test.hugepage.per_node.2M.topology.no_numatune_memnode.numatune_mem: PASS (27.86 s)
 (02/16) type_specific.io-github-autotest-libvirt.guest_numa.possitive_test.hugepage.per_node.2M.topology.no_numatune_memnode.no_numatune_mem: PASS (26.34 s)
 (03/16) type_specific.io-github-autotest-libvirt.guest_numa.possitive_test.hugepage.per_node.2M.topology.numatune_memnode.m_strict.numatune_mem: PASS (26.12 s)
......
 (15/16) type_specific.io-github-autotest-libvirt.guest_numa.possitive_test.hugepage.per_node.2M.no_topo.numatune_memnode.m_interleave.numatune_mem: PASS (26.22 s)
 (16/16) type_specific.io-github-autotest-libvirt.guest_numa.possitive_test.hugepage.per_node.2M.no_topo.numatune_memnode.m_interleave.no_numatune_mem: PASS (26.95 s)
RESULTS    : PASS 16 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/lib/avocado/job-results/job-2023-02-03T01.47-f88e547/results.html
JOB TIME   : 433.41 s
```

2023-02-03 09:08 UTC, meinaLi commented
Why update it in this method?
1) The skiplist.yaml can't support this skip because it doesn't have a bug.
2) We can use the free size of node1 in host as a condition, but can not get specific value. It mainly depends on different hosts.
3) I don't suggest update the function hp_cl.set_node_num_huge_pages in __init__.py of avocado. I think it may affect other tests(not only libvirt) if we directly update it.
So here I directly move this function to the guest_numa.py to cancel it when the auto case encounter this failure.

2023-02-03 09:10 UTC, meinaLi commented
@kylazhang @liang-cong-red-hat
This is that numa issue with not enough memory we discussed before. Please help to review it. Thanks.

2023-02-07 11:09 UTC, chunfuwen approved these changes
LGTM

2023-02-08 01:54 UTC, chloerh requested changes

2023-02-08 01:54 UTC, chloerh commented on libvirt/tests/src/numa/guest_numa.py
> +
There's no need to copy the function here.

2023-02-08 01:54 UTC, chloerh commented on libvirt/tests/src/numa/guest_numa.py
> +                                            i['size'])
```suggestion
                    try:
                        hp_cl.set_node_num_huge_pages(i['num'],
                                                  i['nodenum'],
                                                  i['size'])
                     except ValueError as details:
                         if "please check if the node has enough memory" in str(details):
                             test.cancel(str(details))
                         else:
                             raise
                             
```

2023-02-08 01:56 UTC, liang-cong-red-hat approved these changes
LGTM

2023-02-08 02:23 UTC, dzhengfy commented on libvirt/tests/src/numa/guest_numa.py
> +                                            i['size'])
@meinaLi , I agree with @chloerh because her solution is easier and less codes.

2023-02-08 03:51 UTC, chunfuwen commented on libvirt/tests/src/numa/guest_numa.py
> +                                            i['size'])
I is just wondering why caught exception, rather than front judgement whether it satisfy pre-conditions like line 116, is recommended. Is there any industry practices ,which can be shared here?

2023-02-08 05:16 UTC, chunfuwen commented on libvirt/tests/src/numa/guest_numa.py
> +                                            i['size'])
In my opinion, in python world, we may try to avoid catching  exception, particularly fatal exception something like ValueError, although we can from technologies view.

2023-02-08 07:10 UTC, chloerh commented on libvirt/tests/src/numa/guest_numa.py
> +                                            i['size'])
> I is just wondering why caught exception, rather than front judgement whether it satisfy pre-conditions like line 116, is recommended. Is there any industry practices ,which can be shared here?

The function you mentioned at line 116 was copied from another file.

2023-02-08 09:44 UTC, dzhengfy commented
@Yingshun @cliping @nanli1 , I would like to hear your opinion. Thanks.

2023-02-08 10:06 UTC, Yingshun commented on libvirt/tests/src/numa/guest_numa.py
> +                                            i['size'])
> @meinaLi , I agree with @chloerh because her solution is easier and less codes.

+1. I think we should avoid copying codes from avocado-vt to tp-libvirt, especially for this case. In hp_cl.set_node_num_huge_pages(), the exception ValueError is a fixed error type if sysFS().sys_fs_value is smaller than the number we set, and from @chloerh 's suggestion, the error message will be checked as well. So it's ok for me.

2023-02-15 01:19 UTC, meinaLi commented on libvirt/tests/src/numa/guest_numa.py
> +                                            i['size'])
Thanks for your opinions. This method is valid and clear. I've already updated it.

2023-02-15 01:20 UTC, meinaLi commented on libvirt/tests/src/numa/guest_numa.py
> +
Remove it now.

2023-02-15 03:30 UTC, chloerh approved these changes

2023-02-15 04:15 UTC, Yingshun approved these changes

2023-02-15 05:42 UTC, dzhengfy approved these changes

2023-02-15 05:42 UTC, merged