memory_misc:Cancel test if fail to set hugepage number of numanode
autotest/tp-libvirt pull request #4787
Opened 2023-03-09 06:47 UTC by chloerh

2023-03-09 07:00 UTC, Yingshun approved these changes

2023-03-09 07:53 UTC, liang-cong-red-hat requested changes
I suggest adding log to get the hugepage number of each numa node. Then we could know how the hugepage is allocated.

2023-03-09 09:09 UTC, Yingshun approved these changes

2023-03-12 11:04 UTC, harihare approved these changes
LGTM

2023-03-13 01:40 UTC, liang-cong-red-hat approved these changes
LGTM

2023-03-13 01:53 UTC, merged