various_numa_topology_settings: add case
autotest/tp-libvirt pull request #4870
Opened 2023-04-29 09:51 UTC by dzhengfy

2023-04-29 10:23 UTC, dzhengfy commented
```
 (01/16) type_specific.io-github-autotest-libvirt.various_numa_topology_settings.discard_none.memaccess_none: ERROR: substring not found (64.62 s)
 (02/16) type_specific.io-github-autotest-libvirt.various_numa_topology_settings.discard_none.memaccess_shared: PASS (64.36 s)
 (03/16) type_specific.io-github-autotest-libvirt.various_numa_topology_settings.discard_none.memaccess_private: PASS (63.01 s)
 (04/16) type_specific.io-github-autotest-libvirt.various_numa_topology_settings.discard_none.memaccess_invalid: PASS (5.76 s)
 (05/16) type_specific.io-github-autotest-libvirt.various_numa_topology_settings.discard_yes.memaccess_none: PASS (63.90 s)
 (06/16) type_specific.io-github-autotest-libvirt.various_numa_topology_settings.discard_yes.memaccess_shared: PASS (65.70 s)
 (07/16) type_specific.io-github-autotest-libvirt.various_numa_topology_settings.discard_yes.memaccess_private: PASS (64.30 s)
 (08/16) type_specific.io-github-autotest-libvirt.various_numa_topology_settings.discard_yes.memaccess_invalid: PASS (5.74 s)
 (09/16) type_specific.io-github-autotest-libvirt.various_numa_topology_settings.discard_no.memaccess_none: PASS (67.59 s)
 (10/16) type_specific.io-github-autotest-libvirt.various_numa_topology_settings.discard_no.memaccess_shared: PASS (64.27 s)
 (11/16) type_specific.io-github-autotest-libvirt.various_numa_topology_settings.discard_no.memaccess_private: PASS (63.32 s)
 (12/16) type_specific.io-github-autotest-libvirt.various_numa_topology_settings.discard_no.memaccess_invalid: PASS (5.72 s)
 (13/16) type_specific.io-github-autotest-libvirt.various_numa_topology_settings.discard_invalid.memaccess_none: PASS (5.54 s)
 (14/16) type_specific.io-github-autotest-libvirt.various_numa_topology_settings.discard_invalid.memaccess_shared: PASS (5.46 s)
 (15/16) type_specific.io-github-autotest-libvirt.various_numa_topology_settings.discard_invalid.memaccess_private: PASS (5.55 s)
 (16/16) type_specific.io-github-autotest-libvirt.various_numa_topology_settings.discard_invalid.memaccess_invalid: PASS (5.41 s)

```

2023-05-04 09:37 UTC, dzhengfy commented
```
(01/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_none.memaccess_none: PASS (66.15 s)
 (02/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_none.memaccess_shared: PASS (66.63 s)
 (03/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_none.memaccess_private: PASS (66.08 s)
 (04/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_none.memaccess_invalid: PASS (6.03 s)
 (05/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_yes.memaccess_none: PASS (66.91 s)
 (06/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_yes.memaccess_shared: PASS (65.81 s)
 (07/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_yes.memaccess_private: PASS (67.30 s)
 (08/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_yes.memaccess_invalid: PASS (6.52 s)
 (09/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_no.memaccess_none: PASS (67.19 s)
 (10/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_no.memaccess_shared: PASS (65.01 s)
 (11/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_no.memaccess_private: PASS (66.86 s)
 (12/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_no.memaccess_invalid: PASS (6.34 s)
 (13/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_invalid.memaccess_none: PASS (6.67 s)
 (14/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_invalid.memaccess_shared: PASS (5.72 s)
 (15/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_invalid.memaccess_private: PASS (6.05 s)
 (16/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_invalid.memaccess_invalid: PASS (6.96 s)
RESULTS    : PASS 16 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/lib/avocado/job-results/job-2023-05-04T05.23-49f5a49/results.html
JOB TIME   : 643.16 s
```

2023-05-06 08:34 UTC, dzhengfy commented
@liang-cong-red-hat, could you help review?

2023-05-09 03:13 UTC, Yingshun commented on provider/numa/numa_base.py
> +class NumaTest(object):
Please generate docstring. thx!

2023-05-15 02:54 UTC, liang-cong-red-hat commented on provider/numa/numa_base.py
> +#   Author: Dan Zheng <chwen@redhat.com>
The email address should be modified.

2023-05-19 02:00 UTC, liang-cong-red-hat commented on libvirt/tests/cfg/numa/guest_numa_topology/various_numa_topology_settings.cfg
> +            numa_cells = [${numa_cell_0}, ${numa_cell_1}]
do you think move these parameters to common part could be better?:
numa_cell_0 = {'id': '0', 'memory': '1048576', 'cpus': '0-1'}
numa_cell_1 = {'id': '1', 'memory': '1048576', 'cpus': '2-3'}
numa_cells = [${numa_cell_0}, ${numa_cell_1}]
And I found memAccess = {'memAccess': 'xxxx'} is not used.

2023-05-19 02:06 UTC, liang-cong-red-hat commented on libvirt/tests/src/numa/guest_numa_topology/various_numa_topology_settings.py
> +    if not test_obj.vm.is_alive():
IMO, here the guest must be not alive, if so there should be some issues. So I think we don't have to check if it is alive.

2023-05-19 02:17 UTC, liang-cong-red-hat commented on libvirt/tests/src/numa/guest_numa_topology/various_numa_topology_settings.py
> +    utils_memory.set_num_huge_pages(int(test_obj.params.get('nr_hugepages')))
After setting the huge page memory, we could check whether the huge pages is set as our demand, since sometimes there could not be enough huge pages set.

2023-05-19 02:28 UTC, liang-cong-red-hat commented on libvirt/tests/src/numa/guest_numa_topology/various_numa_topology_settings.py
> +                           "but not found" % pattern_share_in_qmp_output)
the fail log seems suspicious:  Expect 'xxx' does exist, but not found

2023-05-19 02:38 UTC, liang-cong-red-hat commented on libvirt/tests/src/numa/guest_numa_topology/various_numa_topology_settings.py
> +        return
do you think we could add some comments about the reason of return.
And I am thinking whether there is other kind of solutions to separate the negative(or some tests with different steps) from positive, that might be clearer to the viewer.

2023-05-19 02:42 UTC, liang-cong-red-hat commented on provider/numa/numa_base.py
> +    def check_numa_nodes_availability(self, expect_nodes_num=2):
Do you think we could provide some functions for the scenario that if numa node 0, 1 don't contain enough memory we need, then the program could shift to other node with enough memory?

2023-05-19 03:37 UTC, liang-cong-red-hat requested changes
pls check my comments

2023-05-29 02:55 UTC, dzhengfy commented on libvirt/tests/cfg/numa/guest_numa_topology/various_numa_topology_settings.cfg
> +            numa_cells = [${numa_cell_0}, ${numa_cell_1}]
updated

2023-05-29 02:56 UTC, dzhengfy commented on libvirt/tests/src/numa/guest_numa_topology/various_numa_topology_settings.py
> +    utils_memory.set_num_huge_pages(int(test_obj.params.get('nr_hugepages')))
updated to use new function.

2023-05-29 03:13 UTC, dzhengfy commented on libvirt/tests/src/numa/guest_numa_topology/various_numa_topology_settings.py
> +    if not test_obj.vm.is_alive():
removed

2023-05-29 03:23 UTC, dzhengfy commented on provider/numa/numa_base.py
> +#   Author: Dan Zheng <chwen@redhat.com>
updated

2023-05-29 03:23 UTC, dzhengfy commented on provider/numa/numa_base.py
> +class NumaTest(object):
updated

2023-05-29 03:35 UTC, dzhengfy commented on libvirt/tests/src/numa/guest_numa_topology/various_numa_topology_settings.py
> +                           "but not found" % pattern_share_in_qmp_output)
updated

2023-05-29 03:39 UTC, dzhengfy commented on libvirt/tests/src/numa/guest_numa_topology/various_numa_topology_settings.py
> +        return
updated

2023-05-29 03:46 UTC, dzhengfy commented on provider/numa/numa_base.py
> +    def check_numa_nodes_availability(self, expect_nodes_num=2):
Good suggestion. I can improve it when the case needs.
But I also found there is already hugepage allocation verification in HugePageConfig.set_node_num_huge_pages().

2023-05-29 03:48 UTC, dzhengfy commented
```
# avocado run --vt
-type libvirt --test-runner=runner --vt-machine-type q35 guest_numa_topology.various_numa_topology_settings
JOB ID     : 2a466e9529a0f855cc6f1cef015c03dd7279f803
JOB LOG    : /var/lib/avocado/job-results/job-2023-05-28T22.40-2a466e9/job.log
 (01/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_none.memaccess_none: PASS (71.53 s)
 (02/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_none.memaccess_shared: PASS (68.92 s)
 (03/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_none.memaccess_private: PASS (67.93 s)
 (04/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_none.memaccess_invalid: PASS (9.31 s)
 (05/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_yes.memaccess_none: PASS (68.80 s)
 (06/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_yes.memaccess_shared: PASS (68.77 s)
 (07/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_yes.memaccess_private: PASS (69.05 s)
 (08/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_yes.memaccess_invalid: PASS (9.03 s)
 (09/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_no.memaccess_none: PASS (69.27 s)
 (10/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_no.memaccess_shared: PASS (69.01 s)
 (11/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_no.memaccess_private: PASS (68.87 s)
 (12/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_no.memaccess_invalid: PASS (9.16 s)
 (13/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_invalid.memaccess_none: PASS (9.37 s)
 (14/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_invalid.memaccess_shared: PASS (9.32 s)
 (15/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_invalid.memaccess_private: PASS (8.74 s)
 (16/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_invalid.memaccess_invalid: PASS (9.22 s)
RESULTS    : PASS 16 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/lib/avocado/job-results/job-2023-05-28T22.40-2a466e9/results.html
JOB TIME   : 687.44 s
```

2023-05-31 01:06 UTC, Yingshun approved these changes
LGTM

2023-05-31 01:40 UTC, liang-cong-red-hat approved these changes
LGTM

2023-05-31 01:43 UTC, merged