Exportfs command not found error fixing!
autotest/tp-libvirt pull request #5041
Opened 2023-07-19 09:45 UTC by Anushree-Mathur

Some tests require "exportfs" command which comes with the "nfs-utils" package so this patch will check if the nfs-utils package is installed else it will install that package, so the following error won't occur:

Error: Command 'exportfs' could not be found in any of the PATH dirs: ['/bin', '/root/.local/bin', '/root/bin', '/sbin', '/usr/bin', '/usr/libexec', '/usr/local/bin', '/usr/local/sbin', '/usr/sbin', '/usr/share/Modules/bin'] .
Signed-off-by :Anushree Mathur <anushree.mathur@linux.vnet.ibm.com>

2023-07-19 11:27 UTC, bskjois commented on libvirt/tests/src/virsh_cmd/domain/virsh_domblkerror.py
> +
Can we check negative scenario as well here? 
What if it is not able to install the package ?

2023-07-19 12:08 UTC, smitterl requested changes

2023-07-19 12:08 UTC, smitterl commented on libvirt/tests/src/virsh_cmd/domain/virsh_domblkerror.py
> +    # Install virt-top package if missing.
There is already function for this: https://github.com/avocado-framework/avocado-vt/blob/master/virttest/utils_package.py#L229

2023-07-19 13:49 UTC, Anushree-Mathur commented on libvirt/tests/src/virsh_cmd/domain/virsh_domblkerror.py
> +    # Install virt-top package if missing.
@smitterl Thanks for mentioning this. I will modify the patch using this function.

2023-07-20 09:47 UTC, Anushree-Mathur commented
@smitterl I have modified the patch!

2023-07-20 09:48 UTC, Anushree-Mathur commented on libvirt/tests/src/virsh_cmd/domain/virsh_domblkerror.py
> +
@bskjois In the modified patch i mentioned if the nfs-utils packages can't be installed it will give message!

2023-07-20 17:51 UTC, bskjois approved these changes
LGTM

2023-07-24 03:57 UTC, Anushree-Mathur commented
@chunfuwen @dzhengfy : Can you review and help me in merging this PR!

2023-07-24 05:36 UTC, chunfuwen commented on libvirt/tests/src/virsh_cmd/domain/virsh_domblkerror.py
> +
there are some suggestions or common practices here
 we are not handling package install or uinstall in upstream code since it impact underlying system under testing if we do.
an alternative way is to install those packages in downstream CI

2023-07-24 08:26 UTC, Anushree-Mathur commented on libvirt/tests/src/virsh_cmd/domain/virsh_domblkerror.py
> +    if not package_install("nfs-utils"):
@chunfuwen I have seen this package installation policy in tp-libvirt code at many places. Is this something new change that have been introduced !

2023-07-25 03:00 UTC, chunfuwen commented on libvirt/tests/src/virsh_cmd/domain/virsh_domblkerror.py
> +    if not package_install("nfs-utils"):
@Anushree-Mathur previously there is package installation policy at many places in tp-libvirt. In practices, we learned some lessons, e.g package install conflict during calling software install, and suggestions from other upstream projects, so we don't suggest install sw in tp-libvirt code

2023-09-12 20:15 UTC, closed without merging