Fixed a wrong if condition
autotest/tp-libvirt pull request #5044
Opened 2023-07-20 17:38 UTC by bskjois

Signed-off-by: Kowshik Jois B S <kowsjois@linux.ibm.com>

Description:
- Here the test needs either of the packages to be installed.
- Since there is 'not' in the 'if' condition, it should have 'and' instead of 'or'.
- With the current code, it keeps looking for first one and prints the error message.
- It will never look at the second as first 'True' condition is sufficient for OR.

2023-07-21 09:16 UTC, Anushree-Mathur commented
LGTM!

2023-07-21 09:29 UTC, Anushree-Mathur approved these changes

2023-07-21 11:30 UTC, harihare commented
it should be OR condition only. as per the message from the package.

2023-07-21 11:31 UTC, harihare requested changes
Let us drop this patch

2023-07-21 12:08 UTC, harihare approved these changes

2023-07-21 17:53 UTC, bskjois commented
@chunfuwen , @dzhengfy Could you please help me merging this patch as 2 LGTM has been labled.

2023-07-24 03:40 UTC, chunfuwen approved these changes
lgtm

2023-07-24 03:41 UTC, merged