External snapshot deletion failure modification!
autotest/tp-libvirt pull request #5177
Opened 2023-09-12 20:21 UTC by Anushree-Mathur

In libvirt version lesser than 9.0.0 external snapshot deletion was unsupported, but the testcase is failing now with the error message as "Snapshot delete succeed but expect fail" because the deletion is supported now with external disk.
For reference : https://libvirt.org/news.html#v9-0-0-2023-01-16
Signed-off-by: Anushree Mathur <anushree.mathur@linux.vnet.ibm.com>

2023-09-12 20:24 UTC, Anushree-Mathur commented
LOGS for Testcase runs:
Before patch
```
 (2/4) type_specific.io-github-autotest-libvirt.virsh.snapshot_disk.delete_test.negative_test.no_pool.attach_img_qcow2.snapshot_from_xml.disk_external.sys_checkpoint.default.memory_external: STARTED
 (2/4) type_specific.io-github-autotest-libvirt.virsh.snapshot_disk.delete_test.negative_test.no_pool.attach_img_qcow2.snapshot_from_xml.disk_external.sys_checkpoint.default.memory_external: FAIL: Snapshot delete succeed but expect fail. (106.01 s)
```
After Patch :

``` (2/4) type_specific.io-github-autotest-libvirt.virsh.snapshot_disk.delete_test.negative_test.no_pool.attach_img_qcow2.snapshot_from_xml.disk_external.sys_checkpoint.default.memory_external: STARTED
 (2/4) type_specific.io-github-autotest-libvirt.virsh.snapshot_disk.delete_test.negative_test.no_pool.attach_img_qcow2.snapshot_from_xml.disk_external.sys_checkpoint.default.memory_external: PASS (87.28 s)
```

2023-09-13 06:45 UTC, sacsant requested changes

2023-09-13 06:45 UTC, sacsant commented on libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_disk.py
> +                    if (not libvirt_version.version_compare(9, 0, 0)) and status_error:
Will this check also work for libvirt 9.1.0? Can we make it generic?

if libvirt_version < 9.0.0 and status error
   fail(...)

2023-09-13 06:49 UTC, Anushree-Mathur commented on libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_disk.py
> +                    if (not libvirt_version.version_compare(9, 0, 0)) and status_error:
@sacsant It will work for all the libvirt_version because the version compare will take the libvirt version and then check whether it is greater than to the specified libvirt version or not then will return true or false accordingly!

2023-09-13 08:41 UTC, bskjois approved these changes
LGTM

2023-09-20 04:52 UTC, Anushree-Mathur commented
@chunfuwen @dzhengfy Could you review this PR!

2023-09-27 06:02 UTC, Anushree-Mathur commented
@chunfuwen @dzhengfy Could you review this PR! 
Thanks in advance!

2023-11-04 05:42 UTC, Anushree-Mathur commented
@Yingshun @luckyh @yalzhang @chunfuwen @dzhengfy Could you review and merge this PR!
Thanks in advance!

2023-11-08 11:14 UTC, Anushree-Mathur commented
@Yingshun @luckyh @yalzhang @chunfuwen @dzhengfy Could you review and merge this PR! I have already got 2 LGTMs
Thanks in advance!

2023-12-13 03:55 UTC, Anushree-Mathur commented
@Yingshun @luckyh @yalzhang @chunfuwen @dzhengfy Could you review and merge this PR! I have already got 2 LGTMs
Thanks in advance!

2023-12-18 06:28 UTC, qiankehan commented
A notification for libvirt external snapshot deletion: there is an issue with deleting the external snapshot with multiple children snapshots: https://gitlab.com/libvirt/libvirt/-/issues/534. It is fixed in libvirt v9.10.0

2023-12-18 07:32 UTC, yalzhang approved these changes
no impact for downstream testing since we have added it into skiplist

2024-01-11 03:39 UTC, chunfuwen approved these changes
lgtm

2024-01-11 03:39 UTC, merged