Fix the pid path issue
autotest/tp-libvirt pull request #5211
Opened 2023-09-28 11:16 UTC by bskjois

Signed-off-by: Kowshik Jois B S <kowsjois@linux.ibm.com>

This is an enhancement of the PR #2807

The path in the config file got changed again from libvirt version 8.6.0. Added changes to look for the path accordingly.

2023-09-28 11:20 UTC, bskjois commented
**Logs before the fix:** 

 (2/9) type_specific.io-github-autotest-libvirt.virtual_network.iface_network.dnsmasq_test.net_dns_forward: FAIL: Can't find pid-file=/run/libvirt/network/default.pid in configuration file (11.38 s)
 (3/9) type_specific.io-github-autotest-libvirt.virtual_network.iface_network.dnsmasq_test.net_domain: FAIL: Can't find pid-file=/run/libvirt/network/default.pid in configuration file (11.48 s)
 (4/9) type_specific.io-github-autotest-libvirt.virtual_network.iface_network.dnsmasq_test.net_netmask: FAIL: Can't find pid-file=/run/libvirt/network/default.pid in configuration file (11.43 s)
 (5/9) type_specific.io-github-autotest-libvirt.virtual_network.iface_network.dnsmasq_test.net_forwarder_full: FAIL: Can't find pid-file=/run/libvirt/network/default.pid in configuration file (11.47 s)
 (6/9) type_specific.io-github-autotest-libvirt.virtual_network.iface_network.dnsmasq_test.net_forwarder_domain: FAIL: Can't find pid-file=/run/libvirt/network/default.pid in configuration file (11.43 s)
 (7/9) type_specific.io-github-autotest-libvirt.virtual_network.iface_network.dnsmasq_test.net_forwarder_mix: FAIL: Can't find pid-file=/run/libvirt/network/default.pid in configuration file (12.10 s)
 (8/9) type_specific.io-github-autotest-libvirt.virtual_network.iface_network.dnsmasq_test.disable_dns: FAIL: Can't find pid-file=/run/libvirt/network/default.pid in configuration file (11.60 s)


**Logs after the fix:**

 (2/9) type_specific.io-github-autotest-libvirt.virtual_network.iface_network.dnsmasq_test.net_dns_forward: PASS (37.11 s)
 (3/9) type_specific.io-github-autotest-libvirt.virtual_network.iface_network.dnsmasq_test.net_domain: PASS (36.87 s)
 (4/9) type_specific.io-github-autotest-libvirt.virtual_network.iface_network.dnsmasq_test.net_netmask: PASS (36.67 s)
 (5/9) type_specific.io-github-autotest-libvirt.virtual_network.iface_network.dnsmasq_test.net_forwarder_full: PASS (39.52 s)
 (6/9) type_specific.io-github-autotest-libvirt.virtual_network.iface_network.dnsmasq_test.net_forwarder_domain: PASS (37.02 s)
 (7/9) type_specific.io-github-autotest-libvirt.virtual_network.iface_network.dnsmasq_test.net_forwarder_mix: PASS (34.25 s)
 (8/9) type_specific.io-github-autotest-libvirt.virtual_network.iface_network.dnsmasq_test.disable_dns: PASS (35.32 s)

2023-09-28 11:22 UTC, bskjois commented
@yalzhang This is an enahncement of your old PR 2807. Could you please take a look

2023-09-29 10:53 UTC, Anushree-Mathur approved these changes
LGTM!

2023-09-29 12:54 UTC, yalzhang approved these changes
LGTM

2023-09-29 13:24 UTC, bskjois commented
@chunfuwen , @dzhengfy May I request you to review and merge this PR as 2 LGTMs has already been labled.

2023-09-29 18:02 UTC, harihare approved these changes
LGTM

2023-10-06 15:02 UTC, bskjois commented
@chunfuwen , @dzhengfy Could you please help me merge this PR as 3 LGTMs have already been labled.

2023-10-07 01:18 UTC, yalzhang commented
> @chunfuwen , @dzhengfy Could you please help me merge this PR as 3 LGTMs have already been labled.
Please hold on, since I found the current result is pass in our auto job, not sure about the root cause. I'm checking and will update later.

2023-10-07 05:07 UTC, yalzhang commented
> The path in the config file got changed again from libvirt version 8.6.0.
Hi @bskjois  Could you please help to provide more information about it? since I have checked on libvirt-9.5.0, the file path doesn't change:
# ll /run/libvirt/network/default.pid
-rw-r--r--. 1 dnsmasq dnsmasq 6 Oct  6 23:09 /run/libvirt/network/default.pid

2023-10-09 18:58 UTC, bskjois commented
@yalzhang with any libvirt version we could see both the paths available.
```
[root@localhost ~]# ll /var/run/libvirt/network/default.pid
-rw-r--r-- 1 dnsmasq dnsmasq 6 Sep 26 16:06 /var/run/libvirt/network/default.pid

[root@localhost ~]# ll /run/libvirt/network/default.pid
-rw-r--r-- 1 dnsmasq dnsmasq 6 Sep 26 16:06 /run/libvirt/network/default.pid

[root@localhost ~]# libvirtd --version
libvirtd (libvirt) 9.8.0
```

But, the path for the pid file inside the config file(/var/lib/libvirt/dnsmasq/default.conf) has changed. Hence we need to fix the test case accordingly. 
```
[root@localhost ~]# cat /var/lib/libvirt/dnsmasq/default.conf | grep pid
pid-file=/var/run/libvirt/network/default.pid
```

The path inside the config file was /var/run/libvirt/network/default.pid earlier and from libvirt version 6.0.0 it got changed to /run/libvirt/network/default.pid and Hence you had given the fix here: #2807 

Now, again the path in the config file got changed back to  /var/run/libvirt/network/default.pid. So, I have given a similar fix in the current PR.

2023-10-10 01:33 UTC, yalzhang approved these changes
Thank you for the detailed info.
But I got:
`[root@localhost ~]# virsh -v 
9.5.0
[root@localhost ~]# cat /var/lib/libvirt/dnsmasq/default.conf | grep pid
pid-file=/run/libvirt/network/default.pid`

2023-10-10 05:44 UTC, yalzhang commented
@bskjois   We have checked the libvirt code, the pid path depends on the parameter "RUNSTATEDIR". We use the downstream build rpm packages. So the pid path did not change. Could you please help to check the RUNSTATEDIR when you build the packages? (BTW, with this update, our test case for downstream libvirt will fail)
```
97     if (privileged) {
 98         configdir = g_strdup(SYSCONFDIR "/libvirt");
 99         cfg->networkConfigDir = g_strdup(SYSCONFDIR "/libvirt/qemu/networks");
100         cfg->networkAutostartDir = g_strdup(SYSCONFDIR "/libvirt/qemu/networks/autostart");
101         cfg->stateDir = g_strdup(RUNSTATEDIR "/libvirt/network");
102         cfg->pidDir = g_strdup(RUNSTATEDIR "/libvirt/network");
```

2023-10-10 06:25 UTC, yalzhang requested changes
Since it the path depens on rpm build parameters, and the parameter may be different. So this PR is not suitable for our tests(it will fail with this change). Please check it and hold on. Thank you!

2023-10-10 12:13 UTC, bskjois commented
@yalzhang you had rightly pointed it out. Thank you so much. 
I also checked with libvirt version 9.5.0. In upstream version it is, /var/run/libvirt/network/default.pid and in downstream version it is /run/libvirt/network/default.pid

```
Upstream:
[root@localhost32 libvirt]# virsh -v
9.5.0
[root@localhost32 libvirt]# cat /var/lib/libvirt/dnsmasq/default.conf | grep pid
pid-file=/var/run/libvirt/network/default.pid

Downstream:
[root@localhost39 ~]# virsh -v
9.5.0
[root@localhost39 ~]# cat /var/lib/libvirt/dnsmasq/default.conf | grep pid
pid-file=/run/libvirt/network/default.pid
```

In both the cases, I could see that, both the paths are available with the same content.

```
Upstream:
[root@localhost32 libvirt]# cat /var/run/libvirt/network/default.pid
8567
[root@localhost32 libvirt]# cat /run/libvirt/network/default.pid
8567

Downstream:
[root@localhost39 ~]# cat /var/run/libvirt/network/default.pid
38435
[root@localhost39 ~]# cat /run/libvirt/network/default.pid
38435
```

Could you please suggest how can we go about this? What is the better approach? I have below thoughts in mind.

1. Modify the code accordingly so that it should work in case of both the paths
2. Look for the path of the file instead of looking at what is inside the config file
3. Leave it as is to make it work only with downstream rpm packages installed

2023-10-12 01:36 UTC, yalzhang commented
@bskjois  Since this check point is not a critical one for the function, I think it's okay to go with option 1: Modify the code accordingly so that it should work in case of both the paths. Maybe we can consider it fail only when both of the 2 path check fail.

2023-10-12 08:52 UTC, yalzhang commented
@bskjois   I have pushed https://github.com/autotest/tp-libvirt/pull/5223 to fix this issue.  Could you please help to review? or run in your env to check if it fix the problem. Thank you!

2023-10-30 09:24 UTC, bskjois commented
I am closing this PR as the issue would get fixed with @yalzhang's new PR #5223

2023-10-30 09:24 UTC, closed without merging