add case for file backed nvdimm memory lifecycle
autotest/tp-libvirt pull request #5370
Opened 2023-12-29 02:23 UTC by nanli1

VIRT-299192: Life cycle of file backed nvdimm memory device
Signed-off-by: nanli <nanli@redhat.com>

2024-01-13 09:08 UTC, smitterl requested changes
Thanks for this. Some minor things called my attention please have a look.

2024-01-17 10:45 UTC, nanli1 commented on libvirt/tests/src/memory/memory_devices/lifecycle_for_file_backed_nvdimm_memory.py
> +        1.Define vm with nvdimm memory device and check nvdimm config.
Thanks Sebas,  Done

2024-01-17 11:08 UTC, nanli1 commented on libvirt/tests/src/memory/memory_devices/lifecycle_for_file_backed_nvdimm_memory.py
> +        os.remove(save_file)
Hi Sebas , Thanks for your comment. If other cases have the same named file left, m which will influence my test

2024-03-01 08:49 UTC, smitterl approved these changes
LGTM thank you!

2024-03-06 08:40 UTC, dzhengfy approved these changes
LGTM

2024-03-06 08:42 UTC, merged