Ingnore scm devices on S390
autotest/tp-libvirt pull request #5380
Opened 2024-01-08 03:31 UTC by liang-cong-red-hat

Scm devices are only used in combination with z/OS.
Test result:
JOB ID     : eb5c2c18968651ed63b78547cc593b730cfa5251
JOB LOG    : /var/lib/avocado/job-results/job-2024-01-07T22.27-eb5c2c1/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virsh.nodedev_list.valid_option.non_acl.one_cap_option: PASS (5.18 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/lib/avocado/job-results/job-2024-01-07T22.27-eb5c2c1/results.html
JOB TIME   : 5.51 s

2024-01-08 08:52 UTC, smitterl commented
@liang-cong-red-hat Please squash your commits. Rest LGTM Thank you!

2024-01-08 08:54 UTC, smitterl requested changes
@liang-cong-red-hat Please squash your commits. Rest LGTM Thank you!

2024-01-08 09:11 UTC, liang-cong-red-hat commented
> @liang-cong-red-hat Please squash your commits. Rest LGTM Thank you!

done

2024-01-16 07:11 UTC, chunfuwen approved these changes
lgtm

2024-01-25 02:03 UTC, merged