Fix io_uring failure
autotest/tp-libvirt pull request #5403
Opened 2024-01-24 03:27 UTC by chunfuwen

queue_size in driver is not supported

2024-01-24 03:35 UTC, chunfuwen commented
Failed log:

2024-01-18 14:46:08,764 stacktrace       L0045 ERROR|     run_test_case(test, params, env)
2024-01-18 14:46:08,764 stacktrace       L0045 ERROR|   File "/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-libvirt/libvirt/tests/src/virtual_disks/virtual_disks_io_tuning.py", line 87, in test_coldplug_io_uring_normal_start
2024-01-18 14:46:08,764 stacktrace       L0045 ERROR|     virsh.attach_device(vm_name, device_obj.xml, flagstr="--config",
2024-01-18 14:46:08,764 stacktrace       L0045 ERROR|   File "/var/ci/libvirt-ci/runtest/avocado-vt/avocado-vt/virttest/virsh.py", line 1782, in attach_device
2024-01-18 14:46:08,764 stacktrace       L0045 ERROR|     return _adu_device("attach-device", domainarg=domainarg, filearg=filearg,
2024-01-18 14:46:08,764 stacktrace       L0045 ERROR|   File "/var/ci/libvirt-ci/runtest/avocado-vt/avocado-vt/virttest/virsh.py", line 1765, in _adu_device
2024-01-18 14:46:08,764 stacktrace       L0045 ERROR|     return command(cmd, **dargs)
2024-01-18 14:46:08,764 stacktrace       L0045 ERROR|   File "/var/ci/libvirt-ci/runtest/avocado-vt/avocado-vt/virttest/virsh.py", line 820, in command
2024-01-18 14:46:08,764 stacktrace       L0045 ERROR|     ret = process.run(cmd, timeout=timeout, verbose=debug,
2024-01-18 14:46:08,764 stacktrace       L0045 ERROR|   File "/var/ci/libvirt-ci/runtest/avocado-vt/avocado/avocado/utils/process.py", line 1093, in run
2024-01-18 14:46:08,764 stacktrace       L0045 ERROR|     raise CmdError(cmd, sp.result)
2024-01-18 14:46:08,764 stacktrace       L0045 ERROR| avocado.utils.process.CmdError: Command '/bin/virsh attach-device avocado-vt-vm1 /tmp/xml_utils_temp_s7pygv32.xml --config' failed.
2024-01-18 14:46:08,764 stacktrace       L0045 ERROR| stdout: b'\n'
2024-01-18 14:46:08,764 stacktrace       L0045 ERROR| stderr: b'error: Failed to attach device from /tmp/xml_utils_temp_s7pygv32.xml\nerror: unsupported configuration: queue_size attribute in disk driver

2024-01-24 06:57 UTC, cliping approved these changes
LGTM

2024-01-24 08:16 UTC, chunfuwen commented
Command 'virsh list' finished with 0 after 0.034083162s
DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
PASS 1-type_specific.io-github-autotest-libvirt.virtual_disks.io_tuning.hotplug.io_uring.normal_start

2024-01-24 08:34 UTC, smitterl commented on libvirt/tests/cfg/virtual_disks/virtual_disks_io_tuning.cfg
> +                    driver_attribute = {'name': "qemu", 'type': "qcow2", 'io': 'io_uring'}
I can start a VM successfully with
```
<driver name='qemu' type='qcow2' queue_size='1024'/>
```
and `libvirt-10.0.0`

2024-02-06 02:21 UTC, chunfuwen commented on libvirt/tests/cfg/virtual_disks/virtual_disks_io_tuning.cfg
> +                    driver_attribute = {'name': "qemu", 'type': "qcow2", 'io': 'io_uring'}
you miss 'io': 'io_uring' parameter, if adding this parameter ,it will raise issue

2024-02-16 09:51 UTC, smitterl commented on libvirt/tests/cfg/virtual_disks/virtual_disks_io_tuning.cfg
> +                    driver_attribute = {'name': "qemu", 'type': "qcow2", 'io': 'io_uring'}
@chunfuwen I forgot to add that in my comment you are right. But in any case it still works with io_uring:

The VM starts for me with
```
 -blockdev {"driver":"file","filename":"/var/lib/avocado/data/avocado-vt/images/jeos-27-s390x.qcow2","aio":"io_uring","node-name":"libvirt-1-storage","auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-1-format","read-only":false,"driver":"qcow2","file":"libvirt-1-storage","backing":null} -device {"driver":"virtio-blk-ccw","queue-size":1024,"devno":"fe.0.0000","drive":"libvirt-1-format","id":"virtio-disk0","bootindex":1} ```

I had a look at the original issue, the error says "unsupported configuration: queue_size attribute in disk driver is only supported for virtio bus". Actually, the test case tries to use 'scsi':

```
<disk type="file" device="disk"><target dev="sdb" bus="scsi" /><driver name="qemu" type="qcow2" queue_size="1024" io="io_uring" /><source file="/var/lib/libvirt/images/io_uring.qcow2" /></disk>```

And yes, with that I can see that error message.

2024-02-16 09:53 UTC, smitterl requested changes
Please check my comment.

2024-02-19 05:31 UTC, chunfuwen commented on libvirt/tests/cfg/virtual_disks/virtual_disks_io_tuning.cfg
> +                    driver_attribute = {'name': "qemu", 'type': "qcow2", 'io': 'io_uring'}
queue_size is supported only virto, which is latest change. Previously It is support on both virto and scsi. That is why we have this case. So this fix is to remove queue_size from scsi. 
But more further task is to add virtio case related to io_uring

2024-02-19 16:04 UTC, smitterl commented on libvirt/tests/cfg/virtual_disks/virtual_disks_io_tuning.cfg
> +                    driver_attribute = {'name': "qemu", 'type': "qcow2", 'io': 'io_uring'}
@chunfuwen I understand it now. Thank you for explaining.

2024-02-19 16:05 UTC, smitterl approved these changes
LGTM

2024-03-06 03:34 UTC, dzhengfy approved these changes
LGTM.
A reminder is to rename this case to reflect the scsi bus later.

2024-03-06 03:35 UTC, merged