Filter CCW address cases on q35
autotest/tp-libvirt pull request #5404
Opened 2024-01-24 04:50 UTC by chunfuwen

can not use CCW address type for device on q35

2024-01-24 04:51 UTC, chunfuwen commented
Failed log:

[Changes](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/libvirt-RHEL-9.4-runtest-x86_64-function-virtual_disk/5/changes)
[Console Output](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/libvirt-RHEL-9.4-runtest-x86_64-function-virtual_disk/5/console)
[View as plain text](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/libvirt-RHEL-9.4-runtest-x86_64-function-virtual_disk/5/consoleText)
[Edit Build Information](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/libvirt-RHEL-9.4-runtest-x86_64-function-virtual_disk/5/configure)

[History](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/libvirt-RHEL-9.4-runtest-x86_64-function-virtual_disk/5/testReport/history)
[Parameters](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/libvirt-RHEL-9.4-runtest-x86_64-function-virtual_disk/5/parameters)
[Timings](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/libvirt-RHEL-9.4-runtest-x86_64-function-virtual_disk/5/timings)

[Environment Variables](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/libvirt-RHEL-9.4-runtest-x86_64-function-virtual_disk/5/injectedEnvVars)
[Test Result](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/libvirt-RHEL-9.4-runtest-x86_64-function-virtual_disk/5/testReport)
[Rebuild](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/libvirt-RHEL-9.4-runtest-x86_64-function-virtual_disk/5/rebuild/parameterized)

[Open Blue Ocean](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/libvirt-RHEL-9.4-runtest-x86_64-function-virtual_disk/detail/libvirt-RHEL-9.4-runtest-x86_64-function-virtual_disk/5/)
[Previous Build](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/libvirt-RHEL-9.4-runtest-x86_64-function-virtual_disk/4/testReport/)
[Next Build](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/libvirt-RHEL-9.4-runtest-x86_64-function-virtual_disk/6/testReport/)
Test Result
9 failures (-1) , 138 skipped (±0)
557 tests (±0)
[Took 6 hr 50 min.](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/libvirt-RHEL-9.4-runtest-x86_64-function-virtual_disk/5/testReport/history)
[Add description](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/libvirt-RHEL-9.4-runtest-x86_64-function-virtual_disk/5/testReport/editDescription)
All Failed Tests
[Test Name](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/libvirt-RHEL-9.4-runtest-x86_64-function-virtual_disk/5/testReport/#)
[Duration](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/libvirt-RHEL-9.4-runtest-x86_64-function-virtual_disk/5/testReport/#)
[Age](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/libvirt-RHEL-9.4-runtest-x86_64-function-virtual_disk/5/testReport/#)
 [rhel.virtual_disks.io_tuning.coldplug.io_uring.normal_start](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/libvirt-RHEL-9.4-runtest-x86_64-function-virtual_disk/5/testReport/rhel/virtual_disks/io_tuning_coldplug_io_uring_normal_start/)	7.9 sec	[2](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/libvirt-RHEL-9.4-runtest-x86_64-function-virtual_disk/4/)
 [rhel.virtual_disks.io_tuning.hotplug.io_uring.normal_start](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/libvirt-RHEL-9.4-runtest-x86_64-function-virtual_disk/5/testReport/rhel/virtual_disks/io_tuning_hotplug_io_uring_normal_start/)	41 sec	[2](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/libvirt-RHEL-9.4-runtest-x86_64-function-virtual_disk/4/)
 [rhel.virtual_disks.ccw_addr.hotplug.attach_disk.negative_test.start_vm](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/libvirt-RHEL-9.4-runtest-x86_64-function-virtual_disk/5/testReport/rhel/virtual_disks/ccw_addr_hotplug_attach_disk_negative_test_start_vm/)
[ Error Details](javascript:hideFailureSummary('id9778-error'))
TestFail: unexpected exception happen: Expect should fail with one of ['cannot use CCW address type for device'], but failed with:error: Failed to attach device from /tmp/xml_utils_temp_i8ck6bfp.xmlerror: unsupported configuration: CCW addresses are not supported by machine type 'pc-q35-rhel9.4.0'&#10;
[ Standard Output](javascript:hideFailureSummary('id9778-stdout'))
2024-01-18 14:47:00,200 sysinfo          L0034 INFO | Commands configured by file: /var/ci/libvirt-ci/runtest/avocado-vt/avocado/avocado/etc/avocado/sysinfo/commands
2024-01-18 14:47:00,200 sysinfo          L0034 INFO | Files configured by file: /var/ci/libvirt-ci/runtest/avocado-vt/avocado/avocado/etc/avocado/sysinfo/files
2024-01-18 14:47:00,200 sysinfo          L0038 DEBUG| File /var/ci/libvirt-ci/runtest/avocado-vt/avocado/avocado/etc/avocado/sysinfo/fail_commands does not exist.
2024-01-18 14:47:00,200 sysinfo          L0038 DEBUG| File /var/ci/libvirt-ci/runtest/avocado-vt/avocado/avocado/etc/avocado/sysinfo/fail_files does not exist.
2024-01-18 14:47:00,200 sysinfo          L0109 INFO | Profilers configured by file: /var/ci/libvirt-ci/runtest/avocado-vt/avocado/avocado/etc/avocado/sysinfo/profilers
2024-01-18 14:47:00,200 sysinfo          L0118 INFO | Profiler disabled
2024-01-18 14:47:00,210 sysinfo          L0199 DEBUG| Not logging /sys/kernel/debug/sched_features (file not found)
2024-01-18 14:47:00,315 sysinfo          L0199 DEBUG| Not logging /proc/pci (file not found)
2024-01-18 14:47:00,522 job              L0289 INFO | Command line: /usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 virtual_disks.ccw_addr.hotplug.attach_disk.negative_test.start_vm --vt-connect-uri qemu:///system
2024-01-18 14:47:00,522 job              L0290 INFO | 
2024-01-18 14:47:00,527 job              L0283 INFO | Avocado version: 92.1 (GIT commit 1159721c)
2024-01-18 14:47:00,527 job              L0284 INFO | 
2024-01-18 14:47:00,527 job              L0262 INFO | Avocado config:
2024-01-18 14:47:00,527 job              L0263 INFO | 
2024-01-18 14:47:00,529 job              L0265 INFO | {'assets.fetch.ignore_errors': False,
2024-01-18 14:47:00,529 job              L0265 INFO |  'assets.fetch.references': [],
2024-01-18 14:47:00,529 job              L0265 INFO |  'assets.fetch.timeout': 300,
2024-01-18 14:47:00,529 job              L0265 INFO |  'assets.list.days': None,
2024-01-18 14:47:00,529 job              L0265 INFO |  'assets.list.overall_limit': None,
2024-01-18 14:47:00,529 job              L0265 INFO |  'assets.list.size_filter': None,
2024-01-18 14:47:00,529 job              L0265 INFO |  'assets.purge.days': None,
2024-01-18 14:47:00,529 job              L0265 INFO |  'assets.purge.overall_limit': None,
2024-01-18 14:47:00,529 job              L0265 INFO |  'assets.purge.size_filter': None,
2024-01-18 14:47:00,529 job              L0265 INFO |  'assets.register.name': None,
2024-01-18 14:47:00,529 job              L0265 INFO |  'assets.register.sha1_hash': None,
2024-01-18 14:47:00,529 job              L0265 INFO |  'assets.register.url': None,
2024-01-18 14:47:00,529 job              L0265 INFO |  'config': None,
2024-01-18 14:47:00,529 job              L0265 INFO |  'config.datadir': False,
2024-01-18 14:47:00,529 job              L0265 INFO |  'core.input_encoding': 'utf-8',
2024-01-18 14:47:00,529 job              L0265 INFO |  'core.paginator': False,
2024-01-18 14:47:00,529 job              L0265 INFO |  'core.show': {'app'},
2024-01-18 14:47:00,529 job              L0265 INFO |  'core.verbose': False,
2024-01-18 14:47:00,529 job              L0265 INFO |  'datadir.paths.base_dir': '/var/lib/avocado',
2024-01-18 14:47:00,529 job              L0265 INFO |  'datadir.paths.cache_dirs': ['/root/avocado/data/cache'],
2024-01-18 14:47:00,529 job              L0265 INFO |  'datadir.paths.data_dir': '/var/lib/avocado/data',
2024-01-18 14:47:00,529 job              L0265 INFO |  'datadir.paths.logs_dir': '/var/lib/avocado/job-results',
2024-01-18 14:47:00,529 job              L0265 INFO |  'datadir.paths.test_dir': '/usr/share/doc/avocado/tes [...]

2024-01-24 08:22 UTC, smitterl requested changes
Please check my comment, thank you

2024-01-24 08:22 UTC, smitterl commented on libvirt/tests/cfg/virtual_disks/virtual_disks_ccw_addr.cfg
> +    no s390-virtio q35
You're missing a comma ','. Anyway, why is s390-virtio filtered out? CCW are s390-virtio only. Maybe the original intention was to have 'only s390-virtio' instead?

2024-01-28 09:21 UTC, dzhengfy commented on libvirt/tests/cfg/virtual_disks/virtual_disks_ccw_addr.cfg
> +    no s390-virtio q35
There should be a typo, I think.
We need `only s390-virtio`.

2024-02-06 02:39 UTC, chunfuwen commented on libvirt/tests/cfg/virtual_disks/virtual_disks_ccw_addr.cfg
> +    no s390-virtio q35
changed to only s390-virtio

2024-02-19 08:15 UTC, meinaLi commented
@chunfuwen The recommend update:
```
           error_msg = "cannot use CCW address type for device | CCW addresses are not supported by machine type"
```
We can't changed it to "only s390-virtio". Because this is a negative test in "no s390-virtio". Now we have a more clear error message for it. So it caused this error.

2024-02-26 01:58 UTC, chunfuwen commented
> @chunfuwen The recommend update:
> 
> ```
>            error_msg = "cannot use CCW address type for device | CCW addresses are not supported by machine type"
> ```
> 
> We can't changed it to "only s390-virtio". Because this is a negative test in "no s390-virtio". Now we have a more clear error message for it. So it caused this error.

@meinaLi 
only s390-virtio will filter out whole test suite including positive and negative.
I believe in some technology doc, ccw is clearly explained that it is applied only in s390x, so it is not necessary to have negative case with x86_64, arm.

2024-02-26 02:16 UTC, meinaLi commented
> @meinaLi only s390-virtio will filter out whole test suite including positive and negative. I believe in some technology doc, ccw is clearly explained that it is applied only in s390x, so it is not necessary to have negative case with x86_64, arm.

@chunfuwen Yes, it's only applied in s390x. But because we have this negative case in x86, so this auto case has been added before. Any way, we can't change it to "only s390-virtio" here because it's not a negative case for x390x and we can't get the expected error msg. I suggest that we update the error message to match the manual case now. We can consider moving this negative case with x86_64, arm only when we restructure the virtual disk test plan next time.

2024-02-28 06:56 UTC, meinaLi commented
Through discussion, this case can be removed from the perspective of Libvirt x86 by adding 'only s390-virtio'.

2024-02-28 06:57 UTC, meinaLi approved these changes

2024-03-05 02:38 UTC, dzhengfy approved these changes
LGTM

2024-03-05 02:38 UTC, merged