add case for dimm with memory allocation and numa
autotest/tp-libvirt pull request #5464
Opened 2024-02-22 07:54 UTC by nanli1

xxxx-299047: Dimm memory with various memory allocation and guest numa settings
Signed-off-by: nanli <nanli@redhat.com>

Rhel9.4+x86
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 dimm.memory_allocation_and_numa
 (1/6) type_specific.io-github-autotest-libvirt.memory.devices.dimm.memory_allocation_and_numa.no_numa.no_maxmemory: PASS (47.80 s)
 (2/6) type_specific.io-github-autotest-libvirt.memory.devices.dimm.memory_allocation_and_numa.no_numa.no_slot: PASS (41.13 s)
 (3/6) type_specific.io-github-autotest-libvirt.memory.devices.dimm.memory_allocation_and_numa.no_numa.with_slot: PASS (67.06 s)
 (4/6) type_specific.io-github-autotest-libvirt.memory.devices.dimm.memory_allocation_and_numa.with_numa.no_maxmemory: PASS (41.16 s)
 (5/6) type_specific.io-github-autotest-libvirt.memory.devices.dimm.memory_allocation_and_numa.with_numa.no_slot: PASS (41.30 s)
 (6/6) type_specific.io-github-autotest-libvirt.memory.devices.dimm.memory_allocation_and_numa.with_numa.with_slot: PASS (41.21 s)

```

2024-03-28 08:03 UTC, Yingshun commented
> ```
> xxxx-299047: Dimm memory with various memory allocation and guest numa settings
> ```
> 
> Signed-off-by: nanli [nanli@redhat.com](mailto:nanli@redhat.com)
> 
> Rhel9.4+x86 , rhel8+x86(TBD)
> 
> ```
> avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 dimm.memory_allocation_and_numa
>  (1/6) type_specific.io-github-autotest-libvirt.memory.devices.dimm.memory_allocation_and_numa.no_numa.no_maxmemory: PASS (47.80 s)
>  (2/6) type_specific.io-github-autotest-libvirt.memory.devices.dimm.memory_allocation_and_numa.no_numa.no_slot: PASS (41.13 s)
>  (3/6) type_specific.io-github-autotest-libvirt.memory.devices.dimm.memory_allocation_and_numa.no_numa.with_slot: PASS (67.06 s)
>  (4/6) type_specific.io-github-autotest-libvirt.memory.devices.dimm.memory_allocation_and_numa.with_numa.no_maxmemory: PASS (41.16 s)
>  (5/6) type_specific.io-github-autotest-libvirt.memory.devices.dimm.memory_allocation_and_numa.with_numa.no_slot: PASS (41.30 s)
>  (6/6) type_specific.io-github-autotest-libvirt.memory.devices.dimm.memory_allocation_and_numa.with_numa.with_slot: PASS (41.21 s)
> ```
> 
> arm+rhel9 ` `

@nanli1  Can you plz update test results for arm and rhel8+x86(TBD)?

2024-03-29 09:41 UTC, Yingshun reviewed
There are almost 8 variants for error messages both in cfg and py file. It seems that some variants are there for different libvirt versions. Can you merge some of them to make them simpler?   for eg.  using regular expression or wildcard or limit test variants in cfg and so on.  @nanli1  @dzhengfy

2024-03-29 09:41 UTC, Yingshun commented on libvirt/tests/src/memory/memory_devices/dimm_memory_with_memory_alloccation_and_numa.py
> +    vm_attrs = ""
Can you set vm_attrs as a dict by default and update it using update() ?  From the parameter information -  ":return vm_attrs: get updated vm attrs dict.", I think it's better to use directory, what do you think?

2024-03-29 09:41 UTC, Yingshun commented on libvirt/tests/src/memory/memory_devices/dimm_memory_with_memory_alloccation_and_numa.py
> +            define_error = params.get("define_error")
Is it possible to use an error message like 'error1|error2' to cover these part?

2024-03-29 09:41 UTC, Yingshun commented on libvirt/tests/src/memory/memory_devices/dimm_memory_with_memory_alloccation_and_numa.py
> +        libvirt.check_result(result, redefine_error_2)
Same as before.

2024-04-07 09:53 UTC, nanli1 commented on libvirt/tests/src/memory/memory_devices/dimm_memory_with_memory_alloccation_and_numa.py
> +            define_error = params.get("define_error")
Hi lcong, Could you please check  is it ok if we write as the above comment @liang-cong-red-hat

2024-04-08 05:37 UTC, liang-cong-red-hat commented on libvirt/tests/src/memory/memory_devices/dimm_memory_with_memory_alloccation_and_numa.py
> +            define_error = params.get("define_error")
I think better separating the error checking. But there is one thing we may improve, if we can ignore the result for some version for rhel9.3 or rhel9.2, then we may ignore some libvirt version checking for some kind of error message.

2024-04-13 04:08 UTC, nanli1 commented
Talk to lcong ,He will merge all the checking version, I will auto until his updating over.

2024-04-19 03:16 UTC, nanli1 commented on libvirt/tests/src/memory/memory_devices/dimm_memory_with_memory_alloccation_and_numa.py
> +        libvirt.check_result(result, redefine_error_2)
Thanks yingshun ,Updated

2024-04-22 01:27 UTC, Yingshun commented on libvirt/tests/src/memory/memory_devices/dimm_memory_with_memory_alloccation_and_numa.py
> +        vm.destroy()
Is this step needed? I can't find vm startup for general scenarios except  'slot_no_numa'.

2024-04-22 01:27 UTC, Yingshun commented on libvirt/tests/src/memory/memory_devices/dimm_memory_with_memory_alloccation_and_numa.py
> +        virsh.define(original_vmxml2.xml, debug=True, ignore_status=False)
Should it be a new scenario?

2024-04-22 01:27 UTC, Yingshun commented on libvirt/tests/src/memory/memory_devices/dimm_memory_with_memory_alloccation_and_numa.py
> +        libvirt.check_result(res, hotplug_error)
Is it better to wait until vm fully started up?

2024-04-22 01:27 UTC, Yingshun commented on libvirt/tests/src/memory/memory_devices/dimm_memory_with_memory_alloccation_and_numa.py
> +        if coldplug_error:
reuse libvirt.check_result()?

2024-04-26 07:38 UTC, nanli1 commented on libvirt/tests/src/memory/memory_devices/dimm_memory_with_memory_alloccation_and_numa.py
> +        virsh.define(original_vmxml2.xml, debug=True, ignore_status=False)
@liang-cong-red-hat Could you confirm

2024-04-26 07:48 UTC, liang-cong-red-hat commented on libvirt/tests/src/memory/memory_devices/dimm_memory_with_memory_alloccation_and_numa.py
> +        virsh.define(original_vmxml2.xml, debug=True, ignore_status=False)
yeah, below scenarios could split to new scenarios

2024-04-26 08:45 UTC, nanli1 commented on libvirt/tests/src/memory/memory_devices/dimm_memory_with_memory_alloccation_and_numa.py
> +        libvirt.check_result(res, hotplug_error)
Thanks yingshun, Updated :D

2024-04-26 08:45 UTC, nanli1 commented on libvirt/tests/src/memory/memory_devices/dimm_memory_with_memory_alloccation_and_numa.py
> +        if coldplug_error:
Thanks yingshun, Updated :D

2024-04-26 08:46 UTC, nanli1 commented on libvirt/tests/src/memory/memory_devices/dimm_memory_with_memory_alloccation_and_numa.py
> +        vm.destroy()
Thanks yingshun, Updated :D

2024-04-26 11:21 UTC, Yingshun commented on libvirt/tests/src/memory/memory_devices/dimm_memory_with_memory_alloccation_and_numa.py
> +        virsh.define(original_vmxml2.xml, debug=True, ignore_status=False)
Yes, I understood. But we're going to automate the cases, so I think it's more important to have a clean and clear scenario. Do you mind if we split them in the script?

2024-04-28 03:16 UTC, nanli1 commented
Confirm with lcong ,we need to split this case  because some scenarios are mixed , Will auto after these scenarios are splited over

2024-05-14 03:56 UTC, Yingshun approved these changes

2024-05-21 04:40 UTC, liang-cong-red-hat requested changes
Except the s390 restriction, others LGTM

2024-05-21 05:21 UTC, nanli1 commented on libvirt/tests/cfg/memory/memory_devices/dimm_memory_with_memory_alloccation_and_numa.cfg
> +- memory.devices.dimm.memory_allocation_and_numa:
Thanks lcong , Updated

2024-05-21 05:25 UTC, liang-cong-red-hat approved these changes
Pls remove the s390 restriction inside the matrix.

2024-05-21 05:25 UTC, liang-cong-red-hat commented on libvirt/tests/cfg/memory/memory_devices/dimm_memory_with_memory_alloccation_and_numa.cfg
> +            no s390-virtio
here you can remove s390 restriction

2024-05-21 05:42 UTC, nanli1 commented on libvirt/tests/cfg/memory/memory_devices/dimm_memory_with_memory_alloccation_and_numa.cfg
> +            no s390-virtio
Thanks lcong, Updated

2024-05-21 12:14 UTC, dzhengfy approved these changes
LGTM.  We will consider to increase the vm memory in the test in another patch request.

2024-05-21 12:15 UTC, merged