Add bootc image builder case
autotest/tp-libvirt pull request #5540
Opened 2024-03-23 07:42 UTC by chunfuwen

2024-04-01 10:18 UTC, chunfuwen commented
[Test name](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/bootc-image-builder-RHEL-9.4-runtest-x86_64-acceptance-gating/lastCompletedBuild/testReport/rhel/bootc_image_builder/#)
[Duration](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/bootc-image-builder-RHEL-9.4-runtest-x86_64-acceptance-gating/lastCompletedBuild/testReport/rhel/bootc_image_builder/#)
[Status](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/bootc-image-builder-RHEL-9.4-runtest-x86_64-acceptance-gating/lastCompletedBuild/testReport/rhel/bootc_image_builder/#)
[bib.disk_image_generation.ami.centos.unuse_config_json.tls_verify_disable.owner_change_disable](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/bootc-image-builder-RHEL-9.4-runtest-x86_64-acceptance-gating/lastCompletedBuild/testReport/rhel/bootc_image_builder/bib_disk_image_generation_ami_centos_unuse_config_json_tls_verify_disable_owner_change_disable)	4 min 3 sec	Passed
[bib.disk_image_generation.ami.centos.unuse_config_json.tls_verify_disable.owner_change_enable](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/bootc-image-builder-RHEL-9.4-runtest-x86_64-acceptance-gating/lastCompletedBuild/testReport/rhel/bootc_image_builder/bib_disk_image_generation_ami_centos_unuse_config_json_tls_verify_disable_owner_change_enable)	4 min 47 sec	Passed
[bib.disk_image_generation.ami.centos.unuse_config_json.tls_verify_enable.owner_change_disable](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/bootc-image-builder-RHEL-9.4-runtest-x86_64-acceptance-gating/lastCompletedBuild/testReport/rhel/bootc_image_builder/bib_disk_image_generation_ami_centos_unuse_config_json_tls_verify_enable_owner_change_disable)	4 min 10 sec	Passed
[bib.disk_image_generation.ami.centos.unuse_config_json.tls_verify_enable.owner_change_enable](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/bootc-image-builder-RHEL-9.4-runtest-x86_64-acceptance-gating/lastCompletedBuild/testReport/rhel/bootc_image_builder/bib_disk_image_generation_ami_centos_unuse_config_json_tls_verify_enable_owner_change_enable)	4 min 14 sec	Passed
[bib.disk_image_generation.ami.centos.use_config_json.tls_verify_disable.owner_change_disable](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/bootc-image-builder-RHEL-9.4-runtest-x86_64-acceptance-gating/lastCompletedBuild/testReport/rhel/bootc_image_builder/bib_disk_image_generation_ami_centos_use_config_json_tls_verify_disable_owner_change_disable)	4 min 19 sec	Passed
[bib.disk_image_generation.ami.centos.use_config_json.tls_verify_disable.owner_change_enable](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/bootc-image-builder-RHEL-9.4-runtest-x86_64-acceptance-gating/lastCompletedBuild/testReport/rhel/bootc_image_builder/bib_disk_image_generation_ami_centos_use_config_json_tls_verify_disable_owner_change_enable)	4 min 17 sec	Passed
[bib.disk_image_generation.ami.centos.use_config_json.tls_verify_enable.owner_change_disable](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/bootc-image-builder-RHEL-9.4-runtest-x86_64-acceptance-gating/lastCompletedBuild/testReport/rhel/bootc_image_builder/bib_disk_image_generation_ami_centos_use_config_json_tls_verify_enable_owner_change_disable)	4 min 1 sec	Passed
[bib.disk_image_generation.ami.centos.use_config_json.tls_verify_enable.owner_change_enable](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/bootc-image-builder-RHEL-9.4-runtest-x86_64-acceptance-gating/lastCompletedBuild/testReport/rhel/bootc_image_builder/bib_disk_image_generation_ami_centos_use_config_json_tls_verify_enable_owner_change_enable)	4 min 33 sec	Passed
[bib.disk_image_generation.ami.fedora.unuse_config_json.tls_verify_disable.owner_change_disable](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/bootc-image-builder-RHEL-9.4-runtest-x86_64-acceptance-gating/lastCompletedBuild/testReport/rhel/bootc_image_builder/bib_disk_image_generation_ami_fedora_unuse_config_json_tls_verify_disable_owner_change_disable)	3 min 17 sec	Passed
[bib.disk_image_generation.ami.fedora.unuse_config_json.tls_verify_disable.owner_change_enable](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/bootc-image-builder-RHEL-9.4-runtest-x86_64-acceptance-gating/lastCompletedBuild/testReport/rhel/bootc_image_builder/bib_disk_image_generation_ami_fedora_unuse_config_json_tls_verify_disable_owner_change_enable)	3 min 54 sec	Passed
[bib.disk_image_generation.ami.fedora.unuse_config_json.tls_verify_enable.owner_change_disable](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/bootc-image-builder-RHEL-9.4-runtest-x86_64-acceptance-gating/lastCompletedBuild/testReport/rhel/bootc_image_builder/bib_disk_image_generation_ami_fedora_unuse_config_json_tls_verify_enable_owner_change_disable)	3 min 25 sec	Passed
[bib.disk_image_generation.ami.fedora.unuse_config_json.tls_verify_enable.owner_change_enable](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/bootc-image-builder-RHEL-9.4-runtest-x86_64-acceptance-gating/lastCompletedBuild/testReport/rhel/bootc_image_builder/bib_disk_image_generation_ami_fedora_unuse_config_json_tls_verify_enable_owner_change_enable)	3 min 26 sec	Passed
[bib.disk_image_generation.ami.fedora.use_config_json.tls_verify_disable.owner_change_disable](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/bootc-image-builder-RHEL-9.4-runtest-x86_64-acceptance-gating/lastCompletedBuild/testReport/rhel/bootc_image_builder/bib_disk_image_generation_ami_fedora_use_config_json_tls_verify_disable_owner_change_disable)	3 min 26 sec	Passed
[bib.disk_image_generation.ami.fedora.use_config_json.tls_verify_disable.owner_change_enable](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/bootc-image-builder-RHEL-9.4-runtest-x86_64-acceptance-gating/lastCompletedBuild/testReport/rhel/bootc_image_builder/bib_disk_image_generation_ami_fedora_use_config_json_tls_verify_disable_owner_change_enable)	4 min 8 sec	Passed
[bib.disk_image_generation.ami.fedora.use_config_json.tls_verify_enable.owner_change_disable](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/bootc-image-builder-RHEL-9.4-runtest-x86_64-acceptance-gating/lastCompletedBuild/testReport/rhel/bootc_image_builder/bib_disk_image_generation_ami_fedora_use_config_json_tls_verify_enable_owner_change_disable)	3 min 31 sec	Passed
[bib.disk_image_generation.ami.fedora.use_config_json.tls_verify_enable.owner_change_enable](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/bootc-image-builder-RHEL-9.4-runtest-x86_64-acceptance-gating/lastCompletedBuild/testReport/rhel/bootc_image_builder/bib_disk_image_generation_ami_fedora_use_config_json_tls_verify_enable_owner_change_enable)	3 min 52 sec	Passed
[bib.disk_image_generation.ami.local_image.unuse_config_json.tls_verify_disable.owner_change_disable](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/bootc-image-builder-RHEL-9.4-runtest-x86_64-acceptance-gating/lastCompletedBuild/testReport/rhel/bootc_image_builder/bib_disk_image_generation_ami_local_image_unuse_config_json_tls_verify_disable_owner_change_disable)	3 min 44 sec	Passed
[bib.disk_image_generation.ami.local_image.unuse_config_json.tls_verify_disable.owner_change_enable](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/bootc-image-builder-RHEL-9.4-runtest-x86_64-acceptance-gating/lastCompletedBuild/testReport/rhel/bootc_image_builder/bib_disk_image_generation_ami_local_image_unuse_config_json_tls_verify_disable_owner_change_enable)	3 min 46 sec	Passed
[bib.disk_image_generation.ami.local_image.unuse_config_json.tls_verify_enable.owner_change_disable](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/bootc-image-builder-RHEL-9.4-runtest-x86_64-acceptance-gating/lastCompletedBuild/testReport/rhel/bootc_image_builder/bib_disk_image_generation_ami_local_image_unuse_config_json_tls_verify_enable_owner_change_disable)	3 min 59 sec	Passed
[bib.disk_image_generation.ami.local_image.unuse_config_jso [...]

2024-04-09 11:13 UTC, smitterl commented on provider/bootc_image_builder/bootc_image_build_utils.py
> +    @param params: one dictionary wrapping various parameter
'various parameters'

2024-04-09 11:13 UTC, smitterl commented on provider/bootc_image_builder/bootc_image_build_utils.py
> +        raise exceptions.TestFail('The VM state is not powered on,actually is: %s') % result
",actually" -> ", actually"

2024-04-09 11:13 UTC, smitterl commented on provider/bootc_image_builder/bootc_image_build_utils.py
> +    if result not in "poweredOn":
This works but looks unusual, why not
```python
if result != "poweredOn":
```
?

2024-04-09 11:13 UTC, smitterl commented on provider/bootc_image_builder/bootc_image_build_utils.py
> +    """
Why "wrapped"?

2024-04-09 11:13 UTC, smitterl commented on provider/bootc_image_builder/bootc_image_build_utils.py
> +    prepare environment,virt install,and login vm
",virt install,and" --> ", virt install, and"

2024-04-09 11:13 UTC, smitterl commented on provider/bootc_image_builder/bootc_image_build_utils.py
> +    @param params: one dictionary wrapping various parameter
various parameters

2024-04-09 11:13 UTC, smitterl commented on provider/bootc_image_builder/bootc_image_build_utils.py
> +        ip_address = vm.wait_for_get_address(nic_index=0)
You don't seem to be using `user` nor `passwd` here, please remove them.

2024-04-09 11:13 UTC, smitterl commented on virttools/tests/src/bootc_image_builder/bootc_disk_image_install.py
> +    try:
I'd rather you'd break down the try-block into smaller functions so it's easier to understand what is tested:
```python
try:
    prepare_environment(...)
    build_container(...)
    validate_build_output(...)
    create_vm(...)
finally:
....
```

2024-06-12 01:00 UTC, chunfuwen commented on provider/bootc_image_builder/bootc_image_build_utils.py
> +    cmd = "sudo podman run --rm -it --privileged --pull=newer --security-opt label=type:unconfined_t -v /var/lib/libvirt/images/output:/output"
bootc image builder was used as  normal user by default. But it need privileged permission, so from this point view, there is very tiny difference between normal user and root. Here use sudo is to keep compatibility if one day all environment need to switch to normal user.

2024-06-12 01:02 UTC, chunfuwen commented on provider/bootc_image_builder/bootc_image_build_utils.py
> +        LOG.debug("public key doesn't exist, please create one")
changed to "public key doesn't exist, will help create one" to avoid confusion

2024-06-12 01:10 UTC, chunfuwen commented on provider/bootc_image_builder/bootc_image_build_utils.py
> +    # create VmWare tool folder
updated

2024-06-12 01:15 UTC, chunfuwen commented on provider/bootc_image_builder/bootc_image_build_utils.py
> +        delete_vm_if_existed(params)
changed to delete_vm_if_present

2024-06-12 01:17 UTC, chunfuwen commented on provider/bootc_image_builder/bootc_image_build_utils.py
> +        process.run(govc_install_cmd, shell=True, ignore_status=False)
I would like to keep code logic here, since it firstly check whether govc exist or not. And in case CI not handle it gracefully, we can still work. But it is true, we can firstly add package dependence in CI jobs, let CI handle it

2024-06-12 01:19 UTC, chunfuwen commented on provider/bootc_image_builder/bootc_image_build_utils.py
> +    shutil.copy("/etc/yum.repos.d/beaker-AppStream.repo", folder)
Currently there is no plan to use other provisioned system ,other than beaker. Maybe once there is new provision system, we can consider make it more flexible.

2024-06-12 01:22 UTC, chunfuwen commented on provider/bootc_image_builder/bootc_image_build_utils.py
> +        if add_vmware_tool:
updated

2024-06-12 01:25 UTC, chunfuwen commented on provider/bootc_image_builder/bootc_image_build_utils.py
> +    process.run("govc about", shell=True, ignore_status=False)
updated

2024-06-12 01:32 UTC, chunfuwen commented on provider/bootc_image_builder/bootc_image_build_utils.py
> +    @param params: one dictionary wrapping various parameter
I met some situation where at the beginning, it may need one or two parameters only. But when there is requirements to expand this function, suddenly finding it need more than 4 or 5 parameters. So it seems that it is useful that we set parameter as dict  at the beginning.

2024-06-12 01:33 UTC, chunfuwen commented on provider/bootc_image_builder/bootc_image_build_utils.py
> +    @param params: one dictionary wrapping various parameter
updated

2024-06-12 01:35 UTC, chunfuwen commented on provider/bootc_image_builder/bootc_image_build_utils.py
> +        raise exceptions.TestFail('The VM state is not powered on,actually is: %s') % result
updated

2024-06-12 01:35 UTC, chunfuwen commented on provider/bootc_image_builder/bootc_image_build_utils.py
> +    """
remove "wrapped"

2024-06-12 01:36 UTC, chunfuwen commented on provider/bootc_image_builder/bootc_image_build_utils.py
> +    prepare environment,virt install,and login vm
updated

2024-06-12 01:36 UTC, chunfuwen commented on provider/bootc_image_builder/bootc_image_build_utils.py
> +    @param params: one dictionary wrapping various parameter
updated

2024-06-12 01:37 UTC, chunfuwen commented on provider/bootc_image_builder/bootc_image_build_utils.py
> +        ip_address = vm.wait_for_get_address(nic_index=0)
updated

2024-06-12 01:38 UTC, chunfuwen commented on virttools/tests/src/bootc_image_builder/bootc_disk_image_install.py
> +    try:
updated

2024-08-26 16:35 UTC, smitterl requested changes
@chunfuwen Thanks for this. Some comments from me, please check. I found it a bit difficult to review, so please be patient with me.

One nitpick I've seen repeatedly is the different ways to document the `params` parameter which I sometimes found confusing. After fixing the "@param" you might just use the same docstring for all. I think for the `params` test parameters you should follow the lines of `:param test: test object` and just call all instances `:param params: test parameters` to avoid questions about 'wrapped' et al. `sed -ei 's/:param params:.*/:param params: test parameters/g' <new code>`.

Secondly, the configuration files and some of the script files looks duplicated and there are ways to reduce this, s. my comment.

Finally, I think you should also move VMWare / govc related functions into their own file vmware_utils.py, same as you already did for aws_utils.py

Thank you. Sebas

2024-08-26 16:35 UTC, smitterl commented on virttools/tests/src/bootc_image_builder/bootc_disk_image_build.py
> +    Test boot container image builder.
I think you should update the docstring to describe on a high level what is being tested. AFAICT:

1. Add existing bootable image to podman (cover rhel, fedora).
2. Build image from bootable image with podman (AWS, QCOW2 et al.).
3. Validate podman build image command output.

2024-08-26 16:35 UTC, smitterl commented on virttools/tests/src/bootc_image_builder/bootc_disk_image_install.py
> +def validate_bib_output(params, test):
I compared this `validate_bib_output` with the one of the other script file. This function here rather seems to update / get updated test parameters instead of validating. The part "if not os.path.exists" also seems already covered in `bootc_disk_image_build.py`, not sure if it's still necessary here; maybe this function should rather be called `update_bib_env_info` or similar?

2024-08-26 16:35 UTC, smitterl commented on virttools/tests/src/bootc_image_builder/bootc_disk_image_install.py
> +    Test install disk image generated by boot container image builder.
I think you should update the docstring to describe on a high level what is being tested. AFAICT:

1. Add existing bootable image to podman (cover rhel, fedora).
2. Build image from bootable image with podman (AWS, QCOW2 et al.).
3. Install the image and confirm it boots (on AWS cloud, locally or VMWare vCenter).

2024-08-26 16:35 UTC, smitterl commented on provider/bootc_image_builder/aws_utils.py
> +    if not os.path.exists("/usr/local/bin/aws"):
Not blocking, just a comment:
Using snap packages (officially supported by AWS) or generating our own rpm packages removes the need for this kind of package cleanup logic.

https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/administering_the_system_using_the_gnome_desktop_environment/assembly_installing-applications-using-flatpak_administering-the-system-using-the-gnome-desktop-environment

or

https://github.com/mcenirm/awscliv2-rpm

2024-08-26 16:35 UTC, smitterl commented on virttools/tests/cfg/bootc_image_builder/bootc_disk_image_build.cfg
> +- bootc_image_builder.bib.disk_image_generation:
Not blocking, just a comment: the configuration looks mostly duplicated with the image_install.cfg. Maybe it would have been better to have a single config and script file making it easier to review and reducing duplication: the `prepare_env_and_execute_bib` is duplicated between both script files.

Another way to reduce at least the duplication in the test config could be to reference different script files in the same test config: You can change the script file in your configuration file, though I haven't tried this myself, I've seen it in https://github.com/autotest/tp-qemu/blob/master/qemu/tests/cfg/s390x_cpu_model.cfg

```yaml
- bootc_image_builder.bib:
...
 - disk_image_generation:
   type = bootc_disk_image_build
...
 - disk_image_image_install:
   type = bootc_disk_image_install
```

2024-09-12 03:00 UTC, chunfuwen commented on provider/bootc_image_builder/bootc_image_build_utils.py
> +        process.run(download_vmware_config_cmd, shell=True, verbose=True, ignore_status=True)
download_vmware_config_cmd is specific command to some tasks, this is not general one. The actually working one is actually process.run, which is already is one atomic function. Here download_vmware_config_cmd can be regarded as one input parameter for primitive function:process.run

2024-09-12 03:05 UTC, chunfuwen commented on provider/bootc_image_builder/bootc_image_build_utils.py
> +        process.run(govc_install_cmd, shell=True, ignore_status=False)
Both which gov and current way are reliable ways. I notice in many shell scripts, guy often use take further actions depending on whether specific folder exists or not

2024-09-12 03:12 UTC, chunfuwen commented on virttools/tests/src/bootc_image_builder/bootc_disk_image_install.py
> +    add_vmware_tool = "yes" == params.get("add_vmware_tool")
remove it

2024-09-12 03:15 UTC, chunfuwen commented on virttools/tests/src/bootc_image_builder/bootc_disk_image_build.py
> +    :param params: one collective object representing wrapped parameters
updated

2024-09-12 03:16 UTC, chunfuwen commented on provider/bootc_image_builder/bootc_image_build_utils.py
> +    :param params: wrap up all parameters
updated

2024-09-12 03:18 UTC, chunfuwen commented on virttools/tests/src/bootc_image_builder/bootc_disk_image_build.py
> +    Test boot container image builder.
updated

2024-09-12 03:21 UTC, chunfuwen commented on virttools/tests/src/bootc_image_builder/bootc_disk_image_install.py
> +def validate_bib_output(params, test):
updated

2024-09-12 03:21 UTC, chunfuwen commented on virttools/tests/src/bootc_image_builder/bootc_disk_image_install.py
> +    Test install disk image generated by boot container image builder.
updatated

2024-09-12 03:23 UTC, chunfuwen commented on provider/bootc_image_builder/aws_utils.py
> +    if not os.path.exists("/usr/local/bin/aws"):
Thank for bringing up this idea.Current solution is  AWS official site to introduce how we install tools on linux, see https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html

2024-09-12 03:26 UTC, chunfuwen commented on virttools/tests/cfg/bootc_image_builder/bootc_disk_image_build.cfg
> +- bootc_image_builder.bib.disk_image_generation:
image_install and image_generate has basic overraping in bib version, outputs image formats. But they vary a lot in later validation(see relative cfg files). So it is better to keep them separate to allow flexibility to meet different reqirements

2024-09-12 03:36 UTC, chunfuwen commented on provider/bootc_image_builder/bootc_image_build_utils.py
> +    shutil.copy("/etc/yum.repos.d/beaker-AppStream.repo", folder)
Thank for understanding this. Once we has upstream uncompatiibility one day,  I can  update that when it comes

2024-09-12 06:39 UTC, chunfuwen commented
@smitterl , your comments are addressed, please help double check this

2024-09-12 07:36 UTC, smitterl approved these changes
LGTM, thank you @chunfuwen

2024-09-12 07:36 UTC, smitterl commented on provider/bootc_image_builder/bootc_image_build_utils.py
> +        process.run(download_vmware_config_cmd, shell=True, verbose=True, ignore_status=True)
I understand. I meant there should be a function 'add_vmware_tool' to help with readability, maintaining the same level of abstraction

```python
def add_vmware_tool(params):
 ....
       vmware_tool_path = os.path.join(folder, "etc/vmware-tools/")
        if not os.path.exists(vmware_tool_path):
            os.makedirs(vmware_tool_path)
 ...
        process.run(download_vmware_config_cmd, shell=True, verbose=True, ignore_status=True)
```
Same for following
```python
def enable_fips(params):
...
       dnf_fips_install = "RUN cat > /usr/lib/bootc/kargs.d/01-fips.toml <<'EOF'\n" \
                           "kargs = ['fips=1']\n" \
                           "match-architectures = ['x86_64']\n" \
                           "EOF\n" \
                           "RUN dnf install -y crypto-policies-scripts && " \
                           "update-crypto-policies --no-reload --set FIPS "
```
```python
def setup_custom_repo(params):
...
        repo_path = pathlib.Path(folder) / "rhel-9.4.repo"
...
        crb_repo_content = f"""
            [{repo_prefix}-crb]
            name=beaker-CRB\n
            baseurl={compose_url}/compose/CRB/{vm_arch_name}/os/
            enabled=1
            gpgcheck=0
            sslverify=0\n
            """
```

2024-09-12 07:36 UTC, smitterl commented on virttools/tests/cfg/bootc_image_builder/bootc_disk_image_build.cfg
> +- bootc_image_builder.bib.disk_image_generation:
Thanks for clarifying.

2024-09-12 08:19 UTC, dzhengfy approved these changes
LGTM

2024-09-12 08:21 UTC, merged