Automate blockresize cases
autotest/tp-libvirt pull request #5585
Opened 2024-04-23 03:36 UTC by chunfuwen

Cover blockresize in various scenarios

2024-04-23 13:41 UTC, nanli1 reviewed
Any result

2024-04-27 03:49 UTC, chunfuwen commented
PASS 01-type_specific.io-github-autotest-libvirt.virtual_disks.blockresize.coldplug.virtio.capacity
PASS 02-type_specific.io-github-autotest-libvirt.virtual_disks.blockresize.coldplug.virtio.specific
PASS 03-type_specific.io-github-autotest-libvirt.virtual_disks.blockresize.coldplug.virtio.save_restore
PASS 04-type_specific.io-github-autotest-libvirt.virtual_disks.blockresize.coldplug.virtio.not_equal_actual_size
PASS 05-type_specific.io-github-autotest-libvirt.virtual_disks.blockresize.coldplug.virtio.not_zero_offset
PASS 06-type_specific.io-github-autotest-libvirt.virtual_disks.blockresize.coldplug.virtio.non_raw_block_device
PASS 07-type_specific.io-github-autotest-libvirt.virtual_disks.blockresize.coldplug.sata.capacity
PASS 08-type_specific.io-github-autotest-libvirt.virtual_disks.blockresize.coldplug.sata.specific
PASS 09-type_specific.io-github-autotest-libvirt.virtual_disks.blockresize.coldplug.scsi.capacity
PASS 10-type_specific.io-github-autotest-libvirt.virtual_disks.blockresize.coldplug.scsi.specific
PASS 11-type_specific.io-github-autotest-libvirt.virtual_disks.blockresize.hotplug.virtio.capacity
PASS 12-type_specific.io-github-autotest-libvirt.virtual_disks.blockresize.hotplug.virtio.specific
PASS 13-type_specific.io-github-autotest-libvirt.virtual_disks.blockresize.hotplug.scsi.capacity
PASS 14-type_specific.io-github-autotest-libvirt.virtual_disks.blockresize.hotplug.scsi.specific

2024-04-28 03:41 UTC, nanli1 approved these changes

2024-04-28 03:41 UTC, nanli1 commented on libvirt/tests/src/virtual_disks/virtual_disks_blockresize.py
> +        time.sleep(20)
Is it necessary to wait here , or could we use  `utils_misc.wait_for( `

2024-04-28 03:41 UTC, nanli1 commented on libvirt/tests/src/virtual_disks/virtual_disks_blockresize.py
> +        test.fail(f"actual size of block disk is {actual_size_in_bytes}, but expected is : {matched_size}")
You could reuse    ` check_obj.check_image_info()`  if you want

2024-04-28 03:41 UTC, nanli1 commented on libvirt/tests/src/virtual_disks/virtual_disks_blockresize.py
> +        device_obj = create_customized_disk(params, test)
You could reuse setup_attrs if you want

2024-04-30 15:35 UTC, smitterl requested changes

2024-04-30 15:35 UTC, smitterl commented on libvirt/tests/cfg/virtual_disks/virtual_disks_blockresize.cfg
> +            only coldplug
Please add `no s390-virtio`

2024-04-30 15:35 UTC, smitterl commented on libvirt/tests/src/virtual_disks/virtual_disks_blockresize.py
> +
The empty line from l48 should be before the param listing in l45 IMO.

2024-04-30 15:35 UTC, smitterl commented on libvirt/tests/src/virtual_disks/virtual_disks_blockresize.py
> +    matched_size = params.get("block_size_in_bytes")
Here and in the rest of the code (function params), why not call it in a more standard way "expected_size"?

2024-04-30 15:35 UTC, smitterl commented on libvirt/tests/src/virtual_disks/virtual_disks_blockresize.py
> +        for file_path in cleanup_files:
IMO, the two comments are not necessary the `xml.sync` and `file_path in cleanup_file` already conveys what's done.

2024-04-30 15:35 UTC, smitterl commented on libvirt/tests/src/virtual_disks/virtual_disks_blockresize.py
> +    else:
What `if` does this correspond to?  Is this a typo?

2024-04-30 15:35 UTC, smitterl commented on libvirt/tests/src/virtual_disks/virtual_disks_blockresize.py
> +        device_obj = create_customized_disk(params, test)
+1

2024-05-15 04:45 UTC, chunfuwen commented on libvirt/tests/src/virtual_disks/virtual_disks_blockresize.py
> +        time.sleep(20)
The wait is to allow VM to  show up disk ,and following call new_disk, _ = libvirt_disk.get_non_root_disk_name(session) can succeed. 
So here it is for guest, and hard to find matched pattern for utils_misc.wait_for().

2024-05-15 04:46 UTC, chunfuwen commented on libvirt/tests/src/virtual_disks/virtual_disks_blockresize.py
> +        test.fail(f"actual size of block disk is {actual_size_in_bytes}, but expected is : {matched_size}")
This is only line code, looks like it is not necessary introduce another dependence: check_obj.check_image_info()

2024-05-15 04:51 UTC, chunfuwen commented on libvirt/tests/src/virtual_disks/virtual_disks_blockresize.py
> +        device_obj = create_customized_disk(params, test)
This issue has been discussed multiple round before. Whether use setup_attrs  or previously base utils. setup_attrs need input lots of long and runduant config infor as raw in cfg file, sometimes it look not clear to understand. Base utils build up some disperse parameter, and those parameter can share across variants in cfg file. Finally, I would like to say it is real balance here. I would like author choose his or her preferable ways.

2024-05-15 04:51 UTC, chunfuwen commented on libvirt/tests/cfg/virtual_disks/virtual_disks_blockresize.cfg
> +            only coldplug
done

2024-05-15 04:52 UTC, chunfuwen commented on libvirt/tests/src/virtual_disks/virtual_disks_blockresize.py
> +
updated

2024-05-15 04:54 UTC, chunfuwen commented on libvirt/tests/src/virtual_disks/virtual_disks_blockresize.py
> +    matched_size = params.get("block_size_in_bytes")
change name to expected_size

2024-05-15 04:54 UTC, chunfuwen commented on libvirt/tests/src/virtual_disks/virtual_disks_blockresize.py
> +        for file_path in cleanup_files:
remove those two comments

2024-05-15 04:57 UTC, chunfuwen commented on libvirt/tests/src/virtual_disks/virtual_disks_blockresize.py
> +    else:
this is try exception...else  ..finally mechanism

2024-05-16 07:11 UTC, smitterl commented on libvirt/tests/src/virtual_disks/virtual_disks_blockresize.py
> +        device_obj = create_customized_disk(params, test)
OK, I'm fine with it. I was recently requested to use a dictionary in the cfg though, but I agree the author should be able to decide. https://github.com/autotest/tp-libvirt/pull/5287#discussion_r1452064913

2024-05-16 07:13 UTC, smitterl commented on libvirt/tests/src/virtual_disks/virtual_disks_blockresize.py
> +    """
matched_size -> expected_size?

2024-05-16 07:13 UTC, smitterl commented on libvirt/tests/src/virtual_disks/virtual_disks_blockresize.py
> +    else:
thanks for clarifying!

2024-05-16 07:14 UTC, smitterl requested changes
@chunfuwen Just a minor nitpick about the usage of "matched_size", rest LGTM. Thanks

2024-05-16 08:10 UTC, chunfuwen commented on libvirt/tests/src/virtual_disks/virtual_disks_blockresize.py
> +    """
updated

2024-05-30 03:37 UTC, dzhengfy reviewed
Others LGTM

2024-05-30 03:37 UTC, dzhengfy commented on libvirt/tests/cfg/virtual_disks/virtual_disks_blockresize.cfg
> +            only coldplug
No aarch64, thanks

2024-05-30 05:55 UTC, chunfuwen commented on libvirt/tests/cfg/virtual_disks/virtual_disks_blockresize.cfg
> +            only coldplug
updated

2024-05-30 06:31 UTC, dzhengfy approved these changes

2024-05-30 06:31 UTC, merged