virtual_disks: Add a vhostvdpa disk nodedev test
autotest/tp-libvirt pull request #5587
Opened 2024-04-24 03:19 UTC by Yingshun

This PR adds:
    VIRT-300446 - Test nodedev related operations against vhostvdpa disk

**Depends on:**
- https://github.com/avocado-framework/avocado-vt/pull/3903
- https://github.com/avocado-framework/avocado-vt/pull/3904

**Test results:**
` (1/1) type_specific.io-github-autotest-libvirt.virtual_disks.vhostvdpa.nodedev: PASS (9.00 s)
`

2024-04-28 03:12 UTC, chunfuwen commented on libvirt/tests/src/virtual_disks/vhostvdpa_block_backend_type/nodedev_vhostvdpa_disk.py
> +        test.log.info("TEST_STEP: List node devices with vdpa capability on host.")
line 22 to line 28 , it looks like it is virsh command operation part, it can be wrapped into one specific method

2024-04-28 03:13 UTC, chunfuwen commented on libvirt/tests/src/virtual_disks/vhostvdpa_block_backend_type/nodedev_vhostvdpa_disk.py
> +        for dev_name in devs:
line 29 to line 40 , looks like it is to validate previous virsh operation, it can be wrapped into independent method

2024-04-28 05:47 UTC, Yingshun commented on libvirt/tests/src/virtual_disks/vhostvdpa_block_backend_type/nodedev_vhostvdpa_disk.py
> +        test.log.info("TEST_STEP: List node devices with vdpa capability on host.")
Yes, it might be. But this is to check the output of the virsh nodedev-list, I don't see any special need to wrap up virsh.nodedev_list() in my case.

2024-04-28 05:47 UTC, Yingshun commented on libvirt/tests/src/virtual_disks/vhostvdpa_block_backend_type/nodedev_vhostvdpa_disk.py
> +        for dev_name in devs:
It's about node device's xml checking. I don't quite understand your meaning of wrapping this part. Is that mean we need a common way to compare the xml? If yes, I remember we had a discussion - there's too many differences in different devices, so it's not easy to have that kind of common function at time. Plz let me know your thought, thx!

2024-04-29 01:19 UTC, nanli1 approved these changes

2024-04-30 15:13 UTC, smitterl requested changes

2024-04-30 15:13 UTC, smitterl commented on libvirt/tests/src/virtual_disks/vhostvdpa_block_backend_type/nodedev_vhostvdpa_disk.py
> +        test.log.info("TEST_STEP: List node devices with vdpa capability on host.")
> line 22 to line 28 , it looks like it is virsh command operation part, it can be wrapped into one specific method

+1 

It improves the readability of the code. Clean code principles recommend to use functions with descriptive names instead of comments (this can help comments get out of sync with code) and functions should strive to maintain the same abstraction level. It can help focus on what's important in each function. The code will be easier to maintain. For run:

```python
try:
     test_env_obj = prepare_vhost_vdpa_disks()
     devs = get_vdpa_host_devices(test_env_obj)
     for dev_name in devs:
          check_nodedev_xml(dev_name)
finally:
    test_env_obj.cleanup()
```

Just by rewriting it in this way I noticed that your code actually doesn't exactly do what the comment promises, or I might be misunderstanding:

```python
def run(test, params, env):
    """
    Verify nodedev related operations against vhost-vdpa disk.
    """
```
IMO, you more accurately:
```python
def run(test, params, env):
    """
    Verify nodedev attributes for vhost-vdpa disk
    """
```
There are no operations against vhost_vdpa.

2024-04-30 15:13 UTC, smitterl commented on libvirt/tests/src/virtual_disks/vhostvdpa_block_backend_type/nodedev_vhostvdpa_disk.py
> +        for dev_name in devs:
> line 29 to line 40 , looks like it is to validate previous virsh operation, it can be wrapped into independent method

+1, see comment above

2024-04-30 15:16 UTC, smitterl commented
Thanks @Yingshun I agree with @chunfuwen that the code could be made more readable. Please, check my comment, do I understand the docstring for the 'run' method correctly?

2024-05-06 05:41 UTC, Yingshun commented on libvirt/tests/src/virtual_disks/vhostvdpa_block_backend_type/nodedev_vhostvdpa_disk.py
> +        test.log.info("TEST_STEP: List node devices with vdpa capability on host.")
The description of the polarion case is "This case is to verify that nodedev related operations against vhostvdpa disk can succeed.", so I think it will do some operations on the vhost-vdpa disk like virsh nodedev-list and nodedev-dumpxml to make sure all these operations work well, and I think it's not a test only for nodedev attributes, so I'd like to keep the current way. what do you think?

2024-05-06 05:42 UTC, Yingshun commented on libvirt/tests/src/virtual_disks/vhostvdpa_block_backend_type/nodedev_vhostvdpa_disk.py
> +        for dev_name in devs:
updated.

2024-05-07 07:39 UTC, smitterl commented on libvirt/tests/src/virtual_disks/vhostvdpa_block_backend_type/nodedev_vhostvdpa_disk.py
> +        test.log.info("TEST_STEP: List node devices with vdpa capability on host.")
@Yingshun I'm sorry but I don't agree. I might be missing something. Where are those operations? If there are none, the comment shouldn't say there should be any. Also, please consider that these automated test cases are upstream. Hopefully there will be other people using them and they don't have access to the test management system. As mentioned on another PR, maybe the right thing is to update the documented test cases. If that test case mentions operations but those operations are not run during the test case, then from my POV that's wrong.

2024-05-07 08:59 UTC, smitterl commented on libvirt/tests/src/virtual_disks/vhostvdpa_block_backend_type/nodedev_vhostvdpa_disk.py
> +        test.log.info("TEST_STEP: List node devices with vdpa capability on host.")
Clarified misunderstanding offline.

2024-05-07 08:59 UTC, smitterl approved these changes
LGTM, thank you!

2024-05-10 01:39 UTC, chunfuwen approved these changes
lgtm

2024-05-10 01:41 UTC, merged