add case for checking delete and revert snap event in multiple branch
autotest/tp-libvirt pull request #5595
Opened 2024-04-29 05:57 UTC by nanli1

xxxx-300473: Delete and revert snapshots and check events in two snapshot branches
Signed-off-by: nanli <nanli@redhat.com>
 ```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 snapshot_event.multiple_branch.del_and_revert

JOB LOG    : /var/lib/avocado/job-results/job-2024-04-29T01.45-83f3e08/job.log
 (1/1) type_specific.io-github-autotest-libvirt.snapshot_event.multiple_branch.del_and_revert: PASS (104.57 s)

```

2024-04-29 14:59 UTC, smitterl requested changes
@nanli1 Thanks for this. There's one small ask, please check my comment.
Rest LGTM

2024-04-29 14:59 UTC, smitterl commented on libvirt/tests/src/snapshot/check_delete_and_revert_snap_event_in_multiple_branch.py
> +        test.log.info("TEST_SETUP: Prepare the parent external snapshot "
It would be great if you could add a comment about the expected structure. I think from the code, it will be:

```
+ snap1
    + snap2
+ snap3
    + snap4
        + snap5
```

Is that correct? @nanli1

2024-05-08 02:15 UTC, nanli1 commented on libvirt/tests/src/snapshot/check_delete_and_revert_snap_event_in_multiple_branch.py
> +        test.log.info("TEST_SETUP: Prepare the parent external snapshot "
hi Sebas ,Thanks your comment . 
The snaps  are like the below tree , and I have given the tree log in
` L80:         virsh.snapshot_list(vm_name, **virsh_dargs, options='--tree')`

 ```
 s1 
  |
  +- s2
  |   |
  |   +- s3
  |     
  +- s4
      |
      +- s5

```

2024-05-14 07:52 UTC, smitterl requested changes

2024-05-14 07:52 UTC, smitterl commented on libvirt/tests/src/snapshot/check_delete_and_revert_snap_event_in_multiple_branch.py
> +        test.log.info("TEST_SETUP: Prepare the parent external snapshot "
@nanli1 Thanks for confirming. What I meant to say is that you should please add this tree to the docstring for  the setup_test function. Rest LGTM.

2024-05-14 13:56 UTC, nanli1 commented on libvirt/tests/src/snapshot/check_delete_and_revert_snap_event_in_multiple_branch.py
> +        test.log.info("TEST_SETUP: Prepare the parent external snapshot "
Thanks Sebas ,Updated

2024-05-14 14:04 UTC, smitterl approved these changes
@nanli1 Thank you!

2024-05-15 06:10 UTC, cliping approved these changes
LGTM

2024-05-16 08:44 UTC, chunfuwen approved these changes
lgtm

2024-05-16 08:44 UTC, merged