graphics: Add case to check domdisplay output
autotest/tp-libvirt pull request #5639
Opened 2024-05-28 06:56 UTC by cliping

XXXX-62543 - [vnc] Query display URI of vnc that has password with/without --include-password

2024-05-28 06:56 UTC, cliping commented
Test result:

 (1/2) type_specific.io-github-autotest-libvirt.graphics.functional.positive_tests.vnc_only.set_passwd.check_with_domdisplay.without_passwd: PASS (13.44 s)
 (2/2) type_specific.io-github-autotest-libvirt.graphics.functional.positive_tests.vnc_only.set_passwd.check_with_domdisplay.with_passwd: PASS (11.81 s)

2024-06-04 05:57 UTC, meinaLi commented on libvirt/tests/cfg/graphics/graphics_functional.cfg
> +                                            domdisplay_options = "--include-password"
Actually I suggested to use with/without_passwd_flag or other options. Because in the graphics xml we also has "passwd='redhat'". If it's not clear, it will be understood as whether there is a password here.

2024-06-04 05:57 UTC, meinaLi commented on libvirt/tests/src/graphics/graphics_functional.py
> +        expected_uri += "%s" % str(int(expected_result['vnc_port']) - 5900)
Does this change affect our previous auto cases? I don't understand the previous checkpoint using vnc_port directly. So I'm afraid it will affect existing auto case.

2024-08-28 11:17 UTC, smitterl requested changes
Thanks for this. I agree with @meinaLi about the variant naming, rest LGTM.

2024-08-28 11:17 UTC, smitterl commented on libvirt/tests/src/graphics/graphics_functional.py
> +        expected_uri += "%s" % str(int(expected_result['vnc_port']) - 5900)
The VNC port is just a number, usually >= 5900, being 5900 the first one. However, in URIs, e.g. when connecting via a tiger vnc client, this is shorted to <host_ip>:0 for <host_ip>:5900 and <host_ip>:1 for 5901.

2024-08-28 11:17 UTC, smitterl commented on libvirt/tests/cfg/graphics/graphics_functional.cfg
> +                                            domdisplay_options = "--include-password"
I agree, or maybe
```
variants:
    - include_password_yes
    - include_password_no
```

2024-09-18 07:31 UTC, cliping commented on libvirt/tests/cfg/graphics/graphics_functional.cfg
> +                                            domdisplay_options = "--include-password"
Updated to include_password_yes/include_password_no, thanks.

2024-09-18 07:48 UTC, cliping commented on libvirt/tests/src/graphics/graphics_functional.py
> +        expected_uri += "%s" % str(int(expected_result['vnc_port']) - 5900)
@smitterl  Thanks for your explanation.

@meinaLi I ran graphical job with this PR. No error in test result.

2024-09-23 01:53 UTC, meinaLi approved these changes

2024-10-16 12:47 UTC, smitterl approved these changes
Thank you @cliping ! LGTM

2024-10-23 01:23 UTC, chunfuwen approved these changes
lgtm

2024-10-23 01:24 UTC, merged