add case for virtio memory hotplug
autotest/tp-libvirt pull request #5655
Opened 2024-05-31 10:01 UTC by nanli1

xxxx-300399: Virtio-mem memory device hot-plug
Signed-off-by: nanli <nanli@redhat.com>

```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.devices.virtio_mem.hotplug

 (1/4) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.hotplug.target_and_address: PASS (72.35 s)
 (2/4) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.hotplug.source_mib_and_hugepages: PASS (87.27 s)
 (3/4) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.hotplug.plug_exceeded_max_mem: PASS (75.12 s)
 (4/4) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.hotplug.duplicate_addr: PASS (84.02 s)

```

2024-06-03 00:37 UTC, chunfuwen commented on libvirt/tests/cfg/memory/memory_devices/virtio_mem_hotplug.cfg
> +- memory.devices.virtio_mem.hotplug:
is this the same with https://github.com/autotest/tp-libvirt/pull/5657?

2024-06-03 01:06 UTC, nanli1 commented on libvirt/tests/cfg/memory/memory_devices/virtio_mem_hotplug.cfg
> +- memory.devices.virtio_mem.hotplug:
hi chunfu, Thanks your comment , https://github.com/autotest/tp-libvirt/pull/5657 is unplug case, this case is plug case.

2024-06-05 02:47 UTC, liang-cong-red-hat requested changes
Others LGTM

2024-06-05 02:47 UTC, liang-cong-red-hat commented on libvirt/tests/src/memory/memory_devices/virtio_mem_hotplug.py
> +    params.update({"second_virtio_curr": _get_virtio_current()})
I think we don't have to get the virtio current memory again, use expected_current_size. Case would fail if different.

2024-06-06 04:37 UTC, liang-cong-red-hat requested changes

2024-06-06 04:37 UTC, liang-cong-red-hat commented on libvirt/tests/src/memory/memory_devices/virtio_mem_hotplug.py
> +            "Attached virtio memory current size should be %s", expected_current_size)
test.fail should have only one parameter

2024-06-12 03:44 UTC, nanli1 commented on libvirt/tests/src/memory/memory_devices/virtio_mem_hotplug.py
> +    params.update({"second_virtio_curr": _get_virtio_current()})
hi lcong ,Thanks your comment. That's what polarion case said and I also add wait function to check , I think it would always PASS with the below code
```
    def _get_virtio_current():
        return vm_xml.VMXML.new_from_dumpxml(
            vm_name).devices.by_device_tag("memory")[
            mem_index].target.current_size

    if not utils_misc.wait_for(
            lambda: expected_current_size == _get_virtio_current(), 20):
        test.fail(
            "Attached virtio memory current size should be %s" % expected_current_size)

```

2024-06-12 03:48 UTC, nanli1 commented on libvirt/tests/src/memory/memory_devices/virtio_mem_hotplug.py
> +            "Attached virtio memory current size should be %s", expected_current_size)
Thanks lcong, Updated.

2024-06-12 07:07 UTC, liang-cong-red-hat approved these changes
LGTM

2024-07-09 08:17 UTC, chunfuwen approved these changes
lgtm

2024-07-12 01:51 UTC, merged