fix virsh domstats block.allocation not changing issue during blockco…
autotest/tp-libvirt pull request #5664
Opened 2024-06-03 10:18 UTC by nanli1

…mmit

   add utils_misc.wait for function

2024-06-05 14:19 UTC, smitterl commented on libvirt/tests/src/backingchain/blockcommit/check_allocation_watermark_during_blockcommit.py
> +        def _compare_alloc():
maybe call this better `_alloc_changed` to be clearer about the expected comparison and boolean return value

2024-06-05 14:19 UTC, smitterl requested changes
I used this PR but the test still fails on my machine

```
JOB ID     : 6a88d361f2f1b8b9625ade6ea922cdbefa6fef6d
JOB LOG    : /var/lib/avocado/job-results/job-2024-06-05T10.17-6a88d36/job.log
 (1/1) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.allocation_watermark.block_disk.active_layer: FAIL: block.4.allocation is not changing during blockcommit in 15s. (56.96 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/lib/avocado/job-results/job-2024-06-05T10.17-6a88d36/results.html
JOB TIME   : 57.25 s
```

2024-06-06 12:29 UTC, nanli1 commented on libvirt/tests/src/backingchain/blockcommit/check_allocation_watermark_during_blockcommit.py
> +        def _compare_alloc():
Thanks Sebas, Not use dict.get() now,

2024-06-06 12:31 UTC, nanli1 commented
> I used this PR but the test still fails on my machine
> 
> ```
> JOB ID     : 6a88d361f2f1b8b9625ade6ea922cdbefa6fef6d
> JOB LOG    : /var/lib/avocado/job-results/job-2024-06-05T10.17-6a88d36/job.log
>  (1/1) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.allocation_watermark.block_disk.active_layer: FAIL: block.4.allocation is not changing during blockcommit in 15s. (56.96 s)
> RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
> JOB HTML   : /var/lib/avocado/job-results/job-2024-06-05T10.17-6a88d36/results.html
> JOB TIME   : 57.25 s
> ```

Updated this pr, and the file disk scenarios success all the time , block disk scenarios failed all the time now. Seeking meina's help to check if it's a bug.

2024-06-11 15:20 UTC, nanli1 commented
@smitterl Hi Sebas ,Thanks your comment ,I updated this pr and it has been running on x86 for 10 times and PASS, Please check on 390 ,Thanks.

2024-06-12 09:04 UTC, smitterl commented on libvirt/tests/src/backingchain/blockcommit/check_allocation_watermark_during_blockcommit.py
> +        def _compare_alloc():
I don't understand. What do you want to say with "Not use dict.get() now"?

What I mean is that the code currently is read in the following way:

```
 if not utils_misc.wait_for(_compare_alloc, timeout=120, step=0.1):
```

So, without further context it can be understood as "couldn't compare allocation".

The code would be more readable IMO if the line said

```
 if not utils_misc.wait_for(_alloc_changed, timeout=120, step=0.1):
```

Which is more easily understood as "if not _alloc_changed" = "if allocation didn't change".

2024-06-12 09:25 UTC, smitterl commented
Even with this patch the test fails.

AFAICT,

# The test has been checking `Got alloc dict : {'0': '1745944576', '1': '0', '2': '0', '3': '0', '4': '0'}` 
# the blockcommit finishes `virsh # Block commit: [100.00 %]`
# The test now tries to check again with `changing_index` value `4` which leads to ```
2024-06-12 05:15:02,226 test             L0941 ERROR|   File "/var/log/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-libvirt/libvirt/tests/src/backingchain/blockcommit/check_allocation_watermark_during_blockcommit.py", line 77, in _compare_alloc
    changing_alloc, alloc_value, new_alloc[changing_index]))

2024-06-12 05:15:02,226 test             L0941 ERROR| KeyError: '4'
```

2024-06-12 09:38 UTC, smitterl commented
> Even with this patch the test fails.
> 
> ```
> backingchain.blockcommit.allocation_watermark.block_disk.active_layer: ERROR: '4' (44.46 s)
> ```
> 
> AFAICT,
> 
> 1. the test has been checking `Got alloc dict : {'0': '1745944576', '1': '0', '2': '0', '3': '0', '4': '0'}`
> 2. the blockcommit finishes `virsh # Block commit: [100.00 %]`
> 3. the test now tries to check again with `changing_index` value `4` which leads to
> 
> ```
> 2024-06-12 05:15:02,226 test             L0941 ERROR|   File "/var/log/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-libvirt/libvirt/tests/src/backingchain/blockcommit/check_allocation_watermark_during_blockcommit.py", line 77, in _compare_alloc
>     changing_alloc, alloc_value, new_alloc[changing_index]))
> 
> 2024-06-12 05:15:02,226 test             L0941 ERROR| KeyError: '4'
> ```

I now got all tests passing in the following way:

1. Write 400MB instead of 200MB: I think the actual size (bs, count) should become configurable, s. comment
2. I had to  manually enable 'virt_use_nfs', that is 'setsebool virt_use_nfs=on'. Isn't the test code doing this automatically? I have seen other tests doing this automatically during test setup with the SELinuxBoolean object in avocado-vt/virttest/test_setup/storage.py, s. https://github.com/autotest/tp-libvirt/blob/master/libvirt/tests/cfg/svirt/shared_storage/svirt_nfs_disk.cfg#L6

2024-06-12 09:40 UTC, smitterl requested changes
Hi @nanli1 please check my comments. I think we should address two more points:
1. Make sure nfs is allowed for by selinux
2. Make the data size that's written configurable by moving it to the cfg file.

2024-06-12 09:40 UTC, smitterl commented on libvirt/tests/src/backingchain/blockcommit/check_allocation_watermark_during_blockcommit.py
> +                                      count='100')
Given that the size of the written data might need to be increased, please move this to the cfg so we can update it more easily and don't need to touch the code.

2024-06-12 14:57 UTC, nanli1 commented on libvirt/tests/src/backingchain/blockcommit/check_allocation_watermark_during_blockcommit.py
> +                                      count='100')
Thanks your patience , Sebas , Updated

2024-06-12 14:58 UTC, nanli1 commented on libvirt/tests/src/backingchain/blockcommit/check_allocation_watermark_during_blockcommit.py
> +        def _compare_alloc():
Sorry ,Not understand correctly, Updated now :D

2024-06-12 14:58 UTC, nanli1 commented
> Hi @nanli1 please check my comments. I think we should address two more points:
> 
> 1. Make sure nfs is allowed for by selinux
> 2. Make the data size that's written configurable by moving it to the cfg file.

Updated as your comment, Please review :D

2024-06-13 04:25 UTC, nanli1 commented
@smitterl Enable nfs by  the below code, Please review again : D
```
     if params.get("virt_use_nfs"):
            selinux_bool = utils_misc.SELinuxBoolean(params)
            selinux_bool.setup_local()
```

2024-06-13 08:12 UTC, smitterl commented
> @smitterl Enable nfs by the below code, Please review again : D
> 
> ```
>      if params.get("virt_use_nfs"):
>             selinux_bool = utils_misc.SELinuxBoolean(params)
>             selinux_bool.setup_local()
> ```

不好意思 I might have misunderstood, you are right, this shouldn't be necessary. Just defining the variables

```
    storage_type = nfs
    local_boolean_varible = 'virt_use_nfs'
    setup_local_nfs = "yes"
    nfs_mount_src = "/var/lib/avocado/data/avocado-vt/images"
    nfs_mount_dir = "/var/lib/libvirt/nfs_dir"
    nfs_mount_options = "rw"
    export_ip = "*"
    export_dir = "/var/lib/avocado/data/avocado-vt/images"
    local_boolean_value = "on"
```
 should suffice I assume. I didn't see those in my last review but I think they are there now. They should cause the avocado-vt/virttest/test_setup.py to do the rest.

Please remove these lines again and I'll rerun on my system. Thank you

2024-06-14 01:30 UTC, nanli1 commented
@smitterl Hi Sebas, Updated, Please help re-review :D

2024-06-19 08:30 UTC, smitterl approved these changes
works well now, thank you very much

2024-07-01 02:08 UTC, dzhengfy approved these changes
LGTM

2024-07-01 02:08 UTC, merged