Fix  Link state isn't up in guest
autotest/tp-libvirt pull request #5665
Opened 2024-06-03 12:37 UTC by chunfuwen

In some extreme case, the timeout is not enough

2024-06-03 12:50 UTC, chunfuwen commented
virsh.domif_setlink_getlink.positive_test.virtio.interface_mac.no_config.domain_name.running_guest.domif_setlink.setlink_down failed

2024-06-03 12:50 UTC, chunfuwen commented
@smitterl

2024-06-03 12:50 UTC, chunfuwen commented
@yalzhang

2024-06-04 12:57 UTC, smitterl requested changes
On my system this doesn't solve the issue (I applied the patch). Also, manually even after more than 1min I still didnt' see a change in the link state.

```
# avocado run --test-runner runner --vt-type libvirt --vt-machine-type s390-virtio --vt-connect-uri qemu:///system virsh.domif_setlink_getlink.positive_test.virtio.interface_mac.no_config.domain_name.running_guest.domif_setlink.setlink_down 
JOB ID     : 69b09ff435564360054c2b14119c892bef0a2140
JOB LOG    : /var/lib/avocado/job-results/job-2024-06-04T08.54-69b09ff/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virsh.domif_setlink_getlink.positive_test.virtio.interface_mac.no_config.domain_name.running_guest.domif_setlink.setlink_down:  FAIL: Link state isn't up in guest (70.54 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/lib/avocado/job-results/job-2024-06-04T08.54-69b09ff/results.html
JOB TIME   : 70.80 s
```

2024-06-04 23:47 UTC, yalzhang commented
> On my system this doesn't solve the issue (I applied the patch). Also, manually even after more than 1min I still didnt' see a change in the link state.
> 
> ```
> # avocado run --test-runner runner --vt-type libvirt --vt-machine-type s390-virtio --vt-connect-uri qemu:///system virsh.domif_setlink_getlink.positive_test.virtio.interface_mac.no_config.domain_name.running_guest.domif_setlink.setlink_down 
> JOB ID     : 69b09ff435564360054c2b14119c892bef0a2140
> JOB LOG    : /var/lib/avocado/job-results/job-2024-06-04T08.54-69b09ff/job.log
>  (1/1) type_specific.io-github-autotest-libvirt.virsh.domif_setlink_getlink.positive_test.virtio.interface_mac.no_config.domain_name.running_guest.domif_setlink.setlink_down:  FAIL: Link state isn't up in guest (70.54 s)
> RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
> JOB HTML   : /var/lib/avocado/job-results/job-2024-06-04T08.54-69b09ff/results.html
> JOB TIME   : 70.80 s
> ```

after our analysis, this is a bug on s390x. So this fix is not needed anymore, what do you think? @chunfuwen

2024-06-05 00:50 UTC, chunfuwen commented
this PR is not needed any more

2024-06-05 00:50 UTC, closed without merging