Fix set memory deviation issue
autotest/tp-libvirt pull request #5666
Opened 2024-06-03 12:48 UTC by chunfuwen

In some nested virtualization such as s390x, it needs
more time to settle guest memory

2024-06-03 12:51 UTC, chunfuwen commented
virsh.setmem.valid_options.running.half_mem.domid.dom_arg_size_arg.cmd_flag_current.manipulate_action.none.no_action  failed

2024-06-04 12:39 UTC, smitterl commented
I could reproduce the issue this on an LPAR, not nested. However, when testing manually, the memory inside the guest is never updated, even after a couple of minutes.

2024-06-04 12:53 UTC, smitterl requested changes
This doesn't seem to be working on my environment.

2024-06-05 00:51 UTC, chunfuwen commented
close it and it looks like it can not resolve the issue

2024-06-05 00:51 UTC, closed without merging