migration: Fix stress package issue
autotest/tp-libvirt pull request #5702
Opened 2024-06-18 08:02 UTC by cliping

There is no stress package in the latest repo. So we need to compile the stress package as a workaround.

2024-06-18 08:11 UTC, cliping commented
Before:
TestError: Installation failed with output: checking for a BSD-compatible install... /usr/bin/install -cchecking whether build environment is sane... yeschecking for a thread-safe mkdir -p... /usr/bin/mkdir -pchecking for gawk... gawkchecking whether make sets $(MAKE)... nochecking for gcc... nochecking for cc... nochecking for cl.exe... noconfigure: error: in `/home/stress-1.0.4':configure: error: no acceptable C compiler found in $PATHSee `config.log' for more details.

After:
 (1/1) type_specific.io-github-autotest-libvirt.migration.migration_uri.network_data_transport.tcp.migration_port_reuse.abort_migration.p2p: PASS (312.90 s)

2024-06-20 02:11 UTC, Yingshun requested changes

2024-06-20 02:11 UTC, Yingshun commented on libvirt/tests/src/migration/live_migration.py
> +                params.update({"stress_dependency_packages_list": "['gcc', 'make']"})
In the code, I can see it'll try to install the rpm package firtst, if it fails, go to the steps to compile the source tarball. So I think we should keep 'stress_install_from_repo' to yes and update the dependency packages.
The package "make' and "gcc" are basic ones, should we set them as a default value?

https://github.com/avocado-framework/avocado-vt/blob/master/virttest/utils_test/__init__.py#L2414C9-L2438C1

2024-07-01 08:16 UTC, cliping commented on libvirt/tests/src/migration/live_migration.py
> +                params.update({"stress_dependency_packages_list": "['gcc', 'make']"})
Since the issue of missing stress package has been solved in ci, so close this PR. Thanks.

2024-07-01 08:17 UTC, closed without merging