add case for virtio memory dynamic slots
autotest/tp-libvirt pull request #5703
Opened 2024-06-19 03:56 UTC by nanli1

xxxx-300535:Dynamic memory slots for virtio-mem device
Signed-off-by: nanli <nanli@redhat.com>
```

 avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.devices.virtio_mem.dynamic_slots
 (01/12) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.dynamic_slots.default_mb.undefined_dynamic_memory_slots.basic_virtio: PASS (72.83 s)
 (02/12) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.dynamic_slots.default_mb.enable_dynamic_memory_slots.basic_virtio: PASS (98.43 s)
 (03/12) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.dynamic_slots.default_mb.disable_dynamic_memory_slots.basic_virtio: PASS (73.02 s)
 (04/12) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.dynamic_slots.file_mb.undefined_dynamic_memory_slots.basic_virtio: PASS (73.44 s)
 (05/12) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.dynamic_slots.file_mb.enable_dynamic_memory_slots.basic_virtio: PASS (73.26 s)
 (06/12) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.dynamic_slots.file_mb.disable_dynamic_memory_slots.basic_virtio: PASS (73.21 s)
 (07/12) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.dynamic_slots.hugepages_mb.undefined_dynamic_memory_slots.basic_virtio: PASS (73.40 s)
 (08/12) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.dynamic_slots.hugepages_mb.enable_dynamic_memory_slots.basic_virtio: PASS (73.47 s)
 (09/12) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.dynamic_slots.hugepages_mb.disable_dynamic_memory_slots.basic_virtio: PASS (73.53 s)
 (10/12) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.dynamic_slots.memfd_mb.undefined_dynamic_memory_slots.basic_virtio: PASS (74.24 s)
 (11/12) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.dynamic_slots.memfd_mb.enable_dynamic_memory_slots.basic_virtio: PASS (73.13 s)
 (12/12) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.dynamic_slots.memfd_mb.disable_dynamic_memory_slots.basic_virtio: PASS (73.02 s)

```

2024-07-12 01:58 UTC, dzhengfy commented
@liang-cong-red-hat Could you help to review? thanks

2024-07-12 02:09 UTC, liang-cong-red-hat requested changes
Others LGTM

2024-07-12 02:09 UTC, liang-cong-red-hat commented on libvirt/tests/src/memory/memory_devices/virtio_mem_dynamic_slots.py
> +        test.log.info("TEST_SETUP: Allocate huge page memory")
log info should move after if.

2024-07-12 02:09 UTC, liang-cong-red-hat commented on libvirt/tests/src/memory/memory_devices/virtio_mem_dynamic_slots.py
> +        utils_memory.set_num_huge_pages(0)
here should add if memory_backing == "hugepages_mb" like setup part.

2024-07-12 06:44 UTC, dzhengfy commented on libvirt/tests/src/memory/memory_devices/virtio_mem_dynamic_slots.py
> +            utils_memory.set_num_huge_pages(allocate_size/default_hugepage_size)
Could you use HugePageConfig class to setup hugepage because the functions are robuster than  utils_memory class. For exameple, there is no checking for the hugepage number setupped.

2024-07-12 06:44 UTC, dzhengfy commented on libvirt/tests/src/memory/memory_devices/virtio_mem_dynamic_slots.py
> +    virtio_dict = eval(params.get('virtio_dict') % default_hugepage_size)
To be honest, I am a little bit confused with the naming 'virtio'. I think it is better with virtio_mem_dict, or mem_dict because `virtio` usually stands for the device bus, not a device.

2024-07-12 06:44 UTC, dzhengfy commented on libvirt/tests/src/memory/memory_devices/virtio_mem_dynamic_slots.py
> +def get_vm_attrs(test, params):
I feel this is to update vm  attrs.

2024-07-12 06:44 UTC, dzhengfy commented on libvirt/tests/src/memory/memory_devices/virtio_mem_dynamic_slots.py
> +    mb = eval("{'mb':{%s}}" % mb_value[:-1])
BTW, couldn't we directly define a parameter in cfg with expected mb value?

2024-07-12 06:44 UTC, dzhengfy commented on libvirt/tests/src/memory/memory_devices/virtio_mem_dynamic_slots.py
> +        vmxml.sync()
You can reuse `memory_base.define_guest_with_memory_device()`

2024-07-12 06:44 UTC, dzhengfy commented on libvirt/tests/src/memory/memory_devices/virtio_mem_dynamic_slots.py
> +        utils_memory.set_num_huge_pages(0)
Consider to use `HugePageConfig()`

2024-07-12 06:44 UTC, dzhengfy commented on libvirt/tests/src/memory/memory_devices/virtio_mem_dynamic_slots.py
> +    memory_base.check_supported_version(params, test, vm)
Please move up this line as many as possible

2024-07-14 14:19 UTC, nanli1 commented on libvirt/tests/src/memory/memory_devices/virtio_mem_dynamic_slots.py
> +    if actual_machine_version < machine_version:
Thank you all, Updated

2024-07-14 14:19 UTC, nanli1 commented on libvirt/tests/src/memory/memory_devices/virtio_mem_dynamic_slots.py
> +        test.log.info("TEST_SETUP1: Define guest with virtio memory")
Thanks lcong, Updated

2024-07-14 14:19 UTC, nanli1 commented on libvirt/tests/src/memory/memory_devices/virtio_mem_dynamic_slots.py
> +        test.log.info("TEST_SETUP: Allocate huge page memory")
Thanks lcong,Updated

2024-07-14 14:20 UTC, nanli1 commented on libvirt/tests/src/memory/memory_devices/virtio_mem_dynamic_slots.py
> +        utils_memory.set_num_huge_pages(0)
Thanks lcong,Updated

2024-07-14 14:20 UTC, nanli1 commented on libvirt/tests/src/memory/memory_devices/virtio_mem_dynamic_slots.py
> +            utils_memory.set_num_huge_pages(allocate_size/default_hugepage_size)
Thank you dzheng, Updated

2024-07-14 14:20 UTC, nanli1 commented on libvirt/tests/src/memory/memory_devices/virtio_mem_dynamic_slots.py
> +    virtio_dict = eval(params.get('virtio_dict') % default_hugepage_size)
Thank you dzheng, Updated

2024-07-14 14:20 UTC, nanli1 commented on libvirt/tests/src/memory/memory_devices/virtio_mem_dynamic_slots.py
> +def get_vm_attrs(test, params):
Thank you dzheng, Updated

2024-07-14 14:26 UTC, nanli1 commented on libvirt/tests/src/memory/memory_devices/virtio_mem_dynamic_slots.py
> +    mb = eval("{'mb':{%s}}" % mb_value[:-1])
hi dzheng,Thanks your comment, But it's a little complex here, we have many condition ,such as 
```
source_attr exists , but hugepages_attr not exists ,
source_attr not exists , but hugepages_attr  exists
both exists
both unexists
....
```
I don't confirm how to combine is ok, the comma always influence mb attr `{'mb':{source_attr, hugepages_attr}}"`

2024-07-14 14:28 UTC, nanli1 commented on libvirt/tests/src/memory/memory_devices/virtio_mem_dynamic_slots.py
> +        vmxml.sync()
Thank you dzheng, Updated

2024-07-14 14:28 UTC, nanli1 commented on libvirt/tests/src/memory/memory_devices/virtio_mem_dynamic_slots.py
> +        utils_memory.set_num_huge_pages(0)
Thank you dzheng, Updated

2024-07-14 14:28 UTC, nanli1 commented on libvirt/tests/src/memory/memory_devices/virtio_mem_dynamic_slots.py
> +    memory_base.check_supported_version(params, test, vm)
Thank you dzheng, Updated

2024-07-15 02:33 UTC, liang-cong-red-hat approved these changes
LGTM

2024-07-18 02:51 UTC, dzhengfy approved these changes
LGTM

2024-07-18 02:52 UTC, merged