virsh/nodedev: fix chain test
autotest/tp-libvirt pull request #5707
Opened 2024-06-20 11:13 UTC by smitterl

1. Fix test name, subtest should be nodedev_dumpxml.chain for better discoverability and set definition.
2. Update test to run against a specific device.
3. Allow for a list of devices to be physically present. The test will configure the first one to establish the test precondition.

2024-06-20 11:14 UTC, smitterl commented
```
JOB ID     : 099aa3b3f61565498caf1982c55c0fe4f526b3c7
JOB LOG    : /var/log/avocado/job-results/job-2024-06-20T07.09-099aa3b/job.log
 (1/2) type_specific.io-github-autotest-libvirt.virsh.nodedev_dumpxml.chain.device_type_dasd: PASS (5.54 s)
 (2/2) type_specific.io-github-autotest-libvirt.virsh.nodedev_dumpxml.chain.device_type_css: PASS (5.55 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/log/avocado/job-results/job-2024-06-20T07.09-099aa3b/results.html
JOB TIME   : 11.39 s
```

2024-06-25 08:00 UTC, chunfuwen commented on libvirt/tests/cfg/virsh_cmd/nodedev/virsh_nodedev_dumpxml_chain.cfg
> +- virsh.nodedev_dumpxml.chain:
this change impacts case pattern in our jobs.config. Do we really need change this?

2024-06-25 08:35 UTC, smitterl commented on libvirt/tests/cfg/virsh_cmd/nodedev/virsh_nodedev_dumpxml_chain.cfg
> +- virsh.nodedev_dumpxml.chain:
Yes, it's better in the long run. This is only run on s390x so the change in our local jobs configuration is rather small in comparison with the benefit it brings IMO

2024-07-18 01:20 UTC, chunfuwen approved these changes
lgtm

2024-07-29 04:41 UTC, liang-cong-red-hat requested changes
just one comment, others LGTM

2024-07-29 04:41 UTC, liang-cong-red-hat commented on libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_dumpxml_chain.py
> +        if device and device[paths.HEADER["Use"]] != "yes":
is it device[paths.HEADER["Use"]] == "yes" ?

2024-07-29 06:03 UTC, smitterl commented on libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_dumpxml_chain.py
> +        if device and device[paths.HEADER["Use"]] != "yes":
Yes, this corresponds to the previous step of setting the devices online:
https://github.com/autotest/tp-libvirt/blob/a49c45ce4c9ef0ae6c12eaa557388e4e06701939/libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_dumpxml_chain.py#L28C8-L29C66

2024-07-29 06:04 UTC, smitterl commented on libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_dumpxml_chain.py
> +        if device and device[paths.HEADER["Use"]] != "yes":
Yes, you're right. Updated. Thanks!

2024-07-29 07:05 UTC, liang-cong-red-hat approved these changes

2024-08-09 10:04 UTC, merged