viommu: Add a test scenario about 'virsh reset'
autotest/tp-libvirt pull request #5860
Opened 2024-08-27 06:48 UTC by Yingshun

This pr adds 'virsh reset' into viommu lifecycle testing.

2024-08-28 11:45 UTC, smitterl requested changes
A couple of questions, please check, thanks.

2024-08-28 11:45 UTC, smitterl commented on libvirt/tests/src/sriov/vIOMMU/iommu_device_lifecycle.py
> +                test.log.info("TEST_STEP: Reboot the VM.")
IIUC, you need to update this string, maybe `f"TEST_STEP: Run '{virsh_cmd}'"`

2024-08-28 11:45 UTC, smitterl commented on libvirt/tests/src/sriov/vIOMMU/iommu_device_lifecycle.py
> +                    session.sendline(params.get("reboot_command"))
Has this ever worked? The variant 'reboot_command' should return None or "". Given that this test case seems to be a PASS before, I assume it's "" and therefore nothing is really executed but I might be wrong.

2024-08-28 11:45 UTC, smitterl commented on libvirt/tests/src/sriov/vIOMMU/iommu_device_lifecycle.py
> +            if virsh_cmd:
These three lines can be removed IIUC. You just want to `session.close()` at the end of both cases `if...else` .

2024-08-28 11:45 UTC, smitterl commented on libvirt/tests/src/sriov/vIOMMU/iommu_device_lifecycle.py
> +                test.log.info("TEST_STEP: Reboot the VM.")
IIUC, there are two different test cases: reboot and reset. The reboot is expected to be triggered in the guest (s. line below) and the reset from host (virsh). Now, if you instead of introducing a variable 'virsh_cmd' only for reset would use a new one:

```
- reset:
  cmd = 'virsh.reset'
- reboot:
  cmd = 'session.reboot'
```
You could just write `f"TEST_STEP: Run {cmd}"`. Furthermore:
```
if cmd.startswith("session"):
    command = lambda: session.sendline(cmd.split(".")[1])
elif cmd.startswith("virsh"):
    command = lambda: eval(cmd)(vm.name, **VIRSH_ARGS)
command()
```

2024-08-28 11:45 UTC, smitterl commented on libvirt/tests/src/sriov/vIOMMU/iommu_device_lifecycle.py
>              session = vm.wait_for_serial_login(
You just closed the session in the previous line in all cases, wouldn't it make sense to reuse the session instead of creating a new one?

2024-08-29 02:34 UTC, Yingshun commented on libvirt/tests/src/sriov/vIOMMU/iommu_device_lifecycle.py
> +                    session.sendline(params.get("reboot_command"))
Yes, of course. It's in guest-os cfg in vt.

2024-08-29 02:36 UTC, Yingshun commented on libvirt/tests/src/sriov/vIOMMU/iommu_device_lifecycle.py
> +            if virsh_cmd:
No, in this case, if we restart the vm using shell command in vm, the session will be got stuck and have to recreate one before using it.

2024-08-29 02:40 UTC, Yingshun commented on libvirt/tests/src/sriov/vIOMMU/iommu_device_lifecycle.py
> +                test.log.info("TEST_STEP: Reboot the VM.")
It looks like the current logic is complex and as you said, they are different test cases, so I'd like to split them as different test scenario.
Actually, we have several ways to reboot the guest, but the feature owner kept using shell command in vm(but not using 'virsh.reboot'), so the code looks a little bit different with other lifecycle scenario.

2024-08-29 02:44 UTC, Yingshun commented on libvirt/tests/src/sriov/vIOMMU/iommu_device_lifecycle.py
>              session = vm.wait_for_serial_login(
Same as above, the vm session will be hang if rebooting using shell command line in vm, so I have to recreate it. And for virsh.reset I need to login to system, so I prefer recreating it.

2024-09-04 02:44 UTC, meinaLi approved these changes

2024-09-04 09:44 UTC, smitterl commented on libvirt/tests/src/sriov/vIOMMU/iommu_device_lifecycle.py
> +                    session.sendline(params.get("reboot_command"))
Got it, thanks for clarifying.

2024-09-04 09:52 UTC, smitterl approved these changes
LGTM thank you!

2024-09-04 09:52 UTC, smitterl commented on libvirt/tests/src/sriov/vIOMMU/iommu_device_lifecycle.py
>              session = vm.wait_for_serial_login(
Thanks for clarifying.

2024-09-04 09:52 UTC, smitterl commented on libvirt/tests/src/sriov/vIOMMU/iommu_device_lifecycle.py
> +            if virsh_cmd:
I didn't question you had to recreate it. It just looked like you closed the session at the end of two ramifications and could just have closed it at the end of both saving code. Anyhow, it doesn't apply anymore :)

2024-09-04 09:52 UTC, smitterl commented on libvirt/tests/src/sriov/vIOMMU/iommu_device_lifecycle.py
> +                test.log.info("TEST_STEP: Reboot the VM.")
Hi, I didn't mean to imply you create a single test scenario I was proposing another way to organize the code that would have reduced the current complexity as I saw it.

2024-09-05 02:29 UTC, Yingshun commented on libvirt/tests/src/sriov/vIOMMU/iommu_device_lifecycle.py
> +                test.log.info("TEST_STEP: Reboot the VM.")
Yes, I understand, I agree that your suggestion is quite good. I've been struggling whether to take them apart:)

2024-09-05 05:40 UTC, merged