viommu: Add a case for file transfers
autotest/tp-libvirt pull request #5861
Opened 2024-08-27 07:04 UTC by Yingshun

This PR adds:
    VIRT-301880: Transfer a file between host and vm with iommu device

**Test results:**
```
 (1/2) type_specific.io-github-autotest-libvirt.vIOMMU.transfer_file.virtio_interface.virtio: PASS (79.73 s)
 (2/2) type_specific.io-github-autotest-libvirt.vIOMMU.transfer_file.virtio_interface.smmuv3: PASS (49.39 s)
```

2024-08-28 11:29 UTC, smitterl requested changes
A minor nitpick in test case naming, rest LGTM thank you.

2024-08-28 11:29 UTC, smitterl commented on libvirt/tests/cfg/sriov/vIOMMU/viommu_transfer_file.cfg
> +- vIOMMU.transfer_file:
Better use 'viommu'. There's no written rule about it but I've only seen lower case used ever and if searching for available tests I'd ever only use lower-case (e.g. avocado list...|grep). IMO, 'vIOMMU' can also lead to errors when updating CI job files (what if somebody writes VIOMMU or vlOMMU accidentally?)

2024-08-28 11:32 UTC, smitterl commented on libvirt/tests/cfg/sriov/vIOMMU/viommu_transfer_file.cfg
> +- vIOMMU.transfer_file:
I see that vIOMMU is already being used, would it be okay to change all instances to 'viommu'?

2024-08-29 02:52 UTC, Yingshun commented on libvirt/tests/cfg/sriov/vIOMMU/viommu_transfer_file.cfg
> +- vIOMMU.transfer_file:
Hi @smitterl, thanks for your suggestion!
I think 'vIOMMU' is really a formal name and also you can use '-i' when searching via 'grep'. And I can also see some cases' name in tp-qemu have upper-case as below:
`(30/38) virtio_iommu.Host_RHEL.m9.u5.v0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.aarch64.page_4k.io-github-autotest-qemu.netperf_stress_test.TCP_STREAM.guest2guest.arm64-pci: PASS (236.83 s)
`
Furthermore, we need to update the related items in caselink and jira manually if we change the name. So I'd like to keep it the way it is unless it's absolutely necessary.

2024-09-02 02:15 UTC, nanli1 approved these changes

2024-09-02 02:43 UTC, meinaLi commented on libvirt/tests/src/sriov/vIOMMU/viommu_transfer_file.py
> +        iface_dict = test_obj.parse_iface_dict()
Maybe we don't need this step and only use `iface_dict= eval(params.get('iface_dict', '{}'))`? We don't deal with the controllers in these test scenarios. So I think use parse_iface_dict() may make the step complicate in understanding.

2024-09-02 02:43 UTC, meinaLi commented on libvirt/tests/src/sriov/vIOMMU/viommu_transfer_file.py
> +        vm.start()
VIRSH_ARGS is not used in this script. I think we can use it in here.

2024-09-02 03:05 UTC, Yingshun commented on libvirt/tests/src/sriov/vIOMMU/viommu_transfer_file.py
> +        iface_dict = test_obj.parse_iface_dict()
Hi @meinaLi Thanks for your review! For the way to get the interface settings, I prefer to manage it uniformly to reduce the maintenance cost. What do you think?

2024-09-02 03:07 UTC, Yingshun commented on libvirt/tests/src/sriov/vIOMMU/viommu_transfer_file.py
> +        vm.start()
@meinaLi  I dont think vm object can accept 'VIRSH_ARGS', do you mean change it to 'virsh.start'?

2024-09-02 05:47 UTC, Yingshun commented on libvirt/tests/src/sriov/vIOMMU/viommu_transfer_file.py
> +        iface_dict = test_obj.parse_iface_dict()
removed.

2024-09-02 05:48 UTC, Yingshun commented on libvirt/tests/src/sriov/vIOMMU/viommu_transfer_file.py
> +        vm.start()
removed. thx!

2024-09-02 06:08 UTC, meinaLi approved these changes

2024-09-23 01:40 UTC, Yingshun commented
All comments have been processed. Iommu's name has been discussed with dzheng and we don't plan to modify it at the moment, so merge this PR first.

2024-09-23 01:40 UTC, merged