vcpu_metrics: handle missing element
autotest/tp-libvirt pull request #5887
Opened 2024-09-09 07:23 UTC by smitterl

//os/loader* might not exist on the domain definition leading to an exception. In this case, skip the step that tries to remove those attributes.

2024-09-09 07:23 UTC, smitterl commented
@liang-cong-red-hat please help review

2024-09-10 07:56 UTC, liang-cong-red-hat requested changes

2024-09-10 07:56 UTC, liang-cong-red-hat commented on libvirt/tests/src/cpu/vcpu_metrics.py
> +        vmxml.os = libvirt_bios.remove_bootconfig_items_from_vmos(vmxml.os)
libvirt_bios.remove_bootconfig_items_from_vmos could move out of try...except block.

2024-09-13 02:16 UTC, liang-cong-red-hat approved these changes
LGTM

2024-09-18 01:38 UTC, cliping approved these changes

2024-09-20 11:41 UTC, chloerh approved these changes

2024-09-20 11:41 UTC, merged