SRIOV: add new test scenarios for vIOMMU
autotest/tp-libvirt pull request #5937
Opened 2024-10-11 06:02 UTC by meinaLi

Automate new dma_translation attribute for vIOMMU: 
VIRT-294818 - [vIOMMU] Hotplug or coldplug iommu device to guest 
VIRT-294818 - [vIOMMU] Start vm with iommu device

2024-10-11 06:03 UTC, meinaLi commented
```
# avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 vIOMMU.iommu_device_settings..intel
JOB ID     : 758b6911ec2381a2f01846ed9ab84c0bae470a4f
JOB LOG    : /var/log/avocado/job-results/job-2024-10-10T22.41-758b691/job.log
 (01/16) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_settings.e1000e.virtio:PASS (40.62 s)
 (02/16) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_settings.e1000e.intel: PASS (165.87 s)
 (03/16) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_settings.rtl8139.virtio: PASS (41.68 s)
......
 (16/16) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_settings.pcie_root_port_from_expander_bus.intel: PASS (276.34 s)
Not opening readers, lock_server_running not locked
Not opening readers, lock_server_running not locked
RESULTS    : PASS 16 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/log/avocado/job-results/job-2024-10-10T22.41-758b691/results.html
JOB TIME   : 1900.18 s

# avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 vIOMMU.attach_iommu_device..intel
JOB ID     : bb1c851cd27ddcfecb9357d64bf30ba07b033cb3
JOB LOG    : /var/log/avocado/job-results/job-2024-10-10T23.28-bb1c851/job.log
 (1/4) type_specific.io-github-autotest-libvirt.vIOMMU.attach_iommu_device.cold_plug.virtio: PASS (8.14 s)
 (2/4) type_specific.io-github-autotest-libvirt.vIOMMU.attach_iommu_device.cold_plug.intel: PASS (8.45 s)
 (3/4) type_specific.io-github-autotest-libvirt.vIOMMU.attach_iommu_device.hot_plug.virtio: PASS (28.88 s)
 (4/4) type_specific.io-github-autotest-libvirt.vIOMMU.attach_iommu_device.hot_plug.intel: PASS (37.56 s)
RESULTS    : PASS 4 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/log/avocado/job-results/job-2024-10-10T23.28-bb1c851/results.html
JOB TIME   : 84.85 s
```

2024-10-15 08:32 UTC, chunfuwen commented on libvirt/tests/src/sriov/vIOMMU/attach_iommu_device.py
> +            iommu_dict['driver']['dma_translation'] = 'on'
dma_translation  is new feature, so maybe create separate case under intel variant of ./libvirt/tests/cfg/sriov/vIOMMU/attach_iommu_device.cfg , otherwise it is easy to ignore this feature if still under previous test case.

2024-10-22 08:36 UTC, meinaLi commented on libvirt/tests/src/sriov/vIOMMU/attach_iommu_device.py
> +            iommu_dict['driver']['dma_translation'] = 'on'
I've considered whether we need to add a new case. But after the evaluation I gave up because:
1) Keep the same attributes strategy as before in plan.
2) This new attribute is not so important because before it was enabled default.
Certainly it can also reduce our debug workloads.

2024-10-23 02:23 UTC, chunfuwen approved these changes
lgtm

2024-10-23 07:03 UTC, meinaLi commented
@Yingshun Could you help review this PR? Thanks.

2024-10-25 08:35 UTC, Yingshun requested changes
As discussed offline, it's better to add it to intel iommu cases or create a new one.

2024-10-31 06:28 UTC, meinaLi commented
```
# avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 vIOMMU.intel_iommu_with_dma_translation
JOB ID     : d23c0f2bac019be9d0c4153cb80a230cb4250c40
JOB LOG    : /var/lib/avocado/job-results/job-2024-10-31T01.29-d23c0f2/job.log
 (1/3) type_specific.io-github-autotest-libvirt.vIOMMU.intel_iommu_with_dma_translation.enable_dma_translation: PASS (209.04 s)
 (2/3) type_specific.io-github-autotest-libvirt.vIOMMU.intel_iommu_with_dma_translation.disable_dma_translation: PASS (208.03 s)
 (3/3) type_specific.io-github-autotest-libvirt.vIOMMU.intel_iommu_with_dma_translation.disable_dma_translation_with_more_vcpus: PASS (841.30 s)
Not opening readers, lock_server_running not locked
Not opening readers, lock_server_running not locked
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/lib/avocado/job-results/job-2024-10-31T01.29-d23c0f2/results.html
JOB TIME   : 1259.86 s
```

2024-11-01 11:14 UTC, Yingshun commented on libvirt/tests/src/sriov/vIOMMU/intel_iommu_with_dma_translation.py
> +        vmxml = vm_xml.VMXML.new_from_dumpxml(vm_name)
It's only used for L27-29, I think it can be moved into the if statement.

2024-11-01 11:14 UTC, Yingshun commented on libvirt/tests/src/sriov/vIOMMU/intel_iommu_with_dma_translation.py
> +        virsh.start(vm_name, debug=True)
It's better to use vm.start which will raise exceptions if the startup fails.

2024-11-01 11:14 UTC, Yingshun commented on libvirt/tests/src/sriov/vIOMMU/intel_iommu_with_dma_translation.py
> +        vm_session = vm.wait_for_serial_login(timeout=6000)
Why do we expect the timeout to be so long? 6000s is too long in my opinion, what do you think?

2024-11-01 11:14 UTC, Yingshun commented on libvirt/tests/src/sriov/vIOMMU/intel_iommu_with_dma_translation.py
> +            test.fail("Can't get expected message result when disabling dma_translation.")
It's better to log the outputs of above 2 shell commands - 'dmesg | xxx'

2024-11-01 11:14 UTC, Yingshun commented on libvirt/tests/src/sriov/vIOMMU/intel_iommu_with_dma_translation.py
> +                test.fail("Can't get expected vCPU number, the actual number is %s" % type(o))
type(o) to 'o'?

2024-11-05 03:00 UTC, meinaLi commented on libvirt/tests/src/sriov/vIOMMU/intel_iommu_with_dma_translation.py
> +    libvirt_version.is_libvirt_feature_supported(params)
Removed it now.

2024-11-05 03:00 UTC, meinaLi commented on libvirt/tests/cfg/sriov/vIOMMU/intel_iommu_with_dma_translation.cfg
> +    iommu_dict = {'model': 'intel', 'driver': {'intremap': 'on', 'caching_mode': 'on', 'iotlb': 'on', 'dma_translation': '%s'}}
Yes, it can also be at the end of this file.

2024-11-05 03:01 UTC, meinaLi commented on libvirt/tests/src/sriov/vIOMMU/intel_iommu_with_dma_translation.py
> +        vmxml = vm_xml.VMXML.new_from_dumpxml(vm_name)
Moved it now.

2024-11-05 03:01 UTC, meinaLi commented on libvirt/tests/src/sriov/vIOMMU/intel_iommu_with_dma_translation.py
> +        virsh.start(vm_name, debug=True)
Changed to use vm.start().

2024-11-05 03:02 UTC, meinaLi commented on libvirt/tests/src/sriov/vIOMMU/intel_iommu_with_dma_translation.py
> +        vm_session = vm.wait_for_serial_login(timeout=6000)
Because when we start guest with 256 vCPUs, it may take long time to login the guest. Based on this scenario, I extended the timeout.

2024-11-05 03:03 UTC, meinaLi commented on libvirt/tests/src/sriov/vIOMMU/intel_iommu_with_dma_translation.py
> +            test.fail("Can't get expected message result when disabling dma_translation.")
Updated now.

2024-11-05 03:03 UTC, meinaLi commented on libvirt/tests/src/sriov/vIOMMU/intel_iommu_with_dma_translation.py
> +                test.fail("Can't get expected vCPU number, the actual number is %s" % type(o))
Yes, just a mistake in my debugging. I forgot to restore it before.

2024-12-06 05:11 UTC, Yingshun commented on libvirt/tests/src/sriov/vIOMMU/intel_iommu_with_dma_translation.py
> +        vm_session = vm.wait_for_serial_login(timeout=6000)
(3/3) type_specific.io-github-autotest-libvirt.vIOMMU.intel_iommu_with_dma_translation.disable_dma_translation_with_more_vcpus: PASS (841.30 s)

From the test result, it takes 840s for entire testing, I don't think 6000s is a reasonable value, can you plz recheck it?

2024-12-11 12:06 UTC, meinaLi commented on libvirt/tests/src/sriov/vIOMMU/intel_iommu_with_dma_translation.py
> +        vm_session = vm.wait_for_serial_login(timeout=6000)
I mistakenly took 6000 as 10 minutes. I've changed to 1000 now. This case may have different consume time for different machines. So I think 1000 is enough.

2024-12-13 02:33 UTC, merged