guest_os_booting: disable test cases on s390x
autotest/tp-libvirt pull request #5985
Opened 2024-11-07 11:42 UTC by smitterl

SMBIOS, ACPI, the fw_cfg device are not available on s390x. USB is not available on s390x.

Don't enable bootmenu as it will not timeout automatically. Use scsi target bus for now, not sure at this point if virtio-blk is covered, too.

Don't configure firmware on s390x, just return the first VM.

<boot dev.../> is not supported on s390x, disable tests.

For direct kernel boot, don't use hard coded kernel filename. In our setup we'll use kernel.img, so just use the filename from the download url.

2024-12-23 09:35 UTC, smitterl commented
```
JOB ID     : 8199867b88399a62c814678509f70b277b004183
JOB LOG    : /var/log/avocado/job-results/job-2024-12-23T01.19-8199867/job.log
 (01/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.hotplug.disk_device: STARTED
 (01/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.hotplug.disk_device: PASS (19.47 s)
 (02/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.hotplug.usb_device: STARTED
 (02/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.hotplug.usb_device: PASS (78.05 s)
 (03/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.hotplug.filesystem_device: STARTED
 (03/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.hotplug.filesystem_device: PASS (18.03 s)
 (04/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.boot_with_multiple_boot_order.hd.cdrom.hd_bootable.default: STARTED
 (04/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.boot_with_multiple_boot_order.hd.cdrom.hd_bootable.default: PASS (19.07 s)
 (05/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.boot_with_multiple_boot_order.hd.cdrom.hd_bootable.with_loadparm: STARTED
 (05/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.boot_with_multiple_boot_order.hd.cdrom.hd_bootable.with_loadparm: PASS (48.75 s)
 (06/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.boot_with_multiple_boot_order.hd.cdrom.cdrom_bootable: STARTED
 (06/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.boot_with_multiple_boot_order.hd.cdrom.cdrom_bootable: PASS (38.48 s)
 (07/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.boot_with_multiple_boot_order.hd.network.hd_bootable: STARTED
 (07/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.boot_with_multiple_boot_order.hd.network.hd_bootable: PASS (19.83 s)
 (08/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.boot_with_multiple_boot_order.hd.network.network_bootable: STARTED
 (08/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.boot_with_multiple_boot_order.hd.network.network_bootable: PASS (118.98 s)
 (09/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.boot_with_multiple_boot_order.cdrom.hd.hd_bootable.default: STARTED
 (09/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.boot_with_multiple_boot_order.cdrom.hd.hd_bootable.default: PASS (19.24 s)
 (10/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.boot_with_multiple_boot_order.cdrom.hd.hd_bootable.with_loadparm: STARTED
 (10/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.boot_with_multiple_boot_order.cdrom.hd.hd_bootable.with_loadparm: PASS (20.26 s)
 (11/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.boot_with_multiple_boot_order.cdrom.hd.cdrom_bootable: STARTED
 (11/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.boot_with_multiple_boot_order.cdrom.hd.cdrom_bootable: PASS (38.65 s)
 (12/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.boot_with_multiple_boot_order.cdrom.network.cdrom_bootable: STARTED
 (12/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.boot_with_multiple_boot_order.cdrom.network.cdrom_bootable: PASS (68.61 s)
 (13/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.boot_with_multiple_boot_order.cdrom.network.network_bootable: STARTED
 (13/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.boot_with_multiple_boot_order.cdrom.network.network_bootable: PASS (59.72 s)
 (14/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.boot_with_multiple_boot_order.network.hd.hd_bootable.default: STARTED
 (14/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.boot_with_multiple_boot_order.network.hd.hd_bootable.default: PASS (41.31 s)
 (15/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.boot_with_multiple_boot_order.network.hd.hd_bootable.with_loadparm: STARTED
 (15/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.boot_with_multiple_boot_order.network.hd.hd_bootable.with_loadparm: PASS (71.58 s)
 (16/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.boot_with_multiple_boot_order.network.hd.network_bootable: STARTED
 (16/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.boot_with_multiple_boot_order.network.hd.network_bootable: PASS (59.77 s)
 (17/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.boot_with_multiple_boot_order.network.cdrom.cdrom_bootable: STARTED
 (17/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.boot_with_multiple_boot_order.network.cdrom.cdrom_bootable: PASS (55.10 s)
 (18/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.boot_with_multiple_boot_order.network.cdrom.network_bootable: STARTED
 (18/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.boot_with_multiple_boot_order.network.cdrom.network_bootable: PASS (89.20 s)
 (19/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.setting.negative.duplicate: STARTED
 (19/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.setting.negative.duplicate: PASS (37.64 s)
 (20/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.setting.negative.with_os_boots: STARTED
 (20/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.setting.negative.with_os_boots: PASS (37.66 s)
 (21/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.setting.negative.minus: STARTED
 (21/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.setting.negative.minus: PASS (37.70 s)
 (22/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.setting.negative.zero: STARTED
 (22/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.setting.negative.zero: PASS (7.79 s)
 (23/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.setting.negative.string: STARTED
 (23/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.setting.negative.string: PASS (8.07 s)
 (24/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.disk_device.default.disk_boot_order.single_disk: STARTED
 (24/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.disk_device.default.disk_boot_order.single_disk: PASS (59.61 s)
 (25/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.disk_device.default.disk_boot_order.multi_disks: STARTED
 (25/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.disk_device.default.disk_boot_order.multi_disks: PASS (24.88 s)
 (26/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.disk_device.default.disk_boot_order.multi_disks_bootable: STARTED
 (26/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.disk_device.default.disk_boot_order.multi_disks_bootable: FAIL: Couldn't boot correctly (240.89 s)
 (27/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.cdrom_device.default.cdrom_boot_order.with_cdrom: STARTED
 (27/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.cdrom_device.default.cdrom_boot_order.with_cdrom: PASS (67.93 s)
 (28/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.cdrom_device.default.cdrom_boot_order.multi_cdroms: STARTED
 (28/28) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.cdrom_device.default.cdrom_boot_order.multi_cdroms: PASS (39.93 s)
RESULTS    : PASS 27 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML    [...]

2025-01-14 16:40 UTC, smitterl commented
After fixing the multi_disk_bootable test case to make sure not two disk are used with identical VG names:

```
JOB ID     : dd6d9b32b7d5a036646c1a31a31515347c6a139d
JOB LOG    : /var/log/avocado/job-results/job-2025-01-14T11.32-dd6d9b3/job.log
 (1/1) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.disk_device.default.disk_boot_order.multi_disks_bootable: STARTED
 (1/1) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.disk_device.default.disk_boot_order.multi_disks_bootable:  PASS (33.59 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/log/avocado/job-results/job-2025-01-14T11.32-dd6d9b3/results.html
JOB TIME   : 34.82 s
```

2025-02-12 10:25 UTC, liang-cong-red-hat commented on libvirt/tests/cfg/guest_os_booting/boot_order/boot_from_cdrom_device.cfg
> +        - default:
since this is add for s390, so shall we add s390 only for it?

2025-02-13 03:04 UTC, liang-cong-red-hat commented on libvirt/tests/cfg/guest_os_booting/boot_order/boot_from_disk_device.cfg
> +        - default:
Same as above, is it only for s390?

2025-02-13 03:04 UTC, liang-cong-red-hat requested changes
Just 2 comments, others LGTM

2025-02-25 17:19 UTC, smitterl commented on libvirt/tests/cfg/guest_os_booting/boot_order/boot_from_cdrom_device.cfg
> +        - default:
I don't think so, ovmf and seabios refer to secure boot guests. On x86_64 and aarch64, too, there can be non-secure boot guests. AFAIK our test jobs for ovmf and seabios select these explicitly. But I will reach out to the auto-owner to get more info to see if these tests must be filtered out downstream.

2025-02-28 15:06 UTC, smitterl commented
> Just 2 comments, others LGTM

Thank you, as discussed, changed variant to `no_firmeware` and made s390x only.

2025-03-11 02:26 UTC, liang-cong-red-hat approved these changes
LGTM

2025-03-11 02:38 UTC, liang-cong-red-hat commented
I found this doc: https://www.qemu.org/docs/master/system/s390x/bootdevices.html, from this the s390 guest firmware is called "s390-ccw" bios, if it is correct, so we could change "no_firmeware" to "s390-ccw".

2025-03-13 01:44 UTC, Yingshun commented
> I found this doc: https://www.qemu.org/docs/master/system/s390x/bootdevices.html, from this the s390 guest firmware is called "s390-ccw" bios, if it is correct, so we could change "no_firmeware" to "s390-ccw".

@smitterl  Can you please double check the s390 guest firmware? Thanks!

2025-03-13 07:07 UTC, smitterl commented
> > I found this doc: https://www.qemu.org/docs/master/system/s390x/bootdevices.html, from this the s390 guest firmware is called "s390-ccw" bios, if it is correct, so we could change "no_firmeware" to "s390-ccw".
> 
> @smitterl Can you please double check the s390 guest firmware? Thanks!

Thanks for the pointer but that is the usual boot loader, no specific libvirt or qemu level firmware configuration is available. So the definition is the same as if no firmeware was set on x86_64, hence 'no_firmeware'

2025-03-14 02:37 UTC, Yingshun approved these changes

2025-03-14 02:37 UTC, merged