scsi_device: add new case of hostdev device for scsi commands testing
autotest/tp-libvirt pull request #5986
Opened 2024-11-08 10:09 UTC by meinaLi

VIRT-302167 - [Host device assignment][SCSI] SCSI command passthrough test for hostdev scsi device

2024-11-12 03:16 UTC, meinaLi commented
```
# avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 scsi_device.scsi_command_test.with_hostdev.guest_multipath
JOB ID     : 11722ca97ebee116a07bcf4af0249d7c6fc095c9
JOB LOG    : /var/lib/avocado/job-results/job-2024-11-11T21.49-11722ca/job.log
 (1/1) type_specific.io-github-autotest-libvirt.scsi_device.scsi_command_test.with_hostdev.guest_multipath: PASS (64.18 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/lib/avocado/job-results/job-2024-11-11T21.49-11722ca/results.html
JOB TIME   : 64.83 s
```

2024-12-16 02:45 UTC, meinaLi commented
@chunfuwen @smitterl This case is in scsi device plan. The test scenarios is coming from customer. Could you help review it when you have time? Thanks.

2024-12-24 07:22 UTC, smitterl commented on libvirt/tests/src/scsi/scsi_command_test_hostdev.py
> +    get_scsi_cmd = "lsscsi | grep LIO | wc -l"
I'm not a fan of using pipes in bash commands because in case the output is not as expected, it's harder to debug.

How about you do the following?
```
def get_scsi_count(...):
...
    status, output = cmd_status_output("lsscsi")
    scsi_lio_count = len(re.findall("LIO", output))
...
```

2024-12-24 07:22 UTC, smitterl commented on libvirt/tests/src/scsi/scsi_command_test_hostdev.py
> +        run_script_in_guest = "/bin/bash %s" % script_path
If you use "/bin/bash" you do not need the shebang "#!/bin/bash".
In any case, why do you create a bash script and then execute those commands, instead of something like the following?

```python
for cmd in [
    "mpathpersist --out ...",
    "mpathpersist --out ...",
    ...
    "mpathpersist --out --register ..."
    ]:
    s, o = vm_session.cmd_status_output(cmd)
    if s:
        test.error(f"Error running '{cmd}' in VM: '{o}'")
```

Again, I think it might be easier later to debug any issues.

2024-12-24 07:22 UTC, smitterl commented on libvirt/tests/src/scsi/scsi_command_test_hostdev.py
> +        # Delete the first iscsi target
IMO, the comments are unnecessary.

2024-12-24 07:31 UTC, smitterl commented on libvirt/tests/src/scsi/scsi_command_test_hostdev.py
> +        The current libvirt.setup_or_cleanup_iscsi() can't cover it.
This looks like duplicated code. Couldn't you use `iscsi.Iscsi.create_iSCSI(second_params)` instead? It allows for setting the target name, `second_params['target']='tgp1'`.

2025-01-06 06:49 UTC, meinaLi commented on libvirt/tests/src/scsi/scsi_command_test_hostdev.py
> +    get_scsi_cmd = "lsscsi | grep LIO | wc -l"
Thanks for your suggestion. I moved it to a function now.

2025-01-06 06:50 UTC, meinaLi commented on libvirt/tests/src/scsi/scsi_command_test_hostdev.py
> +        run_script_in_guest = "/bin/bash %s" % script_path
Yes, Using list but not script can be more easy to debug in our test. So I've changed it.

2025-01-06 06:50 UTC, meinaLi commented on libvirt/tests/src/scsi/scsi_command_test_hostdev.py
> +        # Delete the first iscsi target
Removed.

2025-02-06 02:02 UTC, meinaLi commented
@smitterl Could you help review this PR again? It's a little urgent now because we need to use it to test on different rhel version. Thanks.

2025-02-06 08:48 UTC, fangge1212 commented on libvirt/tests/src/scsi/scsi_command_test_hostdev.py
> +                test.fail("Register reservation keys failed with message %s!" % output)
Will "123aaa" be in every command's output?

2025-02-10 08:43 UTC, smitterl requested changes
I added an example about how to avoid duplication creating the second device re-using the existing avocado-vt code.

2025-02-10 08:43 UTC, smitterl commented on libvirt/tests/cfg/scsi/scsi_command_test_hostdev.cfg
> +            hostdev_dict = {'type': 'scsi', 'source': {'untyped_address': {'target': '0', 'unit': '0', 'bus': '0'}, 'adapter_name': 'scsi_host%s'}, 'mode': 'subsystem', 'type_name': 'scsi', 'rawio':
+1

2025-02-10 08:43 UTC, smitterl commented on libvirt/tests/src/scsi/scsi_command_test_hostdev.py
> +        The current libvirt.setup_or_cleanup_iscsi() can't cover it.
With `setup_or_cleanup_iscsi` you can't seem to be able to do this, that's right but I referred to using `iscsi.Iscsi`  directly. The following works:

```python
params_1 = {'emulated_image': '/var/tmp/em1', 'target': 'iqn.2025-02.com.virttest:device.em1.target', 'image_size': '1G', 'portal_ip': '127.0.0.1', 'enable_authentication': False} 
params_2 = {'emulated_image': '/var/tmp/em2', 'target': 'iqn.2025-02.com.virttest:device.em2.target', 'image_size': '1G', 'portal_ip': '127.0.0.1', 'enable_authentication': False}

_iscsi_1 = iscsi.Iscsi.create_iSCSI(params_1)
_iscsi_2 = iscsi.Iscsi.create_iSCSI(params_2)
_iscsi_1.login()
dev_1 = utils_misc.wait_for(_iscsi_1.get_device_name, 5, 0, 1, "getting first device name")
_iscsi_2.login()
dev_2 = utils_misc.wait_for(_iscsi_2.get_device_name, 5, 0, 1, "getting second device name")

# dev_1 looks somewhat like "/dev/sdm"
# dev_2 looks somewhat like "/dev/sdn"

...
finally:
   _iscsi_1.cleanup()
   _iscsi_2.cleanup()
   for file in [x['emulated_image'] for x in [params_1, params_2]]:
       if os.path.exists(file):
           os.remove(file)
```

And you could pack the above maybe into a loop to avoid more duplication.

2025-02-12 02:15 UTC, meinaLi commented on libvirt/tests/src/scsi/scsi_command_test_hostdev.py
> +        The current libvirt.setup_or_cleanup_iscsi() can't cover it.
I know what you mean and actually I've tried the above steps before. But actually it's not suitable for this scenario. Because in this test scenario we need to use the same emulated_image to create two different LUNs. The above iscsi.Iscsi.create_iSCSI(params_1) can only use to create different emulate_images, otherwise it will have error "stderr: b'storage object for /var/tmp/em1 already exists: device.em1\n'".

2025-02-12 02:17 UTC, meinaLi commented on libvirt/tests/src/scsi/scsi_command_test_hostdev.py
> +                test.fail("Register reservation keys failed with message %s!" % output)
After changing to run every command one by one, it can't get the "123aaa" for all commands. I directly removed this checkpoint because I think it's enough to check the output status.

2025-02-12 02:17 UTC, meinaLi commented on libvirt/tests/cfg/scsi/scsi_command_test_hostdev.cfg
> +            hostdev_dict = {'type': 'scsi', 'source': {'untyped_address': {'target': '0', 'unit': '0', 'bus': '0'}, 'adapter_name': 'scsi_host%s'}, 'mode': 'subsystem', 'type_name': 'scsi', 'rawio':
Removed.

2025-02-26 16:48 UTC, smitterl commented on libvirt/tests/src/scsi/scsi_command_test_hostdev.py
> +        The current libvirt.setup_or_cleanup_iscsi() can't cover it.
@meinaLi I understand better now thank you. IMO it makes sense to extend the framework to allow for multipath setups.

The following works, I checked your test case and I think it's suitable: https://github.com/avocado-framework/avocado-vt/pull/4067
Please check the example there.

2025-02-27 06:01 UTC, meinaLi commented on libvirt/tests/src/scsi/scsi_command_test_hostdev.py
> +        The current libvirt.setup_or_cleanup_iscsi() can't cover it.
Thanks for your working on this issue. I've added a comment to the avocado-vt PR and updated this PR with this change. Please have a look again.

2025-03-04 07:43 UTC, smitterl approved these changes
We need to make sure that the dependency on https://github.com/avocado-framework/avocado-vt/pull/4067 is not overlooked. Usually for that I add a comment on top of the MR so maintainers see it easily. Please do that too, rest LGTM

2025-03-07 03:46 UTC, fangge1212 approved these changes

2025-03-13 01:48 UTC, merged